### ISSUE TITLE
Cant install on Xiaomi 9T 

### ISSUE THREAD

**Issue by eminozlem** [aj3423/SpamBlocker#1]
![image](https://github.com/aj3423/SpamBlocker/assets/507708/e02563d1-122b-4df3-8e3b-2b9a13554bc1)
![image](https://github.com/aj3423/SpamBlocker/assets/507708/edf9b115-f4be-4476-a5f1-23469bb58ba2)

**Comment by aj3423** [comment]
Oh, the first release is targeting Android 13+, I'll adapt older versions.

**Comment by aj3423** [comment]
Just released version 1.1, now it supports Android 10+. I guess it'll take a couple of days for it to get updated on fdroid, you can download it from the release page.

**Comment by eminozlem** [comment]
Thanks, I hope it works. I ve been looking for a solution to block pesky SMS spam from betting sites without replacing the default messaging app as a whole
