### ISSUE TITLE
Dismiss SpamBlocker notification if the users taps it to open

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#10]
Dismiss SB's own notification if I tap it.

**Comment by aj3423** [comment]
It is supposed to work like that already, all notifications(passed or blocked) from SB are dismissed when the app window is activated, is it not working?

**Comment by bb1a2** [comment]
When I tap SB notification, it opens the default SMS app but the notification remains. I have to clear it by swiping every time

**Comment by aj3423** [comment]
Done, try this action build: https://github.com/aj3423/SpamBlocker/actions/runs/8866115240
