### ISSUE TITLE
Testers wanted for the closed testing of Google Play

### ISSUE THREAD

**Issue by aj3423** [aj3423/SpamBlocker#102]
Hi,
I'm trying to publish SpamBlocker to Play Store, Google requires any app must be tested by 20 testers for at least 14 days.
Currently I already have 60+ testers, and 2 days left :)
But anyway, join if you like :)

Steps to join the closed testing:
0. You need a Google Account, and have Play Store installed
1. Join the testing group:
   - open https://groups.google.com/g/spamblocker-test
   - click the button "Join group"
3. Become a tester:
   - open https://play.google.com/apps/testing/spam.blocker
   - click the button "BECOME A TESTER"
4. Download the app: https://play.google.com/store/apps/details?id=spam.blocker
5. Keep it installed for at least 14 days.

**Comment by vlakoff** [comment]
I have registered. The more testers, the better to please Google.

I can't bear spam calls anymore, and your app seems to be a really good fit to avoid them.

(Sadly, Android 9 isn't supported, and it's not possible to do. That makes one additional reason to admit I have to leave my good old Xperia XZ1 Compact.)

**Comment by aj3423** [comment]
@vlakoff Thank you and other people who helped testing, it has passed the closed testing and will be live in a couple of days.
