### ISSUE TITLE
CVS import issue

### ISSUE THREAD

**Issue by FoolishFool4202** [aj3423/SpamBlocker#103]
The cvs import option for multiple rules on numbers is broken and just generates empty rules
![Screenshot_20240731_134351_SpamBlocker](https://github.com/user-attachments/assets/edb7d7a8-1e20-4d0b-9d07-18a688313e21)

**Comment by aj3423** [comment]
It's based on column headers, plz check the balloon tip.

**Comment by aj3423** [comment]
I'll add a warning when the .csv doesn't contain the required column "pattern".

**Comment by FoolishFool4202** [comment]
Oh I pretty much just downloaded the cvs file and tried to see if that worked.

**Comment by FoolishFool4202** [comment]
Please tell me there is a tutorial...

**Comment by aj3423** [comment]
I think there would be video tutorials in the future, but currently the balloon tooltips are the best instructions.
In your case, just add a column header at the top of the .CSV file, like:

pattern, other_optional_columns, ...
11111, ..., ...
222
333, ...
