### ISSUE TITLE
RepeatedCall not working in rule test

### ISSUE THREAD

**Issue by bapeey** [aj3423/SpamBlocker#104]
Repeated call is ignored on rule test, my regex is .* with repeatedCall enabled, test always shows blocked but its working with real calls.

**Comment by aj3423** [comment]
Yeah that's expected, because RepatedCall depends on the real call history, testing won't add new record to the history log, testing it requires making a real call. 
I'll note this in the balloon tooltip, thanks for reporting.

**Comment by aj3423** [comment]
On a second thought, it can be supported. 
I made some changes to the RepeatedCall, now,
- When testing, it will read from both the real call log and the local database.
- When being called, it will only read from the real call log.

Done in the latest tag.

**Comment by bapeey** [comment]
tysm, it was confusing at first because I thought that repeated call was not working
