### ISSUE TITLE
Filter the content of an SMS by recognizing several words one after the other

### ISSUE THREAD

**Issue by Matthieu203** [aj3423/SpamBlocker#106]
Hello,

Thank you for creating such an awesome and well built app.

I added a regular expression to recognize text messages that contain the following words in a row: avant majoration http

For example, to block this type of text message: _"ANTAI: Dernier rappel avant la majoration de votre amende à 135,00 euros: https://reglementsdirect.com"_

Here is my regular expression, tested and validated on https://regex101.com/
`.*avant.*majoration.*http.*`

However, when I test in your SpamBlocker application, it tells me that the text message is accepted.

Can you help me find my error please?

Thank you.

**Comment by aj3423** [comment]
Your regex works fine:
![image](https://github.com/user-attachments/assets/b23381ba-2e2c-4d5d-93b9-f0c1c86ab38a)

Please check the SMS history tab, it shows why messages are blocked or allowed. What's the reason in your case?
![image](https://github.com/user-attachments/assets/2bc41eaf-21b1-44fe-bc01-96154450df69)

**Comment by Matthieu203** [comment]
Thank you for your quick answer.
Here screenshots of my settings 👍 
![screenchot 1](https://github.com/user-attachments/assets/5a598fbf-ea44-48c3-9d77-072b366684ec)
![screenchot 2](https://github.com/user-attachments/assets/7d72fb7c-c216-469d-81b7-66b0d040a740)
![screenchot 3](https://github.com/user-attachments/assets/f4b938e9-6ad8-4a65-8621-ecd9d9e63732)

**Comment by aj3423** [comment]
That's strange, can you export the configuration and paste here? (Json format)

**Comment by Matthieu203** [comment]
`{
    "global": {
        "enabled": true,
        "callEnabled": true,
        "smsEnabled": true
    },
    "theme": {
    },
    "language": {
    },
    "contacts": {
        "enabled": true
    },
    "stir": {
        "enabled": true,
        "isExcusive": true
    },
    "repeatedCall": {
        "enabled": true,
        "times": 1,
        "inXMin": 5
    },
    "dialed": {
        "enabled": true,
        "inXDay": 10
    },
    "recentApps": {
        "list": [
            "ee.mtakso.client"
        ],
        "inXMin": 10
    },
    "blockType": {
    },
    "offTime": {
        "enabled": true,
        "stHour": 19,
        "stMin": 30,
        "etHour": 21
    },
    "numberRules": {
        "rules": [
            {
                "id": 1,
                "pattern": "(?:33)?(1(?:62|63)|2(?:70|71)|3(?:77|78)|4(?:24|25)|5(?:68|69)|9(?:48|49))\\d{6}",
                "patternFlags": {
                    "value": 5
                },
                "patternExtraFlags": {
                    "value": 5
                },
                "description": "Bloqué appel pub",
                "flags": {
                    "value": 1
                },
                "importance": 1,
                "schedule": "23456,00:00-00:00,true"
            }
        ]
    },
    "contentRules": {
        "rules": [
            {
                "id": 2,
                "pattern": ".*avant.*majoration.*http.*",
                "patternFlags": {
                    "value": 5
                },
                "patternExtraFlags": {
                    "value": 5
                },
                "description": "Spam Amende",
                "priority": 12,
                "flags": {
                    "value": 3
                },
                "importance": 1,
                "schedule": ",00:00-00:00,false"
            },
            {
                "id": 1,
                "pattern": ".*veuillez.*http.*",
                "patternFlags": {
                    "value": 5
                },
                "patternExtraFlags": {
                    "value": 5
                },
                "description": "spam livraison ",
                "priority": 3,
                "flags": {
                    "value": 3
                },
                "importance": 1,
                "schedule": ",00:00-00:00,false"
            }
        ]
    },
    "quickCopyRules": {
        "rules": [
            {
                "id": 1,
                "pattern": "(?<=code.{0,3})\\d+",
                "patternFlags": {
                    "value": 5
                },
                "patternExtraFlags": {
                    "value": 5
                },
                "description": "Copier code sms",
                "isBlacklist": false,
                "flags": {
                    "value": 26
                },
                "schedule": ",00:00-00:00,false"
            }
        ]
    }
}`

**Comment by aj3423** [comment]
I can't reproduce the problem, it's blocked:
![image](https://github.com/user-attachments/assets/68911ae5-0947-455b-809a-ff5ad2c71ebc)

**Comment by Matthieu203** [comment]
I use version 1.19 from Store F-Droid, with Android 14.

**Comment by aj3423** [comment]
I just downloaded v1.19 from F-Droid and tried on Android 14, it still works.
This is really strange, is it just this message or rule not working? What about other rules? For example, does `.*` work at all?

**Comment by Matthieu203** [comment]
The other rules work.
I am testing this rule with real messages that I receive, so far I have only received one message with this new phone.

**Comment by Matthieu203** [comment]
In fact, I am trying to filter spam sms that contain certain words in the message like please, delivery - surcharge, fine.

In France, there are spams with fines, social assistance, parcels in delivery, etc...

And to spot a spam sms, you have to recognize several words in a certain order.

However, to match several spam sms, it is necessary to use different regular expressions.

I have not found any other solutions to simplify this type of spam SMS filtering.


Below are examples of spam sms (translated into English)

_ANTAI: Last reminder before the increase of your fine to 135.00 euros: https://reglementsdirect.com_

_La Poste
Following the Paris 2024 Olympic Games and despite our efforts, your package No.: CAC09244 has suffered a delivery problem.
Please update your delivery information on our website: https://mes-services-colissimo.info_

_UPS: Your package has been put on hold because it does not meet the weight requirements. Please go to the following address: https://ma-livraison-ups.com_

**Comment by aj3423** [comment]
What about this: `.*(antai|olympic|ups).*`, or simply `.*https:.*`

And what about the previous issue that passed by default, got any clue?

**Comment by Matthieu203** [comment]
Thank you for your help.
I use this : `.*(amende|livraison|ups).*https.*`

It's working.

Congratulations, your app is very great !
