### ISSUE TITLE
Rules not saved when I hit save

### ISSUE THREAD

**Issue by devoid1** [aj3423/SpamBlocker#11]
Latest version 1.3.  I checked
-enabled
-contacts

and when i go to enter phone number filter
regex pattern - .*
description - noncontact
priority - 1
apply to calls and sms
type blacklist
default notifications

hit SAVE and it goes back to the main screen but no rule shown like the screen shots and a spam call rang through.
i cleared cache and data and tried again, same response
i uninstalled app and reinstalled through github, same response

it never asks me for storage permission, does it need that to store blacklist?
pixel 7a. calyxos. degoogled. 

**EDIT**  downloaded 1.2 off of f-droid and it saves ok.  update to 1.3 directly from github with APK, saves ok.  when i clear rules (to get rid of testing rules) they clear and when i add another rule ALL rules (even deleted ones) come back.  i have to uninstall app to get rid of rules.  reinstall latest off of github same problem again, wont save rule.  uninstall and install 1.2 from fdroid, saves rules again.

**Comment by aj3423** [comment]
I can reproduce the "Clear" bug, it brings back all the "Clear"ed rules when adding a new rule. Actually I'm about to remove this "Clear" button, replace it with a "Test" button. The point of this app is to do the job with very few rules instead of lots of specific numbers, the "Clear" won't be necessary. You can delete a rule by swiping left, it should work fine.

However I can't reproduce the bug that not being able to add new rule right after re-installed. It doesn't require storage permission, it stores database in its own internal storage, degoogled should be fine.

**Comment by aj3423** [comment]
Try this action build: https://github.com/aj3423/SpamBlocker/actions/runs/8843504501

The "Clear" button is removed, the "Test" feature will soon be done in v1.4. The bug "rules not saved" is fixed, my brain is fixed as well, sorry for the previous wrong info, and thanks for your feedback.

**Comment by devoid1** [comment]
thanks for your quick response, and thanks for writing the app in the 
first place. I have been using Yet Another Call Blocker because it's 
simple and just sends non-contacts to voicemail. it has not been updated 
for several years and has a whole database thing that no longer functions 
right. your app is just i needed.

Apr 26, 2024 12:32:46 AM aj3423 ***@***.***>:

**Comment by devoid1** [comment]
action build works.  adds number and can slide and delete.  nice job!

question.  while i was testing it i got a phone call from a non-contact and even though it didnt ring, my phone showed the call and vibrated.  is that the way its supposed to work?  i had imagined that if i had notifications set to NONE that i would not see anything at all when a spam call comes in.

**Comment by aj3423** [comment]
Strange, the rule `.*` should block all non-contact calls, that call should be blocked.
Is that call listed in history page? If so, does it show a green "pass"?

BTW, the "Test" feature is done in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/8857903749, you can test rules without waiting for new incoming call.

**Comment by devoid1** [comment]
ok.  tried the new build, called myself from another unknown phone number.  blocked correctly.

i tried the TEST function and it returns results correctly, including properly catching contacts.  looks like problem is resolved.  thank you.
