### ISSUE TITLE
Will this app work Google call screening?

### ISSUE THREAD

**Issue by minhgi** [aj3423/SpamBlocker#110]
Will this app work with Google call screening? I got a Pixel 8 Pro.  Just discovered your app.

**Comment by aj3423** [comment]
I don't have experience with google call, if it relies solely on the internet then it won't work, if it supports forwarding to your sim card, then maybe yes.

**Comment by minhgi** [comment]
I have your app install and set it as the default ID/Spam app.  I will let you know if it works and not.  Awesome idea though.  So far I didn't get any spam call to get a result.

**Comment by aj3423** [comment]
Closing for now, feel free to reopen if any further issue.
