### ISSUE TITLE
Do not disturb problem

### ISSUE THREAD

**Issue by MinhBui2002** [aj3423/SpamBlocker#111]
I try to add this app to the white list of the "Do not disturb" feature on a Samsung phone (to allow call notification sound). However, I can not find the app on the "Selecting app" screen. How can I fix this ?

**Comment by aj3423** [comment]
The "incoming call screen" is actually shown by the call app, maybe you should add that app to the whitelist instead?

However,  on my phone, this app appears in the list of choosing "Apps that can interrupt DND". The app name could have been translated due to the local language setting.
