### ISSUE TITLE
I can't delete rules

### ISSUE THREAD

**Issue by NicolasWladyslaw** [aj3423/SpamBlocker#112]
When I long press on a rule in the list, I can :

+ duplicate the rule ;
+ delete all the rules.

But there is no way to delete the rule. I can't find how to delete one rule at a time.
I'm on /e/OS and I installed Version 1.20 (spam.blocker) yesterday via the App Lounge (F-Droid).

**Comment by aj3423** [comment]
![Screenshot_20240820-235340_SpamBlocker.png](https://github.com/user-attachments/assets/9d3ca6a3-334d-4faa-8b6e-4979ce742d11)

Swipe left, as described in the balloon tooltips.
I'll add a "Delete Rule" menu item.

**Comment by NicolasWladyslaw** [comment]
Thanks !
