### ISSUE TITLE
Contact pictures not always right in call tab

### ISSUE THREAD

**Issue by djelloul78** [aj3423/SpamBlocker#113]
Hi there. 

I'm observing a strange app behaviour regarding contact pictures in the call tab of SpamBlocker (SB) since a while.
In the list of allowed and blocked phone numbers screened by SB, the thumb pictures located in the left of each contact is not always right. 
Please look at the following picture: 
![Screenshot_20240822_160156_SpamBlocker](https://github.com/user-attachments/assets/37582f85-9dbf-4311-8e35-cd62d2e1d665)

I have censored family names for privacy reason, so do excuse the raw job done in the screenshot. 

As you can see, there are pictures for some contact in this list, but it also appear that some blocked numbers seems presented with a picture from a previous contact and it shouldn't be the case as these phone numbers aren't even stored in my phone contact list.

Is it something that you observe on your side or am I the only one having such issue?

I don't know if this issue applies also on the SMS tab as I'm not using it but it is maybe concerned also.

Thank you for your attention.

**Comment by aj3423** [comment]
Yeah, I thought it has been fixed, but seems not. The RecyclerView is trying to save some memory and it shows cached image, it's i one of the pitfalls of the current XML UI solution.
Currently I'm in the middle of migrating from the XML UI to jetpack compose, this issue will no longer exist after that. It takes a while though :)

**Comment by djelloul78** [comment]
As usual, thank you for your quick feedback. 
And you know how I work with you when I open issues:
I open them but there's absolutely no emergency behind.

The app has reached a great level of maturity, so we're not going to complain because of a visual flaw that has absolutely no impact on the main app mission...
Be proud of what you're sharing with us.

Thank you again!

**Comment by aj3423** [comment]
Fixed in v2.0
