### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [aj3423/SpamBlocker#12]
https://github.com/aj3423/SpamBlocker/releases/tag/v1.3 -> points to https://github.com/aj3423/SpamBlocker/commit/b540505b130e2aba953278a57c7d3c593fd39028

But your APK was built from d6e0e8dfa93fec8045b64b5adebe679459b0d975 ? ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6719209532#L3126

also.. the APK is gone?

/PS: in the future, always build from the tagged commit 

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/c86d157ca23507d0718d870274b2f8b53c3c8c24

**Comment by aj3423** [comment]
Got it, the v1.3 introduced a serious bug that user reported today: https://github.com/aj3423/SpamBlocker/issues/11

So I deleted the v1.3,  I thought if I should delete before fdroid merges it, but I didn't expect the merge happens that that quick.

Sorry for the trouble.

**Comment by licaon-kter** [comment]
Yeah, checkupdate runs continuously, sometimes it's faster than devs expect, but slower when they need it :) :)

**Comment by bb1a2** [comment]
It builds now. v1.4 is live.
