### ISSUE TITLE
Feature: block by caller ID name 

### ISSUE THREAD

**Issue by cdmichaelb** [aj3423/SpamBlocker#120]
I get spam calls from a certain caller ID name but they're always using random numbers with random area codes so I can't regex a number to block them. Their caller ID name always shows up the same though.

**Comment by aj3423** [comment]
That caller ID is displayed by the default call app, it relies on some built-in database. When the call is intercepted by the Caller ID app, there is no information about the name.

To confirm this, I reverse engineered the Samsung call app: `adb pull /system/priv-app/SamsungInCallUI/SamsungInCallUI.apk`:

It shows log:

> SCallUI : PhoneNumberLocatorRepository - query: start
> ...
> SCallUI : PhoneNumberLocatorRepository - query: onSuccess, cursor count: 1, uri: XXX, timeMillis:24
> SCallUI : PhoneNumberLocatorRepository - putIntoCache : PhoneNumberLocatorModelImpl{ mLocation : XX Telecom }

The *XX Telecom* is the result of this query, it's displayed as Caller ID name, the related code:
![image](https://github.com/user-attachments/assets/8c9407cd-14ad-4206-9665-ac6a4532c69a)

I don't want to integrate any database:) However, if you find the database somewhere, you can import it as .csv.

**Comment by cdmichaelb** [comment]
Ah, thanks for looking into it and sharing the info. I guess this is probably why no other app has implemented it too. Shame the mainstream apps don't implement it since they likely have access to the databases.

**Comment by aj3423** [comment]
There's actually a public offline database available, so blocking by area code is now supported.
