### ISSUE TITLE
feature idea: after blocking / silencing call, send a predefined SMS to the number

### ISSUE THREAD

**Issue by redcat42** [aj3423/SpamBlocker#129]
saw this request in the comments of another app, thought it is not a bad idea, especially for those who have an unlimited SMS plan 

thought I'd share

![1](https://github.com/user-attachments/assets/ed941c33-e948-4bb3-9c94-dff3c5994f4c)

**Comment by aj3423** [comment]
Not necessary in this app, for those who really need to talk, they will call you twice.

**Comment by redcat42** [comment]
true, that's the same option android's 'do not disturb' gives :)
