### ISSUE TITLE
Add SIM Filter

### ISSUE THREAD

**Issue by rafaelmatuo** [aj3423/SpamBlocker#131]
Please can you add a SIM filter?
E.g.: I'd like to block all SIM 2 calls because I use this SIM just for data.

**Comment by aj3423** [comment]
See this: https://issuetracker.google.com/issues/348442539
I fired this feature request to Google, I'll add this feature once google finishes the issue, maybe give a "+1" to it.

**Comment by CyanDragonS** [comment]
I'm sorry google is not accessible in my area. I have the same functional needs.
You mean this feature is not possible with Android's limitations?

**Comment by aj3423** [comment]
@CyanDragonS  Currently it's not possible, there is a workaround, but Cons > Pros, so I'm waiting for the upstream to support it. It has been accepted, with a very low priority P4..

**Comment by CyanDragonS** [comment]
@aj3423
I found a way to separate two sim cards.
Android SubID.

**Comment by aj3423** [comment]
@CyanDragonS Where is this SubID? Doesn't seem to exist in the TelecomCall.Details.

**Comment by CyanDragonS** [comment]
> @CyanDragonS Where is this SubID? Doesn't seem to exist in the TelecomCall.Details.
> 

https://developer.android.com/reference/android/telephony/SubscriptionManager#getSubscriptionId(int)

**Comment by aj3423** [comment]
@CyanDragonS Yeah, that API requires the slot index, slot 0 for sim1, slot 1 for sim 2. The real problem is how to get the slot, for SMS receiver, I have this code:
```kotlin
fun getSimFromIntent(ctx: Context, intent: Intent?) : String {
    // https://stackoverflow.com/questions/35968766/how-to-figure-out-which-sim-received-sms-in-dual-sim-android-device
    try {

        val bundle = intent?.extras ?: return DEFAULT_SIM

        var slot = -1
        listOf("slot", "simSlot", "simId", "slot_id", "simnum", "phone", "slotId", "slotIdx", "android.telephony.extra.SLOT_INDEX")
            .first {

                slot = bundle.getInt(it, -1)
                slot != -1
            }

        val subMgr = ctx.getSystemService(Context.TELEPHONY_SUBSCRIPTION_SERVICE) as SubscriptionManager

        val subInfo = if (slot != -1) {
            subMgr.getActiveSubscriptionInfoForSimSlotIndex(slot)
        } else { // no slot, check subscription
            val sub = bundle.getInt("subscription", -1)
            if (sub == -1)
                return DEFAULT_SIM
            subMgr.getActiveSubscriptionInfo(sub);
        }
        return subInfo.number

    } catch (e: SecurityException) { // when permission not granted
        return DEFAULT_SIM
    }
}
```
It works for SMS,  but for call screening, there isn't such slot information in call Details.

**Comment by CyanDragonS** [comment]
Maybe threr have another way to get call info? Like android broadcast?

**Comment by aj3423** [comment]
In the CallStateReceiver, there is the sim info. However, it would be too late, the call would have started ringing, and the block/silence mode will no longer work, the lock screen will be turned on and there will be a call end tone.

**Comment by CyanDragonS** [comment]
Oh, that's right. Thank you. I guess I still have a lot to learn.

**Comment by CyanDragonS** [comment]
I have a question, if I set the first three seconds of the ring is blank, then start of the ring, if you can add this function, maybe it can also temporarily work? Or will it no longer work at all?

**Comment by aj3423** [comment]
By the "the call would have started ringing",  I mean it must have already passed the CallScreeningService.

The current logic is, the result of whether it should be blocked or allowed must be determined in the CallScreeningService, but with that workaround, it will be delayed to the next stage, which will complicate the logic a lot and make it difficult to maintain.

So technically it's possible, it's just too many drawbacks, and not that necessary, I mean if the rules are doing good job blocking calls from sim1, you shouldn't be getting any spam on sim2.

**Comment by rafaelmatuo** [comment]
This apk https://play.google.com/store/apps/details?id=com.mglab.scm&hl=en,
has a similar solution for this workaround.

Em sáb., 19 de out. de 2024 às 05:44, CyanDragonS ***@***.***>
escreveu:

**Comment by aj3423** [comment]
> This apk https://play.google.com/store/apps/details?id=com.mglab.scm&hl=en, has a similar solution for this workaround. 

See the analysis about this apk here: https://github.com/aj3423/SpamBlocker/issues/59#issuecomment-2138102091

**Comment by aj3423** [comment]
It's now supported: https://github.com/aj3423/SpamBlocker/issues/169#issuecomment-3617874545

**Comment by rafaelmatuo** [comment]
Amazing, I was using call forwarding to 00000, this will works better, thanks to continue supporting this app, I really appreciate
