### ISSUE TITLE
some UI feature

### ISSUE THREAD

**Issue by Umotas** [aj3423/SpamBlocker#133]
I have 3000 and more spam numbers.
Maybe to hide all spam numbers from 'settings - list'. And to make a special list only for spam numbers.

**Comment by aj3423** [comment]
No matter how many numbers, it won't exceed 60% of the screen height, and in the latest version there are scrollbars, they are scrollable, I don't think it's necessary to hide them.

**Comment by aj3423** [comment]
Supported in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/10957829013
A new context menu item "Search Rule".

**Comment by aj3423** [comment]
Good idea, currently it's swipe left, but I'll change it to close on losing focus, it'll more convenient and intuitive.

**Comment by aj3423** [comment]
No need to support swipe left since it will disappear when losing focus.

The description is supposed to be simple, one line is enough. But the regex can be very long, it's displayed in multi-lines, up to 10 lines.

**Comment by aj3423** [comment]
> I try to scroll the settings down. I must catch the narrow string "Message Rules" when scrolling down.

Try the scrollbar, put your finger at the most right edge of the screen and start dragging up/down. 

> You don't sort 'Message Rules'. Why?

Actually they are sorted, in the order of:  priority -> description -> regex

BTW, those regex like 0800.... will never work, the leading 0 is ignored, unless the regex flag "Raw Number" is set. I suppose these rules were imported, not manually added, why not import them as a single rule, why 2000 rules?

**Comment by aj3423** [comment]
Yeah, it looks like (11|22|33...),  I mean the feature "Import .csv as a single rule" by long pressing the "New" button.
2000 numbers should be fine, but you don't want to edit it later, since it's super long.

**Comment by aj3423** [comment]
Added in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/11033104414

"Delete All(30) Rules" and "Delete Duplicated Rules"
