### ISSUE TITLE
small suggestion: In the recent apps option, set the recent used time limit for each app independently

### ISSUE THREAD

**Issue by CyanDragonS** [aj3423/SpamBlocker#135]

**Comment by CyanDragonS** [comment]
1.In the recent apps option, set the recent used time limit for each app independently
2.set more than one off time. (You can pick a day of the week like the number rules)

**Comment by aj3423** [comment]
> 1.In the recent apps option, set the recent used time limit for each app independently

What's the use case? Usually 5-10 min should be enough.

> 2.set more than one off time.

OffTime is just a "quick setting", it's convenient but limited, to get more precise control, you can use the Rule Schedule.

**Comment by CyanDragonS** [comment]
1.In my area, food delivery usually takes 30-40 minutes, and when the delivery is delivered, I need to enter the APP to confirm the order (the time will be recalculated after entering the APP), but this time will be particularly long for my work APP, because I will enter the lunch break after eating, and the lunch break will be over after 45 minutes.
2.OK, Thanks.

**Comment by aj3423** [comment]
Individual duration for RecentApps, supported in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/11002615898

**Comment by CyanDragonS** [comment]
> Individual duration for RecentApps, supported in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/11002615898

So fast? Incredible!

**Comment by CyanDragonS** [comment]
![Screenshot_2024-09-24-11-43-28-507_spam.blocker-edit.jpg](https://github.com/user-attachments/assets/56a889bf-9e17-454e-9990-122758f500a6)

Maybe there's a little bug here? After setting the time for each APP separately, the total time previously set will still be displayed on the right side of the recent app
