### ISSUE TITLE
auto/manual update imported rules from csv

### ISSUE THREAD

**Issue by TyroSpy** [aj3423/SpamBlocker#136]
Please make auto/manual update imported rules from csv

**Comment by aj3423** [comment]
What is the use case?

**Comment by TyroSpy** [comment]
At the moment, CallBlocker can't work with a common csv list of rules and I have to split it into separate ones like whitelist, blacklist, etc. So I have four separate lists of rules. Then I sync the my own csv files with my smartphone. Then I have to delete all the old lists in the application and import new ones manually one by one. It would be nice to simplify this update process as much as possible, because I update my rules lists very often.

**Comment by aj3423** [comment]
@TyroSpy I do have a plan to support an auto import system, like an extension system, it's for importing from the online database, but it can also work for local files. I'll fire an proposal issue later, for gathering all possible requirements, it'll take some time.

Currently you can add a column `isBlacklist` in the .csv file, so you don't need to split it into 4 files, for example:

pattern,  isBlacklist
111, true
222, false
...

For a complete list of supported columns, check the balloon tooltip of the Number Rules:
![image](https://github.com/user-attachments/assets/0be3967f-5d21-45a4-8f99-58dabbadb40a)

The drawback is, it only works for importing as multiple rules, when it's imported as a single rule, all numbers will be either blacklist or whitelist. It will be impossible to manually delete the previous imported rules, unless you delete them all.

When importing as single rule, you need two files for blacklist and whitelist, but you have four files, what are the other two files for?

**Comment by CyanDragonS** [comment]
Or, import it automatically when the specific list file in the specific folder is updated? In this way, multiple devices can be automatically synchronized with other files(Use some file sync apps)

**Comment by aj3423** [comment]
> It may be possible to make a change to the current export file format, which does not have to support the previous format.

The current export functionality is for backing up all settings, not only for the regex rules.

> Give permission to use a folder, give the app permission to monitor usage, so that the file can be automatically re-imported when the date is updated.

Monitoring file/directory requires [Foreground Service](https://developer.android.com/develop/background-work/services/foreground-services), from the doc:
> Foreground services show a status bar notification, to make users aware that your app is performing a task in the foreground and is consuming system resources.

The notification can't be avoided, and it consumes more battery, no plan to support it.

**Comment by TyroSpy** [comment]
no need permanently monitoring, only with open apps or without any monitoring, but just function for manual update

**Comment by aj3423** [comment]
Closing this, this is the plan: https://github.com/aj3423/SpamBlocker/issues/140
