### ISSUE TITLE
Block call start with + ?

### ISSUE THREAD

**Issue by fauguswanto** [aj3423/SpamBlocker#14]
Either I am not understand how Regex work, or it didn't work as expected?
![Screenshot_2024-04-27-12-59-30-790_spam blocker](https://github.com/aj3423/SpamBlocker/assets/84930076/85c378af-bcd3-41b1-b229-4507319abb02)
![Screenshot_2024-04-27-12-59-33-418_spam blocker](https://github.com/aj3423/SpamBlocker/assets/84930076/bc82b5af-123c-4186-866b-9a3355c14f42)

**Comment by aj3423** [comment]
It's a bug, special characters are not removed before checking, now it's fixed, try this action build: https://github.com/aj3423/SpamBlocker/actions/runs/8857903749

BTW, now there is a "Test" feature, you can test your rules directly, no need to wait for new incoming call.

**Comment by fauguswanto** [comment]
How bout the Regex I wrote, is it already correct? I tried new build and it still pass the call that I filtered

**Comment by aj3423** [comment]
Strange, I tested with this number and it is blocked:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/5978ce09-c721-44a5-88b9-887979ba736a)
with the rule:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/b0f56c29-0b89-49d1-b438-2f9b9205ec23)

Does it still shows "pass" in the history log page ?  Also check the regex rule, does it contain any trailing spaces?

**Comment by aj3423** [comment]
Oh wait , it's  a bug

**Comment by fauguswanto** [comment]
Thanks for testing it, after I remove the filter then re-input it again with same regex, now it's blocked when I tested it. Thanks, I really appreciate it !

**Comment by fauguswanto** [comment]
Seems like the call still managed to get it but the application said blocked.. 

![Screenshot_2024-04-27-16-56-58-263_com gravity roo sea](https://github.com/aj3423/SpamBlocker/assets/84930076/b2090b05-88bf-49f0-aac9-f3fdd7aa59a0)

**Comment by aj3423** [comment]
What Android version is this?

**Comment by fauguswanto** [comment]
Android 14, Poco X5 5g

**Comment by aj3423** [comment]
I just tried again on Android 10 emulator with the exact number, and Android 14 real phone with a different number,  both works.
Unfortunately the call simulation doesn't work for Android 14 emulator.
Really strange, maybe check if any permission disallowed in system setting.

**Comment by fauguswanto** [comment]
I am able to resolve this issue by reinstalling the apk, then inputting the filter again. Now it's works
