### ISSUE TITLE
v3.0 plan, spam database and automation

### ISSUE THREAD

**Issue by aj3423** [aj3423/SpamBlocker#140]
This is the plan for v3.0, integrate spam database and automation, plz share your ideas if it doesn't cover your use case.

**Edited**: It's done in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/11265746145

The proposal:

Table of Contents
=================
   * [Spam Database](#spam-database)
   * [Automation Workflow](#automation-workflow)
     * [Triggers](#triggers)
     * [Actions](#actions)
     * [Presets](#presets)
       * [Examples](#examples)
         * [DNC daily .csv](#dnc-daily-csv)
         * [Generate regex rule from local .csv](#generate-regex-rule-from-local-csv)
         * [Daily backup](#daily-backup)

# Spam database
With the Automation Workflow(see below), it'll be possible to import any database into this app.

There'll be a new item "Database" in the Quick Settings section. 

# Automation Workflow
On the setting page, there'll be a section showing all workflows. 
A workflow is made of two things:
 - A trigger, for when it should be executed.
 - A sequence of Actions, each executed in order, the output of one action becomes the input for the next.

## Triggers

 - `manually` 
 - `hourly`
 - `daily`
 - `weekly`
  
## Actions

 - network operations:
   - `http_download`
     - config
       - *url*: "https://...", supports 
     - output
       - ByteArray

 - parsers: 
    - `parse_csv`
      - config
        - *column_mapping*, e.g.: { "pattern": "Company_Phone_Number" }
      - input
        - ByteArray
      - output
        - RuleList

 - regex rules
   - `add_regex_rule`, create a new number rule like `(11|22|...)`
     - config
       - *description*
       - *priority* 
     - input
       - RuleList
   - `merge_regex_rule`, merge numbers to the rule with the specific description, create if not exists
     - same as `add_regex_rule`, *priority* is only used when creating new rule
   - `replace_regex_rule`: replace a rule with the same description, and create if not exists
     - same as above

 - spam database:
   - `spam_db_add`
     - config
       - *priority*
     - input
       - RuleList

 - file operations:
   - `read_file`
     - config 
       - *dir*, e.g.: "{Downloads}"
       - *filename*, e.g.: "input.csv"
     - output 
       - ByteArray

 - backup and restore: 
    - `backup_export`
     - config 
       - *dir*, e.g.: "{Downloads}"
       - *filename*, e.g.: "SpamBlocker.auto.bak"

## Presets

A workflow can be built from scratch with the UI, there will be a build dialog, however, if it's widely used, it will be included in the presets.

A preset is simply a json, it can be imported to generate the workflow.

#### DNC daily .csv

It will download [DNC](https://www.ftc.gov/policy-notices/open-government/data-sets/do-not-call-data) daily .csv and import the numbers into the database:

```json
{
  "trigger": {
    "type": "weekly",
    "weekdays": [1,2,3,4,5],
    "at": "01:00:00"
  },
  "actions": [
    {
      "type": "http_download",
      "url": "https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_{year}-{month}-{day}.csv"
    },
    {
      "type": "parse_csv",
      "column_mapping": { "pattern": "Company_Phone_Number" }
    },
    {
      "type": "spam_db_add"
    }
  ]
}

```

#### Generate regex rule from local .csv:

```json
{
  "trigger": {
    "type": "daily",
    "at": "00:00:00"
  },
  "actions": [
    {
      "type": "read_file",
      "dir": "{Downloads}",
      "filename": "1.csv"
    },
    {
      "type": "parse_csv",
      "column_mapping": { "pattern": "my_number_column" }
    },
    {
      "type": "replace_regex_rule",
      "description": "imported from 1.csv",
      "priority": 10
    }
  ]
}
```

#### Daily backup:

```json
{
  "trigger": {
    "type": "daily",
    "at": "00:00:00"
  },
  "actions": [
    {
      "type": "backup_export",
      "dir": "{Downloads}",
      "filename": "SpamBlocker.auto.bak"
    },
  ]
}
```

**Comment by aj3423** [comment]
@Umotas 
> Every number can be spam today and cannot be spam tomorrow.

It can be solved by adding an automated workflow `db_cleanup`, with a configurable expiry, it will be included in the presets. 

> synchronize / parse local CSV-file

There's a feature request for it. I put it here just to show that it can grab data from anywhere, HTTP, local files, or even IPFS databases in the future. It can be easily supported by adding a new `action` protocol.

No plan for custom themes, the dark theme is just for reducing eye strain in the midnight.

@realgooseman 

> Having a custom filter + third-party crowdsourced spam database would make SpamBlocker very powerful.

Exactly, it will be capable of integrating all public databases into this app.

**Comment by aj3423** [comment]
@realgooseman

> Will the spam databases be included in the app with enable/disable buttons or will the user have to import them manually ?

The database will be a new row in the quick settings, looks like:

> Contact ...
> STIR ...
> Database            [ 12345 records ]  [switch box]
> ... 

And there will be a new section "Automation", just like the regex rules, it's a list of workflow items. Click a workflow to popup the configuration dialog, you can edit it with UI, no need to manually compose the json, the json is only for exporting a workflow so that you can share it to others. If you set a workflow as "schedule = daily, actions = [ http_download, import_to_db ]", then the database will get updated everyday, if you change it to "schedule = manually", then you can manually run it.

> Are there European public spam databases, I believe there is STIR/SHAKEN for US citizens but I'm not familiar with European alternative ?

I don't know if there are any public European databases, but if there are any, I'll add them to the presets. And from google, because SHAKEN doesn't work for international calls, it would be ineffective unless other countries also implement it. So far, France seems to be the only European country that has implemented it (in 2023), maybe there will be more countries in the future.

> Truecaller/Hiya

Maintaining such proprietary databases is time and money consuming, if they were to make it publicly accessible, it could be easily integrated with the workflow (if it's free and opensource), but it's impossible for them to do that.

**Comment by thomasjimmy** [comment]
I don't know whether only the suggestions related to spam database integration are welcomed.
What I feel this app really need is
An optional way to filter/delete the actual message instead of just the notifications.
There is another abandoned fdroid app [Blacklist Blocker ](https://f-droid.org/en/packages/com.kaliturin.blacklist/) which does this thing well. What misses in that app is the regex checking. It only allows sender blacklisting. It would be complete, if we can bring in those features of that app in this one.

**Comment by aj3423** [comment]
@thomasjimmy 

The database can't be generic without a flexible automation system.

About deleting messages, from that app's readme:

> it is required to give to the application the permissions of "Default SMS-application" in the Settings.

That's why it's capable of deleting messages, it has to be the default app.

**Comment by thomasjimmy** [comment]
Hi @aj3423 

Can we get a feature, where users can choose an option to delete the messages from the actual message instead of just filtering notifications? Those users who choose this feature alone need to give the "Default SMS-application" permission. This will increase the usability to a large extent.

**Comment by aj3423** [comment]
@thomasjimmy Making it the "Default SMS-application" means it must do whatever an SMS app does, such as handling SMS/MMS conversation, group messaging, a fancy UI, etc. That would be making a brand new app, all the efforts, just for deleting messages? Nah..

**Comment by noto10** [comment]
I think implementing the database is a good idea if it does not detract from the primary original configurability of Spamblocker of giving the user maximum control of the number of ways to block spam as his situation demands which may vary according to locale and circumstances.

For example, in some countries/regions, telemarketers are almost unheard of while scam callers are the predominant villains. To my understanding, in such cases, a database will be almost useless since scammers typically use "normal" numbers to make calls and such numbers are too random and dynamic and rarely permanent enough to make it to a database which is more suited to targeting telemarketers.

That is why, to me, a powerful blacklist / whitelist configurable system is the best core of a spam-blocking app.

**Comment by aj3423** [comment]
Just did a quick search, Begone is an app? It's supposed to support any kind of data, can you show me a sample XML from Begone?

**Comment by aj3423** [comment]
The first version is done, for those who want to try the automation and database, here's the action build: https://github.com/aj3423/SpamBlocker/actions/runs/11217112568

**Comment by aj3423** [comment]
There seems to be an issue about reading files that are not created by this app, maybe writing as well. I'll fix this later.

BTW, the `{pattern}` should be a json, for example `{'my_number': 'pattern'}`, which means map column `my_number` to `pattern`. If the column is already named ` pattern`, then there is no need to map, simply use a empty json `{}`.

**Comment by aj3423** [comment]
@Umotas 
Well, I thought it won't require any permission when accessing the Downloads folder, just like the backup export/import. But actually it requires permission, when you use that file dialog to select a file in the Downloads folder, that system file picker will temporarily grant that permission for you. However, when the workflow reads a file, there isn't such user interference, that's why it caused the permission error.

To solve this, now the app will ask for file storage permission when any file action is used.

Updated in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/11247096939

**Comment by aj3423** [comment]
The numbers should have been imported, The UI is not refreshed, try restarting the app.

**Comment by Nosnahc** [comment]
@aj3423
A Begone  xml list : https://github.com/oulixalt/BegoneListeFR/blob/Liste-compl%C3%A8te/Begone-FR.xml

**Comment by aj3423** [comment]
@Nosnahc It's now supported: https://github.com/aj3423/SpamBlocker/actions/runs/11265746145
This xml doesn't seem to be up-to-date, I'm not adding it to the presets. You can import this configuration to test:
![image](https://github.com/user-attachments/assets/e82f945a-9bbf-473f-a379-ebf1da9ef6aa)

```json
{
    "desc": "Begone",
    "schedule": {
        "type": "Daily",
        "time": {
            "hour": 0,
            "min": 0
        }
    },
    "actions": [
        {
            "type": "HttpDownload",
            "url": "https://raw.githubusercontent.com/oulixalt/BegoneListeFR/refs/heads/Liste-compl%C3%A8te/Begone-FR.xml"
        },
        {
            "type": "ParseXML",
            "xpath": "//dict/key[text()='number']/following-sibling::string[1]"
        },
        {
            "type": "ConvertNumber",
            "from": "(\\+)",
            "flags": 5,
            "to": ""
        },
        {
            "type": "ConvertNumber",
            "from": "(#)",
            "flags": 5,
            "to": "."
        },
        {
            "type": "ImportAsRegexRule",
            "description": "BeGone",
            "priority": 0
        }
    ],
    "enabled": false
}
```

**Comment by noto10** [comment]
How does Quick Copy work? I read the pop-up help about matching verification codes or OTP and tried to use regex to match a sample SMS containing a verification code but there's no Copy: 123456 button in the notification.

Sample SMS:

`"Your verification number is 12345678. Please enter this and press the # key."`

Regex tried: 

`(?<=is\s)\d{8}(?=\.)`

**Comment by aj3423** [comment]
I'm closing this since v3 is ready, welcome to test (the latest tag)

@noto10 This issues is only for discussion about v3, I created another issue for the regex problem: https://github.com/aj3423/SpamBlocker/issues/150

**Comment by TyroSpy** [comment]
How can I replace my regex rules with Workflow? I tried "type": "ReplaceAsRegexRule" but it's failure

**Comment by aj3423** [comment]
> How can I replace my regex rules with Workflow? I tried "type": "ReplaceAsRegexRule" but it's failure

Not sure what you mean by "replace regex rule", please fire a new issue, because everyone in this post will get notified, I'm locking this post.
