### ISSUE TITLE
Translation request: Brazilian Portuguese

### ISSUE THREAD

**Issue by EricMGVS** [aj3423/SpamBlocker#141]
Just found out about the app a few days ago and it was literally everything I was looking for in terms of spam blocking both for calls and texts. I'm just opening this issue to request the translation for Brazilian Portuguese which is not present yet. Thanks in advance.

**Comment by aj3423** [comment]
Added in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/11133148503
