### ISSUE TITLE
Timetable for automatic switch on/off filters

### ISSUE THREAD

**Issue by SirTeddyBear** [aj3423/SpamBlocker#143]
I would like certain filters to be turned on or off automatically depending on the time or day of the week.
For example: I would like that on the weekend, only calls from the contacts I have in the address book were allowed, right now I would have to turn filters on or off manually.

Thanks for the app, it's great !!!

**Comment by aj3423** [comment]
The regex rule supports time schedule,  which does exactly what  you need.

**Comment by SirTeddyBear** [comment]
> The regex rule supports time schedule, which does exactly what you need.

I meant in quick settings but will try the regex rule. Thx

**Comment by aj3423** [comment]
It's actually more complex than expected, the idea is: 
- create a contact group named "all contacts" and add all contacts to this group
- create regex rule 1:  `.*`, blacklist, at weekend,  priority 1.  It will block everyone at weekend.
- create regex rule 2:  `all contacts`,  contact group mode, whitelist,  at  weekend,  priority  2.  It has higher priority than rule 1, so  it allows all contacts.

**Comment by aj3423** [comment]
Maybe I should add a new "Contact Mode", so you don't need to create that contact group. 
With this "Contact Mode", the rule 2 would be:
- create regex rule 2: `.*`, contact mode, whitelist, at weekend, priority 2.

I'll add this mode in v3.0.

**Comment by SirTeddyBear** [comment]
> It's actually more complex than expected, the idea is:
> 
>     * create a contact group named "all contacts" and add all contacts to this group
> 
>     * create regex rule 1:  `.*`, blacklist, at weekend,  priority 1.  It will block everyone at weekend.
> 
>     * create regex rule 2:  `all contacts`,  contact group mode, whitelist,  at  weekend,  priority  2.  It has higher priority than rule 1, so  it allows all contacts.

Thanks.

Enable Quick config : AddressBook Inclusive

and then

Create regex rule 1: .*, blacklist, at weekend, priority 1. It will block everyone at weekend except the address book, because it's enabled in quick setting.

Your solution is more powerfull because you can specify groups of contacts,

**Comment by aj3423** [comment]
The quick settings are for most common use cases, such use case is a bit more complex and should not be supported in the quick settings. 
The new "Contact Mode" would make it really easy to achieve this, but for now you can use the "contact group" workaround.

**Comment by SirTeddyBear** [comment]
> The quick settings are for most common use cases, such use case is a bit complex and should not be supported in the quick settings. The new "Contact Mode" would make this really easy, but for now you can use the "contact group" workaround.

Thanks for your help, in the meantime i will use the workaround.

**Comment by aj3423** [comment]
The "Contact Mode" has been implemented in the action build:
https://github.com/aj3423/SpamBlocker/actions/runs/11224638081

**Comment by SirTeddyBear** [comment]
Thank you so much.
