### ISSUE TITLE
Regex issue - searching for string in entire sms not working 

### ISSUE THREAD

**Issue by avongil** [aj3423/SpamBlocker#144]
example:

.*(votantes|poll|survey|tailored).*

this will only work if the line in the SMS starts with poll, or survey etc.  As soon as you put something in front of it, it fails to test.

"survey" works.
"Please take this survey"   does not work.
"poll"  works
"you must take this poll to save us!!"  does not work.

Let me know if am am doing something wrong or if this is a bug.  Thank you!

**Comment by aj3423** [comment]
`.` means any **single** character, `.poll` will only match *apoll* or *bpoll*.
You need to use `.*` instead of `.`, which means "a sequence of characters".
Try: `.*(votantes|poll|survey|tailored).*`

**Comment by avongil** [comment]
Sorry about that, I copied and pasted from my phone to signal then here, those got stripped in the process. Yes that is what is entered.  
![Screenshot_20241006-063051](https://github.com/user-attachments/assets/ac4b53b7-16bd-458e-a4e1-bd82a81c7832)
![Screenshot_20241006-063154](https://github.com/user-attachments/assets/a7590481-5e12-4e80-b515-7b93a0544c42)
![Screenshot_20241006-063215](https://github.com/user-attachments/assets/e638c025-7613-488d-b4fa-f0a6611ff62e)

**Comment by aj3423** [comment]
You typed the regex in the description field, that field is just for showing a brief note about what this regex does, you need to input it in the "SMS Content" field:
![image](https://github.com/user-attachments/assets/9ac836f8-626a-4638-8922-040f2be578de)

**Comment by avongil** [comment]
Darn it.   there are no stupid questions.  Just stupid people and actions.  Thank you. 

I cannot be the only fool, perhaps you can throw in a help button (?) - you can put a few examples for dummies like me.  I think this one that scans for a bunch of words would be the most popular.  

Perhaps even a default one with  Stop2End, reply OUT, STOP, reply END, reply UnSubScriBe  ...
another good default would be the one I used in the example above.

I am struggling with the regex, is it JavaScript notation or it's own thing?  Would like to make sure caps or lowercase works.

**Comment by avongil** [comment]
This might be another silly question, but I don't see a way to delete a single rule other than exporting, editing the file then importing the settings again.

**Comment by aj3423** [comment]
Good idea, there are some typical regex examples in the readme, I'll add them to the help balloon. And the label "Description" will be changed to "Description (optional)".

It's kotlin regex, case insensitive by default. You can also change the regex flags, this regex flag icon is clickable:
![image](https://github.com/user-attachments/assets/e987a142-08e9-4c63-ad4a-97f23223c353)

Swipe left to delete a rule, as mentioned in the balloon tooltip of Number Rules.

**Comment by avongil** [comment]
awesome!  thank you.  Working great now!!!!!
