### ISSUE TITLE
Request - Ability to block Calls and SMSes from Private and Unknown numbers (No CallerID)

### ISSUE THREAD

**Issue by noto10** [aj3423/SpamBlocker#145]
Hi,

Is there a way to block calls and SMS messages from Private or numbers with no CallerID? These are incoming calls or SMSes which show up as from "Private"/"Unknown" (or Unlisted) callers. Typically the telco provides a paid service to allow subscribers to hide their numbers so only "Private" (or equivalent) show up on the recipient's phone.

I find this to be another form of spam because the caller is able to abuse the recipient while hiding behind a veil of pseudo anonymity.

I have not found a way to do it with SpamBlocker. If there is one, please let me know. If there isn't, I would appreciate it if the developer would consider adding this to the feature set.

**Comment by aj3423** [comment]
Maybe they are just empty numbers, try regex like `.{0}` or `^$`, which matches empty string.

**Comment by aj3423** [comment]
In the history log, you can see those numbers, are they displayed as empty strings?

**Comment by noto10** [comment]
They are displayed as follows:

Incoming call:

<img width="151" alt="private1" src="https://github.com/user-attachments/assets/ecea6ed3-ec03-488e-a18a-24fca417108c">



History log:

<img width="270" alt="private2" src="https://github.com/user-attachments/assets/f24cce67-49b2-41f0-96e3-61c9bbcc84bc">





> In the history log, you can see those numbers, are they displayed as empty strings?

**Comment by aj3423** [comment]
I mean what does it look like in the Call tab of SpamBlocker?

**Comment by noto10** [comment]
According to various sites, incoming calls without Caller ID may also display as **"Unknown number"** or **"No Caller ID"** or using similar identifiers. This really depends on the carrier but they are the same for all intents and purposes.

Following are an Australian carrier's instructions for users to block outgoing Caller ID when making calls:

![image](https://github.com/user-attachments/assets/806d25c2-d447-4406-89ab-271ca4b674c6)

**Comment by noto10** [comment]
> I mean what does it look like in the Call tab of SpamBlocker?

It says "Passed by default"

**Comment by aj3423** [comment]
Thanks for your support. 

> It says "Passed by default"

I didn't mean looking for the "block reason", the number in the first row is what really matters, the Private number should look like the first one:

![image](https://github.com/user-attachments/assets/2cdd20c8-72fd-4cd8-8c3c-f50981d6f8d9)

If it's not empty, it should have been displayed here, just like the "111",  this number will be checked by the rules. The call app will display it as "Unknown" or "Private", it doesn't matter.

I guess in your history log, it's also an empty string, that's why the regex `^$` worked.

**Comment by noto10** [comment]
Sorry for the misunderstanding. Here is the relevant part of Spamblocker history log:


![img-2024-10-07-19-00-52](https://github.com/user-attachments/assets/847e7581-da90-4250-824a-53f682920bfc)

You were right. It is an empty string. Does it mean if it were not an empty string, the regex should be written to match that string? I'm trying to understand how to block in other scenarios.

> Thanks for your support.
> 
> > It says "Passed by default"
> 
> I didn't mean looking for the "block reason", the number in the first row is what really matters, the Private number should look like the first one:
> 
> ![image](https://private-user-images.githubusercontent.com/4710875/374136901-2cdd20c8-72fd-4cd8-8c3c-f50981d6f8d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTg4MjgsIm5iZiI6MTcyODI5ODUyOCwicGF0aCI6Ii80NzEwODc1LzM3NDEzNjkwMS0yY2RkMjBjOC03MmZkLTRjZDgtOGMzYy1mNTA5ODFkNmY4ZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDdUMTA1NTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE4YjkyZDkyMjM2MTlhZWM5YmYyM2YxZDBkNzRkYzRhZDZjMzU3NDQ5Yzk1YjIwNDEwMjdjZWVlNTU4YjJjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WHrrpCC0-nlHGDDYNpqnG4TdIB_0pLo99RPsBNGeyd4)
> 
> If it's not empty, it should have been displayed here, just like the "111", this number will be checked by the rules. The call app will display it as "Unknown" or "Private", it doesn't matter.
> 
> I guess in your history log, it's also an empty string, that's why the regex `^$` worked.

**Comment by noto10** [comment]
I would like to make a suggestion about Rule Testing :

While the current system is essential for testing a number against the _entire_ list of rules so as to check if the priorities are correctly applied, can we also have a test for each individual rule when it is being crafted?

Something like the following mockup:

![img-2024-10-07-22-53-08](https://github.com/user-attachments/assets/16795dee-3219-47af-b7ab-31669a9fdaf6)


This would make it easier to check whether each rule works as intended for a particular number before applying the whole-list test.

**Comment by aj3423** [comment]
That looks weird..  it would make the UI more complex.  And it's unnecessary, for checking a particular rule, you can set its priority to 999, and set it back to 10 afterward.

**Comment by noto10** [comment]
> That looks weird.. it would make the UI more complex. And it's unnecessary, for checking a particular rule, you can set its priority to 999, and set it back to 10 afterward.

Good tip about setting it to 999. Agree about complicating the UI though.

**Comment by aj3423** [comment]
Yeah, it supports enterprise numbers, such as "Microsoft".

**Comment by noto10** [comment]
Great. I guess this issue is settled for now. Thanks for the support.
