### ISSUE TITLE
Some sporadic bug with Duplicated Rules.

### ISSUE THREAD

**Issue by Umotas** [aj3423/SpamBlocker#146]
I have two of the same numbers in Rules.
And the app doesn't see them as duplicates.
I exported the backup. And I see two same blocks, but one block has:
"schedule": ",00:00-00:00,false"
The other block doesn't have this string.
Most of them have this string. But not all have this string.
I don't understand why.
Maybe, the best way to ignore this string is by searching for duplicated rules.

**Comment by aj3423** [comment]
it's a bug,will be fixed.

**Comment by aj3423** [comment]
Just checked the code, it's a bit different than I thought. 
When creating a new rule or editing an existing rule, after pressing the "Save" button, the schedule will always become something like ",00:00-00:00,false". 

> The other block doesn't have this string.

How did you create that rule?

**Comment by aj3423** [comment]
Maybe create a PR, I'll merge it. You can also paste the wrong tags here, with the corrected strings, I'll replace them.

**Comment by aj3423** [comment]
XML updated, thanks.
