### ISSUE TITLE
How to disable internet permission

### ISSUE THREAD

**Issue by aj3423** [aj3423/SpamBlocker#147]
The internet permission can be disabled in system settings, the option can be found in different locations.

For some devices:

- Long press the app icon on the screen
- `App info` or the `ⓘ` icon
- `Mobile data & WiFi`
- Disable options like `Enable WiFi connection` and `Enable mobile connection`

For Samsung:
- `System settings`
- `Connections`
- `Data usage`
- `Manage app data`
- Select SpamBlocker
- Change `Network connection method` to `Off`

**Comment by aj3423** [comment]
@nvllz 
https://github.com/user-attachments/assets/ffb855bf-a8ce-4b8a-af06-f18a5751c280

OneUI 6.1
Android 14

If it doesn't exist, maybe try searching for "app data" or "data usage" in the system settings.

**Comment by shilin-da** [comment]
> I only have WiFi/mobile data to choose from

I have the same on OneUI 6.1:
![Screenshot_20241018_123334_Settings](https://github.com/user-attachments/assets/dc488b43-7a7c-44bf-ba23-f04976b9d426) ![Screenshot_20241018_123423_Settings](https://github.com/user-attachments/assets/cca6c021-aa6e-4424-95f5-4665b2b17cbe)

**Comment by aj3423** [comment]
Interesting, same version with different UI.

I'll try to write an action script for building an apk without internet permission, so you can build it yourself with one mouse click.

**Comment by aj3423** [comment]
Or even better, it's now available in the release page, this action build is a bit larger and non-reproducible though.

![image](https://github.com/user-attachments/assets/03959465-1e1e-41cb-b3d1-dacb64942ad6)

**Comment by Bakr-Ali** [comment]
> Interesting, same version with different UI.

May I know which device do you have and which region? I'd love to have the feature to natively disable the internet permissions of any app and I'd seriously consider importing/buying an imported device from a region that has this feature. I'd guess such devices would have some other region restricted features too which would be a plus.

I have an S23+ on the same android version and I don't have the option.

**Comment by aj3423** [comment]
Different regions have different 4g/5g brand support, so can an imported device actually work properly in your region?
Mine is a Galaxy S21, but Samsung doesn't seem to work in your region. 
My Zenfone 9 also supports this, maybe give Zenfone a try.

**Comment by Bakr-Ali** [comment]
> Different regions have different 4g/5g brand support, so can an imported device actually work properly in your region?

We don't have 5g yet and we have a thriving market of imported phones (mostlyfrom Europe) so I think they are compatible.

> My Zenfone 9 also supports this, maybe give Zenfone a try.

Sadly we don't have Zenphones here. I'd have to go with Chinese phones or European Samsung phones (of I confirm they have these features enabled).

Edit: I've just remembered something that I read earlier; EU seems to have passed a law that made Samsung lock the bootloader on the latest phones..

https://www.reddit.com/r/PocoPhones/comments/1mf0mp7/eu_kills_android_bootloader_unlock_starting/

https://www.reddit.com/r/Android/comments/1mabuht/samsung_removes_bootloader_unlocking_with_one_ui_8/

**Comment by aj3423** [comment]
> I'd have to go with Chinese phones 

I don't own one myself, but you can try their ROMs on your S23+(if compatible), they tend to be less restrictive.

If you can afford a new device, what about pixel+GrapheneOS? I don't have a pixel, I can't confirm this, but it seems to have a per app [network-permission-toggle](https://grapheneos.org/features#network-permission-toggle):
> the OS app installation UI has been extended to show the toggle as part of the installation confirmation page so users can disable it when installing an app.
