### ISSUE TITLE
[feature] silence non-contacts calls without asking for contacts permission

### ISSUE THREAD

**Issue by redcat42** [aj3423/SpamBlocker#149]
hey,

just wanted to share, this, open source app, 

[https://github.com/x13a/Silence](https://github.com/x13a/Silence)

uses only the default spam blocker in Android to silence calls not in contacts, it does not ask for contacts permission

just sharing, in case you might find it interesting

(the silence call option in in settings icon within the app, have to find it)

thanks for your work

**Comment by aj3423** [comment]
I need to do some experiments first, I'll feedback later.

**Comment by aj3423** [comment]
Well, as the dev, I didn't even know this :expressionless: : 
 [from the doc](https://developer.android.com/reference/android/telecom/CallScreeningService#onScreenCall(android.telecom.Call.Details))
> only calls which are not in the user's contacts are passed for screening, unless the CallScreeningService has been granted Manifest.permission#READ_CONTACTS permission by the user.

Which means when it's called from non-contact, the app won't get triggered at all, that's how this app "allows" contact calls.

To support this, following things must be taken into consideration:

- More popups and tooltips for the user, more complex to understand.
- Other features like the new regex contact mode.
- Testing calls with contact numbers will no longer work.
- Android 10 doesn't support this,  still have to grant the contact permission.
- History table need to save the contact name and photo.
- Passed calls will not be logged in the history table without the contact permission.

More cons than pros, I decide to not support it, disabling internet permission should suffice.

**Comment by redcat42** [comment]
> Which means when it's called from non-contact, the app won't get triggered at all, that's how this app "allows" contact calls.

wow, no wonder the app below made things look so simple and lightweight 

https://play.google.com/store/apps/details?id=com.lifesoftwarelab.android.incomingcallcontrol

it probably works only for Android 10+


> To support this, following things must be taken into consideration:

    More popups and tooltips for the user, more complex to understand.
    Other features like the new regex contact mode are impacted.
    Testing contact calls will no longer work.
    Android 10 doesn't support this, still have to grant the contact permission.
    History table need to save the contact name and photo.
    Passed calls will not be logged in the history table without the contact permission.

More cons than pros, I decide to not support it, disabling internet permission should suffice.


totally understand, makes no sense, especially since Android changed things after Android 10, to support older devices the app should remain as it is

maybe in the future, when you get time, have a guided install based on Android OS version, logs are not so important for someone like me as the dialer app logs all calls anyway, I'm on Android 14, 
so the guide can ask user what they want and based on that use Android 10+ method without logs or Android older version with logs 
same with SMS, if the user wants sms blocking or not, based on that use or not use that code

don't know if that makes sense or is practical to implement

that's for taking the time to investigate 

appreciate your work

**Comment by aj3423** [comment]
I think there will never be this feature. The logic branching hell is the thing I want to avoid the most, especially the unnecessary ones.
