### ISSUE TITLE
Incoming numbers are not matching their respective contacts 

### ISSUE THREAD

**Issue by GorillaDaddy** [aj3423/SpamBlocker#15]
Contact phone number is, for example, "+51 911478035" (+51 is country code prefix)

But call comes in as just 911478035

The phone app matches this to the contact, but spamblocker doesn't. So call is blocked. (I only want calls from contacts)

**Comment by aj3423** [comment]
Fixed, try the latest action build:
https://github.com/aj3423/SpamBlocker/actions/runs/8868645392
