### ISSUE TITLE
Database: questions or bug?

### ISSUE THREAD

**Issue by Umotas** [aj3423/SpamBlocker#151]
(1) previous version.
I set database in 'Expiry 365'. (I saw my 2200 numbers in Database)
After 24H, I see the database is empty. (I see 0 numbers.)
App cleared database !!!
I will test this with v3 also.

(2) version 3
I set database in 'Expiry 365'
Go to SMS/Call lists. Or restart the App.
I click on 2200, and I see 'Expiry 90'.
The App didn't save 365 days.

**Comment by aj3423** [comment]
Ah, thanks. I'll republish the v3.0 soon.

**Comment by aj3423** [comment]
Fixed and tested, release updated. It helped a lot, thanks!

**Comment by aj3423** [comment]
> But If I go to 'call' or 'SMS' pages, - the app DELETES this imported workflow.

It's imported to the UI, but not saved yet, you need to click the "Save" button.

> Can I import and parse html page?

Not sure, but the xml parser should also work for html, just need to find the correct xpath, you might find this site helpful: http://xpather.com/

If it doesn't work, maybe show me a sample of the html.

**Comment by aj3423** [comment]
It's caused by this line:

>  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

The xml parser is expecting  `crossorigin` to have a value like `crossorigin="..."`,  I'll look into that later.

**Comment by aj3423** [comment]
Imported workflows are disabled by default, it's necessary to be manually enabled by the user, which means he has checked everything and knows what he's doing.

**Comment by aj3423** [comment]
> Could you add workflow: 'Import as multiple rules'.

The "import as multiple rules" was a historical feature, it's for migrating configuration from other app.

ref: https://github.com/aj3423/SpamBlocker/issues/94#issuecomment-2227119802

It is not ideal in most cases, too many rules would be very difficult to maintain,  and if you don't really want to maintain them, I think the spam database would be a better option.

**Comment by aj3423** [comment]
fixed..
https://github.com/aj3423/SpamBlocker/actions/runs/11385578677

**Comment by aj3423** [comment]
The sim info is available for the dialer app but not for the screening app.
