### ISSUE TITLE
Enabled call spam filter

### ISSUE THREAD

**Issue by rieussec** [aj3423/SpamBlocker#152]
Hello, I'm sorry but I can't get call blocking to work. I think it comes from this screen I can only select spam caller when I should be able to select the default Android App. But it doesn't activate and the checker remains off. If anyone can help me, thank you in advance. 
![Screenshot_20241014-085950](https://github.com/user-attachments/assets/4c5db8ff-482a-4b93-9c75-d980b3ab8edf)

**Comment by aj3423** [comment]
This dialog is not about choosing the default phone app, it's about choosing the caller ID app, you should choose SpamBlocker in this popup.

**Comment by rieussec** [comment]
Ok thanks for the quick feedback it means that the problem comes from somewhere else then :-( Attached are the tests I've just done 

![Screenshot_20241014-091604](https://github.com/user-attachments/assets/92107f1c-9ab4-4cfd-b65f-64e931df3dd4)

![Screenshot_20241014-091734](https://github.com/user-attachments/assets/8e481b8c-f8db-4d33-9dcb-3e453d0eb4b5)

**Comment by aj3423** [comment]
I'm a bit confused, the call from +336602... should've been blocked by the rule `336.*`, is it not blocked?

**Comment by rieussec** [comment]
Could it be that I had previously installed nophonespam, which didn't work because it was too old, and that it had modified something on my phone (pixel 4a)? If not, too bad, but thanks for your work.

**Comment by aj3423** [comment]
Not sure about the nophonespam, now it should be working fine, right?

**Comment by rieussec** [comment]
I'd prefer to run your application because it doesn't require authorization..

**Comment by aj3423** [comment]
I'm still a bit confused, is there any problem using this app?
