### ISSUE TITLE
Changing contacts? Need to restart spamblocker 

### ISSUE THREAD

**Issue by GorillaDaddy** [aj3423/SpamBlocker#16]
To workaround that number issue (not matching the country code and number stored in contacts) I added just the number to the contact. It was still blocked. Restarting spamblocker required, I imagine the "whitelist" is built on startup.

**Comment by aj3423** [comment]
Currently the contact list is built on startup, I'll monitor the contact change to rebuild the list.
The number issue will be fixed, as a workaround you can also add a number rule(whitelist with higher priority) instead of adding it to contact.

**Comment by aj3423** [comment]
Fixed, try the latest action build:
https://github.com/aj3423/SpamBlocker/actions/runs/8868645392
