### ISSUE TITLE
The possible Action of Automation Workflow

### ISSUE THREAD

**Issue by TyroSpy** [aj3423/SpamBlocker#160]
I create this task for Automation Workflow and this work, but I need change Action from "ImportAsRegexRule" to "Replace.." how can i do this?
```
{
    "id": 2,
    "desc": "test",
    "schedule": {
        "type": "Daily",
        "time": {
            "hour": 12,
            "min": 42
        },
        "iconId": 2131099698
    },
    "actions": [
        {
            "type": "ReadFile",
            "dir": "{Downloads}/CallBlocker",
            "filename": "test.csv"
        },
        {
            "type": "ParseCSV",
            "columnMapping": "{}"
        },
        {
            "type": "ImportAsRegexRule",
            "description": "test_rules",
            "priority": 3
        }
    ],
    "enabled": true,
    "workUUID": "419c5aae-812b-47f2-a3c5-b62b89982f54"
}
```
Please update the header of https://github.com/aj3423/SpamBlocker/issues/140 to true manual for possible action of Automation Workflow and etc.. so as not to create each time new issues. Thanks

**Comment by aj3423** [comment]
Never mind that post, it's now historical. 

Seems you want to replace the numbers everyday, why do you only want to keep the latest numbers? Why not just add them to the spam database? So you don't need to replace them, and all previous numbers will also work.

The replacement action is not implemented yet, I'll see if it's necessary.

**Comment by aj3423** [comment]
I see, I'll add a couple of options to the action "Import as Regex Rule":

- Type: 
Blacklist / Whitelist

- Mode:
  - Replace: The rule with same "description" will be replaced by the new one.
  - Merge: The new numbers will be merged to the rule that has same description, repeated numbers will be ignored.

**Comment by TyroSpy** [comment]
it's great!

**Comment by aj3423** [comment]
done: https://github.com/aj3423/SpamBlocker/actions/runs/11435739723
