### ISSUE TITLE
History Cleanup clarification

### ISSUE THREAD

**Issue by noto10** [aj3423/SpamBlocker#161]
I have my History Cleanup set to Weekly, Everyday at 03.00 but it seems that I am still seeing SMSes and Calls from a few days ago

![image](https://github.com/user-attachments/assets/669721c0-4a0d-402b-83d4-74bcec843ab7)

There is "Expiry: 30 days" in the Workflow. Does it mean that History Cleanup will occur everyday at 03.00 but will only delete Calls and Messages older than 30 days? If that's the case, if I want all Calls and SMSes purged daily, I would set the Expiry to 1 day?

Just seeking clarification.

**Comment by aj3423** [comment]
> Does it mean that History Cleanup will occur everyday at 03.00 but will only delete Calls and Messages older than 30 days? If that's the case, if I want all Calls and SMSes purged daily, I would set the Expiry to 1 day?

Exactly. 

BTW, you don't need to set a workflow to delete the history, in the history tab, there is an option Expiry as well. They do the exact same thing, it schedules at 00:00 everyday.

**Comment by aj3423** [comment]
Yeah, I'll keep the workflow.

**Comment by aj3423** [comment]
That's unnecessary and it's will cause more confusion, which leads to more explanation. I suppose most people won't even bother using workflow for clearing the history, I put it there because I want to show the potential capability of the workflow, and maybe it would also inspire people to have more ideas, but I'm not expecting this idea:)

**Comment by aj3423** [comment]
Wait, there might be some misunderstanding. 

If you set this -1 to 30:

![png](https://github.com/user-attachments/assets/f5892ab8-810d-4374-8ab7-6d6d07e9e753)


It will work exactly the same as the workflow, expired records will be deleted automatically, why do you need to press the red recycle bin button?

**Comment by aj3423** [comment]
Yeah, that's correct, they work independently.

**Comment by aj3423** [comment]
Ah thanks, this is a bug, I'll fix it later.

**Comment by aj3423** [comment]
Fixed. https://github.com/aj3423/SpamBlocker/actions/runs/11515226805
