### ISSUE TITLE
STIR\SHAKEN with Whitelist

### ISSUE THREAD

**Issue by nazgulsenpai** [aj3423/SpamBlocker#163]
I hate to open an issue with this but I could not get the Matrix channel (I "was not invited").

Is it possible to have the Whitelist override the STIR in Exclusive mode with Include Unverified enabled?

Here's the idea: I have a whitelist regex for local area codes in phone numbers that I have tested as working. I would like to block all calls that fail STIR or are unverified, unless they are in the regex whitelist. Right now even with both the STIR/SHAKEN exclusion and Whitelist enabled, if STIR fails the call is blocked ignoring the whitelist. 

Doing an exclusive regex blocks all non-whitelisted calls regardless of the STIR verdict.

Thank you for this application. I've recently begun receiving an onslaught of unsolicited spam calls and even without the rule above this app has helped me manage them on a device without Google Play Services.

**Comment by aj3423** [comment]
The priority of STIR Exclusive is 0.
New regex rule has priority 1 by default, so it is supposed to be checked first, have you changed this priority?

**Comment by nazgulsenpai** [comment]
Oh no I haven't. I figured I was overlooking something simple. Setting whitelist to 0 priority works as expected thank you!

**Comment by nazgulsenpai** [comment]
It does seem like either contacts or dialed were what was allowing the calls through. I turned off everything but the STIR Exclusive and whitelist with priority 0 or 1 and STIR unverified still blocks on each attempt. Apologies, I seem to have confused myself.

So is there a way to achieve the desired result? I appreciate your patience and quick responses.

**Comment by aj3423** [comment]
I guess the regex doesn't match the number, try to set the regex priority to 100 and test with that number again, if it's still not allowed by this rule, then the regex must be incorrect, please show me the regex and the number.
