### ISSUE TITLE
How does the "Priority" work

### ISSUE THREAD

**Issue by aj3423** [aj3423/SpamBlocker#166]
Each filter has its priority value, as the term implies, it dictates the order in which the call is checked.

By default, 
- Whitelist rules have priority 10. 
  E.g.: Contacts/STIR (Inclusive), RepeatedCall, Dialed, RecentApps, OffTime
- Blacklist rules have priority 0.
  E.g.: Contacts/STIR (Exclusive), Database

So, when they are both enabled, the whitelist rules will override the blacklist rules because 10 > 0.

For the regex rules, the priroty can be any number between -2147483648 and 2147483647, different rules can have the same priority as long as they are the same type. However, **never assign the same priority to both whitelist and blacklist rules**, it can cause random behavior.

Some use cases of custimizing the priority:

- If you want to always block a particular number regardless of how many times it repeats, or within OffTime, etc, set a rule with priority > 10.  

- If you want to test a particular regex, just set its priority to 999, so it will override all other rules and you don't have to temporarily disalbe them one by one.

**Comment by MiguVT** [comment]
@aj3423 Maybe this issue should be pinned

**Comment by aj3423** [comment]
@MiguVT It's in the [FAQ](https://github.com/aj3423/SpamBlocker#faq) :)

**Comment by aj3423** [comment]
My plan was to put it directly into the app, but I haven’t figured out the how yet. It'll be added once I find the right place for it.
