### ISSUE TITLE
Dual SIM support

### ISSUE THREAD

**Issue by aj3423** [aj3423/SpamBlocker#169]
Currently, it does support blocking calls on all SIM cards, it's just unable to differentiate between them. If you want to treat them differently, it's not possible yet.

Some other apps support this because they are either:
- The default phone app
  This app isn't a phone app.
- They use the CallStateReceiver
  That would break some features, the lockscreen will be turned on, preventing silent call rejection or silencing(ringing at background). And this approach would significantly increase complexity (code, UI, user experience)

And it doesn't seem to be that useful, if your rules work well for SIM 1, it should work well for SIM 2 as well, unless you want to hide all notifications for SIM 2.

Therefore, I prefer not support it for now.

I've submited a feature request to google ([link](https://issuetracker.google.com/issues/348442539)), maybe give a "+1" to it. Once supported, there will be a SIM option in the regex rule.

**Comment by micheleperani76** [comment]
Hi everyone,

First of all, congratulations on the project! I'm really enjoying it and I think you’ve done a wonderful job.

I’d like to share an idea for implementing dual SIM support. I should note that I’m not a programmer, but a computer enthusiast with limited skills.

For my work, I use a dual SIM phone with a personal SIM and a work SIM. I would like to use your application to filter and manage calls from my personal SIM while leaving my work SIM traffic free. Often, I receive calls from numbers not saved in my contacts on the work SIM, and I need the phone traffic to be free during the day. In the evening, I turn off the work SIM to avoid being disturbed.

I was wondering if it would be possible to add a filter at the program level that intercepts only the phone and SMS traffic of one SIM and redirects all this traffic to the application, leaving the other SIM free. This might not impact the overall project too much and would allow us to use the program more accurately according to our needs.

For example, in the settings screen, it could be possible to add three options to select the desired behavior:

SIM1+2: The program filters all traffic from both SIMs.

SIM1: The program focuses only on SIM1, leaving SIM2 traffic free.

SIM2: The program focuses only on SIM2, leaving SIM1 traffic free.

I believe this solution, although basic, would make a difference for those, like me, who are looking for a flexible solution for their needs.

Additionally, I tried to modify the code with my limited computer knowledge, with the help of an artificial intelligence. I will attach the modified file as an example.

package spam.blocker.ui.setting

@Composable
fun SimFilterSetting() {
    val ctx = LocalContext.current
    val spf = spf.Global(ctx)

    val selectedSim = rememberSaveable { mutableStateOf(spf.getSelectedSimFilter()) }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 8.dp),
        verticalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        Text(
            text = "Selection SIM",
            fontSize = 18.sp,
            fontWeight = FontWeight.Bold,
            color = SkyBlue,
            modifier = Modifier.padding(horizontal = 16.dp)
        )

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceEvenly
        ) {
            SimFilterButton(
                label = "SIM1+2",
                isActive = selectedSim.value == "SIM1+2",
                onClick = {
                    selectedSim.value = "SIM1+2"
                    spf.setSelectedSimFilter("SIM1+2")
                }
            )

            SimFilterButton(
                label = "SIM1",
                isActive = selectedSim.value == "SIM1",
                onClick = {
                    selectedSim.value = "SIM1"
                    spf.setSelectedSimFilter("SIM1")
                }
            )

            SimFilterButton(
                label = "SIM2",
                isActive = selectedSim.value == "SIM2",
                onClick = {
                    selectedSim.value = "SIM2"
                    spf.setSelectedSimFilter("SIM2")
                }
            )
        }
    }
}

@Composable
fun SimFilterButton(label: String, isActive: Boolean, onClick: () -> Unit) {
    StrokeButton(
        label = label,
        color = if (isActive) SkyBlue else White,
        borderColor = if (isActive) SkyBlue else Color.Gray,
        onClick = onClick
    )
}


Thanks for your attention and keep up the good work!

**Comment by micheleperani76** [comment]
Hi everyone,

First of all, congratulations on the project! I'm really enjoying it and I think you’ve done a wonderful job.

I’d like to share an idea for implementing dual SIM support. I should note that I’m not a programmer, but a computer enthusiast with limited skills.

For my work, I use a dual SIM phone with a personal SIM and a work SIM. I would like to use your application to filter and manage calls from my personal SIM while leaving my work SIM traffic free. Often, I receive calls from numbers not saved in my contacts on the work SIM, and I need the phone traffic to be free during the day. In the evening, I turn off the work SIM to avoid being disturbed.

I was wondering if it would be possible to add a filter at the program level that intercepts only the phone and SMS traffic of one SIM and redirects all this traffic to the application, leaving the other SIM free. This might not impact the overall project too much and would allow us to use the program more accurately according to our needs.

For example, in the settings screen, it could be possible to add three options to select the desired behavior:

SIM1+2: The program filters all traffic from both SIMs.

SIM1: The program focuses only on SIM1, leaving SIM2 traffic free.

SIM2: The program focuses only on SIM2, leaving SIM1 traffic free.

I believe this solution, although basic, would make a difference for those, like me, who are looking for a flexible solution for their needs.

Additionally, I tried to modify the code with my limited computer knowledge, with the help of an artificial intelligence. I will attach the modified file as an example.

package spam.blocker.ui.setting

import androidx.compose.foundation.layout.Arrangement
import xxxxxx

@Composable
fun SimFilterSetting() {
    val ctx = LocalContext.current
    val spf = spf.Global(ctx)

    val selectedSim = rememberSaveable { mutableStateOf(spf.getSelectedSimFilter()) }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 8.dp),
        verticalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        Text(
            text = "Select SIM",
            fontSize = 18.sp,
            fontWeight = FontWeight.Bold,
            color = SkyBlue,
            modifier = Modifier.padding(horizontal = 16.dp)
        )

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceEvenly
        ) {
            SimFilterButton(
                label = "SIM1+2",
                isActive = selectedSim.value == "SIM1+2",
                onClick = {
                    selectedSim.value = "SIM1+2"
                    spf.setSelectedSimFilter("SIM1+2")
                }
            )

            SimFilterButton(
                label = "SIM1",
                isActive = selectedSim.value == "SIM1",
                onClick = {
                    selectedSim.value = "SIM1"
                    spf.setSelectedSimFilter("SIM1")
                }
            )

            SimFilterButton(
                label = "SIM2",
                isActive = selectedSim.value == "SIM2",
                onClick = {
                    selectedSim.value = "SIM2"
                    spf.setSelectedSimFilter("SIM2")
                }
            )
        }
    }
}

@Composable
fun SimFilterButton(label: String, isActive: Boolean, onClick: () -> Unit) {
    StrokeButton(
        label = label,
        color = if (isActive) SkyBlue else White,
        borderColor = if (isActive) SkyBlue else Color.Gray,
        onClick = onClick
    )
}


Thanks for your attention and keep up the good work!

**Comment by aj3423** [comment]
Thanks for the feedback, but you've missed the point. 
The problem is that, **when there is an incoming call, the app doesn't know which SIM is called on**, because Android doesn't provide the SIM slot information to the Caller ID app. This is what [this feature request](https://issuetracker.google.com/issues/348442539) is about, it should have been implemented since Android 10, when the call screening was introduced.

**Comment by aj3423** [comment]
Well, google closed this as "Status: Won't Fix (Obsolete)":
https://issuetracker.google.com/issues/348442539?pli=1

**Comment by nikicat** [comment]
@aj3423 Hello, do you have any ideas what do they mean by this? Is there another API that replaces proposed functionality?

**Comment by aj3423** [comment]
@nikicat 
I don't know, but obviously they think it's unnecessary. The `onScreenCall()` is the only API for screening calls, no other workaround.
For anyone who still want this feature, consider reply to that issue https://issuetracker.google.com/issues/348442539?pli=1,  explain more about the usefulness (make sure to @ that google guy),  maybe they'll reopen this.

**Comment by mvbentes** [comment]
I replied on the issue at https://issuetracker.google.com/issues/348442539?pli=1, but it seems impossible to @ anybody on there. I really wish this feature was available. A lot of people could benefit from using different rules for work sims.

**Comment by aj3423** [comment]
> it seems impossible to @ anybody on there

I see. Not sure if reopening issues is part of their responsibilities, as the previous reply was completely ignored, perhaps we should create new issues.

**Comment by slimshady045** [comment]
any other suggested app for the job?

**Comment by aj3423** [comment]
Well, just learned that it's actually possible to get the ringing sim slot, no wonder google marked it as "Obsolete".

So multi SIM is now supported, check this action build, let me know if there are any issues.

https://github.com/aj3423/SpamBlocker/actions/runs/20001261024


<img width="392" height="124" alt="Image" src="https://github.com/user-attachments/assets/e9a2dac1-9b7c-4fa9-ae36-eb632c4f5016" />
 <br>
<img width="264" height="360" alt="Image" src="https://github.com/user-attachments/assets/25fa09d1-89ad-491a-b437-f404b3755d3f" />
 <br>
<img width="357" height="127" alt="Image" src="https://github.com/user-attachments/assets/b6066739-2e50-4f4e-96a4-2b4f6e0d80f1" />

**Comment by dece** [comment]
Exactly what I needed, thanks. I installed the artifact and will report issues found this week if any.
