### ISSUE TITLE
[Feature reqeust] Prompt to copy SMS verification code

### ISSUE THREAD

**Issue by wdlid** [aj3423/SpamBlocker#17]
Thanks for the great APP first.
I'm using Samsung phone and the default SMS could prompt to copy verification code, it's really convenience.
Since I disabled the default notification of default SMS, it will not prompt for copy 'verification code' like this:

https://www.theverge.com/2018/5/11/17345016/android-messages-copy-two-factor-codes-update

It's much better if you can consider muti language.
In Chinese the code could comes with 
验证码：4321
验证码为4321
验证码4321
验证码是4321

so a regex could be like 
(?<=验证码.*)\d+

In english it could be:
(?<=code.*)d+

**Comment by aj3423** [comment]
Good idea, will implement.

**Comment by aj3423** [comment]
Done in the latest tag: https://github.com/aj3423/SpamBlocker/releases
Btw, no need to uninstall/reinstall, just upgrade.

A problem is, the lookaround syntax doesn't seem work, it throws exception even with `Regex("(?<=code.*)d+")`. I posted this on stackoverflow: 
https://stackoverflow.com/questions/78433071/kotlin-regex-works-on-playground-and-even-in-scratch-but-not-in-android-project?noredirect=1#comment138275484_78433071 

To workaround it you can use capturing group like: `code.*?(\d+)`

I'll leave this issue open until I find a solution to the lookarounds.
