### ISSUE TITLE
I need a feature for block every call that Come to my phone 

### ISSUE THREAD

**Issue by AMMARLAFIR** [aj3423/SpamBlocker#170]
I am from Sri Lanka. I'm here to thank you first for the most useful open-source app I've ever use; in our country, most of us don't use Wi-Fi connections. So, in the middle of the Zoom meeting. I receive some calls, and then my internet connection (normal mobile data connection) disconnects with that call. So, I need some features to automatically cancel all calls. Now I use some third-party Call blockers, but I don't like that. I love the spam blocker app and its other features, so I have a kind request: please give me a feature for blocking all calls.

**Comment by aj3423** [comment]
I'll add something like "Meeting Mode" in the quick settings, just like the RecentApps, you can select apps, when a selected app is running in the foreground, all calls will be blocked. 

Currently you can manually block all calls with a regex rule: `.*` / blacklist / priority 100.

**Comment by aj3423** [comment]
done. https://github.com/aj3423/SpamBlocker/actions/runs/11567939703

**Comment by AMMARLAFIR** [comment]
Thank you for implementing the meeting mode upon my request.
I appreciate your help and work really thank you
