### ISSUE TITLE
Minor GUI features

### ISSUE THREAD

**Issue by Umotas** [aj3423/SpamBlocker#173]
The text size is "Large". I think the best way is to make height in three lines. But that is only my opinion.
Why do you use the round icon for every log record? It takes a place in every record.
<img width="270" alt="Screenshot_2024-10-30-10-13-45-366_spam blocker" src="https://github.com/user-attachments/assets/53a66112-a33c-4e3a-bf31-e14a3a8ea5c7">

Is the way to remove some number from the database? Now I have one way - to add this number to rules - whitelist.

**Comment by aj3423** [comment]
The time string is supposed to expand vertically, looks like the height is hardcoded, I'll fix that later.

The round icon is a placeholder, it shows the same color for identical  numbers. When it's a contact, it will show the contact photo instead.

**Comment by aj3423** [comment]
Fixed. https://github.com/aj3423/SpamBlocker/actions/runs/11588032536

> Is the way to remove some number from the database? 

How many numbers do you want to remove? Do you need to do that frequently? And why is that necessary?

**Comment by aj3423** [comment]
Well, it's been 25 minutes and the action is still "queued", maybe github action is currently busy, I'll try again later.

**Comment by aj3423** [comment]
I'll add a searchbox in the popup dialog, matched number will be displayed below, swipe to delete a number.

**Comment by aj3423** [comment]
done. https://github.com/aj3423/SpamBlocker/actions/runs/11595592583

**Comment by aj3423** [comment]
fixed. https://github.com/aj3423/SpamBlocker/actions/runs/11598046916
