### ISSUE TITLE
Log SMS in database but NOT display content in activity log + UI suggestion

### ISSUE THREAD

**Issue by noto10** [aj3423/SpamBlocker#176]
I refer to the Log SMS Content option:

<img width="223" alt="spamblocker UI 001" src="https://github.com/user-attachments/assets/0da0df95-e525-4a40-b284-4ff66978f7f6">

Is it possible to add an option to Log SMS Content to database but _NOT_ display it in the activity log? At present, the UI allows the user to tap to view the contents in Spamblocker if logging is enabled OR tap/swipe right to open in the native SMS app if logging is disabled. It would be good if more granular control is available by making logging to database independent of content viewing.

Perhaps to simplify matters,

1. Tap to expand/collapse content to view.
2. Swipe to open in SMS app (currently in place).
3. Separate Option to Enable/Disable Logging to Database.

I find having the content displayed (even in part) can clutter up the display and increase the level of visual distraction as seen below. This is especially so if there are emojis in the content. Comparing the messages with no content displayed ① and those with content ② should illustrate my point. Having the content displayed in the same area as the number and description (2nd line?) also makes it harder for the eye to "see" the description as it tends to get lost and overwhelmed due to the color of the 1st line and the possible colors in the 3rd line (content). I think by making viewing the content intentional (maybe also optional?) via tapping and separating it from logging will be better.

<img width="216" alt="spamblocker UI 002" src="https://github.com/user-attachments/assets/edc99ea8-486b-4d37-93bf-a45d19ae5003">

Just my opinion and for your consideration.

**Comment by aj3423** [comment]
I think a better solution would be to add an option for customizing the number of displayed rows when collapsed.

The default value would be 1, same behavior as now. 
You can change it to 0 to completely hide it.
Some might want to set it to 2+.

**Comment by aj3423** [comment]
Yeah, logging or not remains unchanged, when logging is enabled, there will be a new integer option "default rows".

**Comment by aj3423** [comment]
done. https://github.com/aj3423/SpamBlocker/actions/runs/11625659999

**Comment by aj3423** [comment]
I don't understand, what's the expected result?

> File isn't imported correctly "as a single rule"

**Comment by aj3423** [comment]
It works fine, what's the problem?

![Screenshot_20241103-145455_SpamBlocker.png](https://github.com/user-attachments/assets/8ce64592-3e76-48b8-9faa-dcbc4a3837ab)

**Comment by aj3423** [comment]
That's expected, for a single rule, it can only be either blacklist or whitelist, can't have both.

**Comment by aj3423** [comment]
Makes sense, I'll change it to generate two rules if there are different types.

**Comment by aj3423** [comment]
> what do you think about to have two chapters of rules. First chapter is a whitelist's rules. Second chapter is a blacklist

It's useful to group them together, they are sorted by priority, which gives you a clear visual representation of which takes precedence in case of a conflict.

> Could you make feature to change quantity displaying rows for rules in Rule-list.

How many rules do you have? What's the current problem with it?

**Comment by aj3423** [comment]
done. https://github.com/aj3423/SpamBlocker/actions/runs/11649954291

**Comment by aj3423** [comment]
> Buit-in Android Contacts has no access to my real Contact-database. Only SpamBlocker will have this base of my contacts.

That's unexpected... You store contact numbers in SB rather than the Contacts app, now I see why you have lots of rules, the description is used for their names.

I'll add some UI options:
- maxLines of the description text
- maxLines of the regex text
- max height of the rule list

**Comment by aj3423** [comment]
When the logging is disabled, there is nothing to expand, what's the point to customize the number of rows?

**Comment by aj3423** [comment]
> when logging is off, all Spamblocker has is the originating number after processing with regex.

Yeah, that's right.

**Comment by aj3423** [comment]
Yeah, like this:
![image](https://github.com/user-attachments/assets/4af37ff2-cf8e-4af8-9910-9ec9158482c2)

**Comment by aj3423** [comment]
Some languages have very long text, and this color Light Magenta is used to indicate the priority throughout the app, along with the icon, this combination is easy to understand, I suppose.

**Comment by aj3423** [comment]
done. https://github.com/aj3423/SpamBlocker/actions/runs/11649954291

**Comment by aj3423** [comment]
Ah, wrong action link... This is the correct link: https://github.com/aj3423/SpamBlocker/actions/runs/11663611939

**Comment by aj3423** [comment]
> I am not sure, in rule I set 'Raw Number'. App doesn't save +111111 number, writes 'invalid regex'

The + symbol has special meaning, should be escaped like `\+111111` when being used as a literal string.

**Comment by aj3423** [comment]
I see,  the red error is updated on input change, so it doesn't disappear when you turn on the RawMode, just type something and it will disappear, I'll fix it later.
