### ISSUE TITLE
404 error when testing FTC workflow

### ISSUE THREAD

**Issue by kevinbbbb** [aj3423/SpamBlocker#178]
Hey, I just discovered this app and tried to download the FTC database files via the suggested workflow. When clicking on "test", I am getting the error "Failed: HTTP: 404".
Am I doing anything wrong? My Internet connection should not be the issue; I tried WiFi and mobile network and also tried deactivating my DNS/Firewall (RethinkDNS) - did not make a difference.

![1](https://github.com/user-attachments/assets/e39de830-2a91-455c-901c-8fecaa875e20) 
![2](https://github.com/user-attachments/assets/a45e47cc-7cb4-48d4-83e5-4768f038abda)

**Comment by aj3423** [comment]
The DNC registry is for US only, it doesn't work for any other countries.

Technically, the 404 means file not found, the url is:
`https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_{year}-{month}-{day}.csv`
It will be parsed to:
https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_2024-11-04.csv
And there isn't such file on their [daily files page](https://www.ftc.gov/policy-notices/open-government/data-sets/do-not-call-data)

**Comment by kevinbbbb** [comment]
Oh okay, that's unfortunate. I also read in a different issue that there is not really a European or German equivalent.
I opted for just [blacklisting all foreign numbers](https://github.com/aj3423/SpamBlocker/issues/90#issuecomment-2198000904), which should fix my problem with spam calls.
Thanks for getting back to me :)

**Comment by mirchie** [comment]
hello,
I don't frequently post on GitHub. I am not sure if I can, or how to, reopen an issue. or maybe I have to ask? (then this is the ask 🙂). I am getting the same 404 error.
if I am reading the above exchange correctly,
https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_{year}-{month}-{day}.csv
pulls today's date, and this fails if the latest available file is yesterday's.
I can confirm something along this by typing in yesterday and not using the {...}.
for me, anyways, any recent date is fine. is there a way to alter
https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_{year}-{month}-{day}.csv
so that it pulls yesterday or some other recent date?
thanks!

**Comment by aj3423** [comment]
@mirchie Always feel free to open a new issue or discussion. 

On [this page](https://www.ftc.gov/policy-notices/open-government/data-sets/do-not-call-data)

> This data set is typically updated each weekday by about noon Eastern time. 

Since you mentioned:
> the latest available file is yesterday's

I guess you don't live in US. The thing is, the FTC-DNC is US exclusive, it won't work for any other countries.

**Comment by mirchie** [comment]
@aj3243 ugh. sometimes I am an idiot!
I live in the USA. my problem was that it was after midnight when I replied, and I failed to take that into account. hence, today was the new day and yesterday was the latest csv that was available. 
I was tired when I wrote it, but still... embarrassing...

**Comment by SevenFactors** [comment]
Hello. I am in the US. 
A day ago I installed this app from f-droid, set it up and I think it would be nice to have a local database setup. I tried to download the FTC NDC list but I get 404 error. I am in the US. I tried The day before around 20:00 hours and today around 12:00 hours.  Still I am experiencing the 404 issue.

If I try to visit any part of the URL via web browser, I get page not found pages. No idea what is going on unless FTC is having issues at their end. Any ideas?

**Comment by aj3423** [comment]
@SevenFactors
They don't update on weekends. 
From https://www.ftc.gov/policy-notices/open-government/data-sets/do-not-call-data

> This data set is typically updated each weekday by about noon Eastern time. Weekend data is included in Monday’s file and holiday data is included in the file posted the next business day.

**Comment by SevenFactors** [comment]
> @SevenFactors They don't update on weekends. From https://www.ftc.gov/policy-notices/open-government/data-sets/do-not-call-data
> 
> > This data set is typically updated each weekday by about noon Eastern time. Weekend data is included in Monday’s file and holiday data is included in the file posted the next business day.

Thank you for you reply.
