### ISSUE TITLE
Can't block in messages app

### ISSUE THREAD

**Issue by mojienjoyment** [aj3423/SpamBlocker#18]
I set rules for blocker and when I recieve sms, in spam blocker it shows me "blocked" but in messages app, I see it! And it had notification. one for spam blocker and one for messages.

It seems the app doesn't block sms really in messages app. I don't know. Is it maybe from priorty?
I already set app my default caller id & spam app.
I also changed my messages app from aosp messages to fossly messanger, but same happed.

Device : poco x3pro
Android 14 crdroid 10.4.

Screenshots:
![ResizedImage_2024-05-01_10-29-37_1232](https://github.com/aj3423/SpamBlocker/assets/68327458/6ef9586a-2227-4c0d-9182-ccd5dca6c0bf)

![ResizedImage_2024-05-01_10-30-33_2582](https://github.com/aj3423/SpamBlocker/assets/68327458/f3606d5e-c238-4f54-a9a8-a5991d013bab)

**Comment by aj3423** [comment]
For SMS messages, you need to disable the notification of default SMS app in system settings, let this app take over the notification. This app doesn't "block" text messages, it "blocks" notifications.
