### ISSUE TITLE
prevent MMS message spam regex filtering bypass

### ISSUE THREAD

**Issue by GonzRon** [aj3423/SpamBlocker#180]
Spam can arrive in the form of political ads in images.
intercept MMS messages with no text (only picture) from unknown numbers.

This is a feature request that would intercept MMS messages that contain only pictures from unknown numbers.  I define unknown numbers as either numbers detected as spam numbers from various databases, or from numbers not in your contacts list.

This will prevent bypass of regex filtering of spam text messages by senders simply putting ad text into an image and sending the image as spam.

**Comment by aj3423** [comment]
What about blocking empty messages? `^$`
