### ISSUE TITLE
Workflows: HTTP Download throws "java.net.unknownHostException: Unable to resolve host"

### ISSUE THREAD

**Issue by stefanheinen** [aj3423/SpamBlocker#181]
Hey,

when I try to test to download a file with the HTTP Download action, it always throws "java.net.unknownHostException: Unable to resolve host", no matter what domain I specify.

![Screenshot_20241105-175235_SpamBlocker](https://github.com/user-attachments/assets/1dea81d1-c712-4d3c-a331-360817c553f0)

**Comment by aj3423** [comment]
That's local dns issue, not sure why, I can't reproduce this, it shows 301 which means connected fine.

**Comment by stefanheinen** [comment]
Uninstall & Reinstall solved the problem, now working fine.
