### ISSUE TITLE
Minor UI bug

### ISSUE THREAD

**Issue by Ilithy** [aj3423/SpamBlocker#182]
Hi;
First of all, thank you very much for this excellent application, which is very practical.

There seems to be a small problem displaying the help bubble, when you click on the "Number Rules" help in the "Regex Settings" tab the bubble is truncated, here's a small video showing the problem:

https://drive.proton.me/urls/YBGHV6VM20#MUAg86c_NfL4

Sorry for this unrelated question, but how can I have a single list of all the phone numbers I want to block? (in Regex Settings).

For exemple, to have a list including:

> ^$
> 0123.*
> 0456.*
> 0789.*

_Because I can't figure out how to do it,_
thank you very much and my apologies for the disruption.

**Comment by aj3423** [comment]
Ah, thanks. I can reproduce this UI issue on Android 15 emulator, it seems to be Android 15 specific, I'll fix it later, here's the rest of the tooltip:
![image](https://github.com/user-attachments/assets/67ece062-7762-4b56-b608-e02f1f74dde9)

To combine multiple patterns into a single regex, you can use the alternation operator `(a|b|c|....)`, it will match any of the a,b,c,etc.

`(^$|0123.*|0456.*|0789.*)`. 

As mentioned by @Umotas, you need the "Raw Number" for the domestic leading 0. It's in the flag icon:
![image](https://github.com/user-attachments/assets/2097adb5-ea06-442d-85b2-a434ff2d0a5b)


And there is a bug that the "Save" button remains disabled when the regex text is actually valid, a quick workaround is manually input the text instead of copy/paste. It has been fixed in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/11736510661

**Comment by Ilithy** [comment]
> Ah, thanks. I can reproduce this UI issue on Android 15 emulator, it seems to be Android 15 specific, I'll fix it later, here's the rest of the tooltip: ![image](https://private-user-images.githubusercontent.com/4710875/384231082-67ece062-7762-4b56-b608-e02f1f74dde9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTEzNzYsIm5iZiI6MTczMTA1MTA3NiwicGF0aCI6Ii80NzEwODc1LzM4NDIzMTA4Mi02N2VjZTA2Mi03NzYyLTRiNTYtYjYwOC1lMDJmMWY3NGRkZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDczMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDBmNjYxM2VkYWEyMTFjNTdiMmYyYzZmMDNiYjg5MWU1NWU1ZDYwNDgzYWZlNTkyMGY3ZDhmZmJlZGRhYjEwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GuX61MO_sUUxYE9nOln6mJWE28P8LFJALyjLAoENg2s)

Indeed, my device is running Android 15, more precisely GrapheneOS Build 2024110400 (a secure aosp-based ROM for Google Pixels); my apologies, I should have mentioned it.
It's not a major bug, thanks for taking it into account.

> To combine multiple patterns into a single regex, you can use the alternation operator `(a|b|c|....)`, it will match any of the a,b,c,etc.
> 
> `(^$|0123.*|0456.*|0789.*)`.

<3 
Thank you very, very much for this help, in fact I was able to add all the advertising callsigns in a single rule, it's much easier to read this way, thank you again. _(Would 
 it be possible to add to the existing help a sample list, as you have clearly presented to me?)_

> As mentioned by @Umotas, you need the "Raw Number" for the domestic leading 0. It's in the flag icon: ![image](https://private-user-images.githubusercontent.com/4710875/384238892-2097adb5-ea06-442d-85b2-a434ff2d0a5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTEzNzYsIm5iZiI6MTczMTA1MTA3NiwicGF0aCI6Ii80NzEwODc1LzM4NDIzODg5Mi0yMDk3YWRiNS1lYTA2LTQ0MmQtODViMi1hNDM0ZmYyZDBhNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDczMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjlmYzBjMjcyY2QwNjcxMWJkNTBiY2NhMTkxMTRkYjFkODgzNTRlODAxZGI5ZjNkMTg4MDZiMGYzMTI4NDFjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.J0FILP3VKSOAxGgd8XI1h-ngJMJBVm1A3JTdixonwEY)

Yes, I understand, thank you both for that clarification, it helped me.

> And there is a bug that the "Save" button remains disabled when the regex text is actually valid, a quick workaround is manually input the text instead of copy/paste. It has been fixed in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/11736510661

Thanks for the warning
