### ISSUE TITLE
Backup/restore settings

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#19]
If I uninstall the F-droid version to install the one from releases, I lose all my rules. Backup settings and rules would be cool.

**Comment by aj3423** [comment]
I'll add the backup/restore feature.
Btw, you can install the github release without uninstalling it first, all the configuration will retain. Only downgrading requires uninstalling first, which will erase all the data.

**Comment by bb1a2** [comment]
Aren't the signing key different, or are you making reproducible builds?

**Comment by aj3423** [comment]
Yeah, it's reproducible, all the releases are signed with the same signing key, even for those action releases.

**Comment by bb1a2** [comment]
Great!

**Comment by aj3423** [comment]
Done in the tag latest. https://github.com/aj3423/SpamBlocker/releases/tag/latest
