### ISSUE TITLE
Temporarily disable and enable a rule by swiping right

### ISSUE THREAD

**Issue by CyanDragonS** [aj3423/SpamBlocker#190]
### The feature

Sometimes I need to temporarily disable one or more rules. In this case, it is difficult to uncheck the check box of a rule one by one.
Thanks

**Comment by aj3423** [comment]
I think it can be solved by adding two new workflow actions:
- Find Rules
Match multiple rules by description.
- Modify Rules
Modify one or mutiple attributes of the rules

**Comment by aj3423** [comment]
done: https://github.com/aj3423/SpamBlocker/actions/runs/11819865530
workflow template:
```json
{
    "id": 8,
    "desc": "Test",
    "schedule": {
        "type": "Daily",
        "time": {
            "hour": 0,
            "min": 0
        }
    },
    "actions": [
        {
            "type": "FindRules",
            "pattern": "test.*",
            "flags": 5
        },
        {
            "type": "ModifyRules",
            "config": "{\n\"flags\": 0,\n\"bbb\":133,\npriority: 134\n}"
        }
    ],
    "enabled": false,
    "workUUID": "ecb0b32a-7752-45a9-a250-de1b16b7d97d"
}
```

**Comment by aj3423** [comment]
> `What is 'bbb' ? I see flag and "flag" working well.`

Ah I forgot to delete it, never mind it, just to demonstrate that you can modify multiple attributes, not just the "flag".

**Comment by aj3423** [comment]
It's the Test button, maybe show me the configuration if it's not working, I can't reproduce this.

**Comment by aj3423** [comment]
From the image, the expiry is set to 90 days, which means it's will only delete history records that are older than 90 days. Your test record is new, it won't be deleted.

To test this, you can modify the expiry to 1 or 0.

And there is a bug, when the history records are deleted by the workflow, the UI is not refreshed, you can restart the app to see if it works, I'll fix this later.
