### ISSUE TITLE
Temporarily disable  by global switch

### ISSUE THREAD

**Issue by ghlpo** [aj3423/SpamBlocker#191]
### The feature

Sometimes I need to disable app for some hours using global switch. It would be nice a feature allowing setting the amount of time the app will be disable. Often I forget to enable app again.
Thanks in advance

**Comment by aj3423** [comment]
I'll add a new schedule type "one-off" and a new action "global switch".

**Comment by ghlpo** [comment]
Awesome , thanks !

**Comment by aj3423** [comment]
> EnableWorkflow - false
> What is it in this case? Will  the workflow be executed one time and turn off itself?

Yeah, that's right.
