### ISSUE TITLE
Mark as read

### ISSUE THREAD

**Issue by vanek49** [aj3423/SpamBlocker#195]
### The feature

Hi. Need useful function "mark as read" for calls and sms. 
Please make a long tap menu on the call and sms icons "mark all calls as read", "mark all sms as read".
And logically, tap on a call to mark as read (now tap on a call and swipe to the right leads to dialing, at the same time a tap on an SMS expands the SMS and marks it as read, swipe to the right leads to the built-in application).

**Comment by aj3423** [comment]
I'll add a "mark all as read" in the context menu. And since there is already the swiping right, I'll change the tapping logic to "mark as read", for both call and sms.

**Comment by aj3423** [comment]
done. https://github.com/aj3423/SpamBlocker/actions/runs/11878520436
