### ISSUE TITLE
Per contact/number SMS rules

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#2]
I want to create a whitelist pattern for SMS from a particular contact (telco provider).

**Comment by aj3423** [comment]
You can create a filter with that particular number, e.g: if the number is 123, the filter would be `^123$`, set with a higher priority like 10.

**Comment by bb1a2** [comment]
But that will filter all SMSs from them. I want to filter only some. Or did I misunderstand?

**Comment by aj3423** [comment]
The  `^` means begin with, `$` means end with, the pattern `^123$` means begin with `123` and end with `123`, which means the exact number 123, it only applies for this number,  other numbers won't be affected.

**Comment by bb1a2** [comment]
I understand regex :)

What I meant is: For number 123, block only messages containing: "win". Is that currently possible?

**Comment by aj3423** [comment]
Oh I see :) It's currently not possible..

**Comment by aj3423** [comment]
Do you see any app has this feature? I'd like to see how they implement such setting on GUI. My first idea is a content pattern like `number:xxx yyy`

**Comment by bb1a2** [comment]
I would imagine it like

```
Number field: (supports regex)

Content field: (supports regex)
```

**Comment by aj3423** [comment]
Yeah, by the `number:xxx yyy` I mean two regex in one filter. For example, to block messages contain "win" from number 123, use a filter like `number:^123$ content:.*win.*` or maybe simply  `number:^123$ .*win.*`

**Comment by bb1a2** [comment]
That could work. But I think you should keep it simple (without custom syntax).

**Comment by aj3423** [comment]
Oh, now I understand, by this:

> Number field: (supports regex)
> 
> Content field: (supports regex)

You mean, add a "Number field" above the "Content field", that's better. I'll think more about this later, will add this feature.

**Comment by aj3423** [comment]
Done, try the v1.2 on the release page, it takes a couple of days to get synced to fdroid.
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/0c612d27-8f5e-4968-98de-a2004070de85)
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/33693b0a-063e-42d3-aebf-15f7315b739a)

**Comment by bb1a2** [comment]
Thanks!

**Comment by GitSyncPromedia** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
l3yx, @DCodeAus, @giovanniSanchez, @plinki, @0xBaconPancakes, @nimmortal, @Forcewithus, @Uptre, @Shraknard, @gkhaos, @evilcos, @whiteath, @jonghwaC, @allilou, @streichsbaer, @avenbreaks, @maciejklimek, @tilt41, @spalen0, @pranshu-taneja, @edwinteo96, @wdv4758h, @jwgatt, @Aristarhys, @cedricwalter, @obatirou, @thurendous, @tina1998612, @wzqs, @dalberto, @50c3, @tserg, @fabianorodrigo, @CeliktepeMurat, @wdcs-dastageersayed, @DecoratedWings, @FreezyEx, @htcarr3, @twseptian, @silochad, @lifeoftheghost, @koraykoska, @rmallof, @Ed94, @Balou9, @cyl520134, @wiasliaw, @yuki1109, @drucoin13, @Theger14
