### ISSUE TITLE
Sort rules

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#20]
Manually/alphabetically/priority. Easier management.

Thanks

**Comment by aj3423** [comment]
Currently it's ordered by priority descending, I think "priority then alphabetically" would be enough, how do you think?

**Comment by bb1a2** [comment]
Yeah that makes sense.

**Comment by aj3423** [comment]
Done, try the latest action build: https://github.com/aj3423/SpamBlocker/actions/runs/8934899159
