### ISSUE TITLE
Maybe bug

### ISSUE THREAD

**Issue by Umotas** [aj3423/SpamBlocker#208]
### SpamBlocker version

3.5

### Android version

12

### The issue

(1) step
Contacts - on (Exclusive)
Or/and
Rule:
Contacts (c) `.*` - whitelist
Priority 10
P.S. contacts have the number 43299887766
(2) step
Rule: 43299.*
Decs: 000
Blacklist
Priority 1.
(3) step
Number 43299887766 was blocked by rule 000
Why?

**Comment by aj3423** [comment]
I can't reproduce this, in my case, it's allowed by the contact rule `.*` as expected.
![Screenshot_20241202-194927_SpamBlocker](https://github.com/user-attachments/assets/75371452-ce60-4199-afd9-7c2eb091884d)

BTW, this verbose testing log is added in the latest tag.

**Comment by Ilithy** [comment]
Hi;
This normal behavior, if you check the prioritization of contacts, in exclusion, they have a priority of 0, so your blocking rule (having a priority of 1) acts before.

See capture: 
![Screenshot_20241203-074204](https://github.com/user-attachments/assets/8ea4cbb5-e9b4-4f7a-b258-b420c7ccf13b)

**Comment by aj3423** [comment]
Yeah, negative filters have priority 0, except the MeetingMode.

**Comment by Ilithy** [comment]
Maybe it could be interesting to make the quick settings priorities editable...

**Comment by Ilithy** [comment]
I don't think so, what you are displaying is for adding a rule via regex (there, the prioritization of the rule is selectable), this does not allow you to modify the priority of the quick parameter "contacts" (inclusive or exclusive)
![_20241203_100844](https://github.com/user-attachments/assets/fb44a9cf-b4d6-42e4-b25d-cc44f939d061)



But I am probably wrong about the usefulness of such an option. :)

**Comment by aj3423** [comment]
> What is your logic to set Priority for 'Contacts' (in Exclusive-mode) to 0. Why it isn't = 10 also?

When positive and negative filters have the same priority value, it will be impossible to determine whether it should be blocked or allowed. For example, if you have both
- A whitelist rule `.*` (priority: 10) 
- A blacklist rule `.*` (priority: 10) 
What result do you expect? 

> Maybe it could be interesting to make the quick settings priorities editable...
> But I am probably wrong about the usefulness of such an option. :)

Yeah, such option would complicate the UI, and wouldn't be that necessary, 10 and 0 should've covered all use cases.

The v4.0 introduced verbose testing log, as in the previous image, which should help troubleshooting such priority issues.
