### ISSUE TITLE
Unable to delete individual blocking rules

### ISSUE THREAD

**Issue by user137** [aj3423/SpamBlocker#210]
### SpamBlocker version

3.5

### Android version

10

### The issue

![Screenshot_2024-12-04-22-19-56-237_spam blocker](https://github.com/user-attachments/assets/844603b0-66ae-43f2-a02b-6a564743cdac)
There is no option to delete a single selected rule in the app. Currently, we can only:
- Delete all rules at once ("Delete All Rules")
- Delete duplicated rules ("Delete Duplicated Rules")

**Comment by aj3423** [comment]
Swipe left to delete a rule, and history records, snack bar, spam db records, any card-element in this app.

**Comment by user137** [comment]
Thanks for quick response.
While the app already has swipe-left-to-delete functionality, it's not immediately obvious to new users. Many users might miss this gesture-based interaction. Suggesting to add visible delete options to improve user experience.

**Comment by aj3423** [comment]
I see, I'll add a menu item "Delete Rule".

**Comment by aj3423** [comment]
fixed in the latest tag
