### ISSUE TITLE
Show rule overview per logged item

### ISSUE THREAD

**Issue by ghost** [aj3423/SpamBlocker#213]
### The feature

When clicking on an item it would be nice to show a rule reaction overview.
This would show how the request reacted to every rule used (including default ones like STIR SHAKEN verification).
It would make troubleshooting easier to understand.
And it can look a little nicer, because the blocked reason (if too long) gets cut off for me.

![image](https://github.com/user-attachments/assets/19c36efa-22d5-4d09-b9c0-c76be1732508)

**Comment by aj3423** [comment]
> When clicking on an item it would be nice to show a rule reaction overview.

Such overview is now available in the latest tag, such as SMS content, API response.

> It would make troubleshooting easier to understand.

The history log already shows the block reason, and now there is a verbose Testing log, added for troubleshooting purpose.

> the blocked reason (if too long) gets cut off for me.

It's improved in the latest tag, now, if you tap on it, it will expand to up to 2 lines.
