### ISSUE TITLE
Add application to Accrescent

### ISSUE THREAD

**Issue by tegridyfarmer** [aj3423/SpamBlocker#215]
### The feature

[Accrescent](https://accrescent.app/) addresses certain security issues that F-Droid has.
[Here](https://accrescent.app/faq#app-submission) you can find more information on submitting an app on Accrescent.

**Comment by aj3423** [comment]
Right now I'll be focusing on the development, I'll try to learn it later, after this release. I do have a plan to publish it on multiple stores.
Thanks for the suggestion and the document link.
I've added this to the TODO list, closing for now.

**Comment by aj3423** [comment]
I just read their docs. 

The cool thing about F-Droid is that it will automatically synchronize updates from the github repository. Everytime I release a new tag, I simply run a github action with a single mouse click, and it will be automatically synchronized to FDroid after a couple of days.

But the accrescent works similarly to the Google Play Store, requiring the developer to manually upload the APK bundle for each update, which can become cumbersome when publishing to many stores. 

I decide to not publish on it.
