### ISSUE TITLE
Disable all call notifications

### ISSUE THREAD

**Issue by dnut** [aj3423/SpamBlocker#217]
### The feature

I don't want to see any notification when a call is blocked.

I see you can configure notifications for regex number rules, but there seems to be no way to customize the notifications for calls blocked by any of the other filters. I simply never want to see any notifications from this app about any calls. It's strange that this is not customizable.

**Comment by aj3423** [comment]
You can simply disable all notifications from this app in system setting.

**Comment by dnut** [comment]
I'm aware of that but I use it for sms also and i want those notifications. The system notification settings for this app do not distinguish between sms and phone calls.

**Comment by aj3423** [comment]
I'll separate them, there will be a new notification channel like "call default" and maybe "sms default" as well.

**Comment by aj3423** [comment]
Done: https://github.com/aj3423/SpamBlocker/actions/runs/12217818811

**Comment by aj3423** [comment]
Ah, sorry, it's fixed https://github.com/aj3423/SpamBlocker/actions/runs/12223851558
