### ISSUE TITLE
Scroll between screens

### ISSUE THREAD

**Issue by ghost** [aj3423/SpamBlocker#219]
### The feature

It would be nice to scroll between screens, without having to press the navigation buttons at the bottom every time.

**Comment by aj3423** [comment]
No plan for this, the UI is not my thing, actually I'm not an android developer, I learned just enough for writing this app. The popup window is the easist for me to learn. And I won't merge such PR, it would complicate the development.

Personally, I use swipe gestures to close a popup(swipe left from the edge of the screen), for small popup windows, you can close them by tapping the rest area on the screen. 

BTW, sorry for the late reply. I don't know why, but github didn't push these feature requests to me, I'm surprised to see them in the issue list right now.
