### ISSUE TITLE
How to add a rule for a Name "number"

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#22]
For example, a message from "Microsoft". I can add the rule itself, but can't test it (test popup only allows numbers). Will it even work?

**Comment by aj3423** [comment]
I don't get it, "message from Microsoft",  this SMS message has no number?

**Comment by bb1a2** [comment]
Yes. It shows the word `Microsoft` instead of the number. When I add a new contact from the SMS app, it prefills `Microsoft` in the Contacts app number field.

**Comment by aj3423** [comment]
Interesting.. I've never seen such messages..  But I found something related from google
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/696fffe2-ce71-4a70-8169-3f4e580faae4)

Previously there was an issue about "empty number", maybe it's the same problem.

I'll look into it later.

**Comment by bb1a2** [comment]
I think they make a deal with the telco to forward their SMS without having to show a number.

**Comment by bb1a2** [comment]
I can confirm that setting the name in the number field works. The SMS was blocked. What remains is the tester accepting letters.

**Comment by aj3423** [comment]
Thanks, I'll just enable typing letters for that input field.

**Comment by aj3423** [comment]
Done, try the latest action build: https://github.com/aj3423/SpamBlocker/actions/runs/8934899159

**Comment by bb1a2** [comment]
Thanks. However, there is an issue. I will create a new issue for it.
