### ISSUE TITLE
Testers wanted for v4.0

### ISSUE THREAD

**Issue by aj3423** [aj3423/SpamBlocker#220]
### The feature

Two main features that are introduced in v4.0:

1. Instant query 
  - query incoming number in real time
3. Report number
  - Manually report as Fraud/Marketing/...
  - Auto report without manual intervention.

Currently there is only one API preset, but it's possible to integrate any API.

And if you don't use these features, you can also help testing, as it's been refactored a lot. 

Here's the pre-rerelease: https://github.com/aj3423/SpamBlocker/releases/tag/latest

Thanks.

**Comment by userx77** [comment]
May I ask why you don't have your own topic about the app anywhere Xda, reddit .. or ? It should be easy to find testers there 🙂

**Comment by aj3423** [comment]
I'd prefer to limit the number of testers, the more people involved, the quicker I have to fix issues:) 5 to 10 downloads per day would be ideal, as it is now.
