### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Prisoner709** [aj3423/SpamBlocker#222]
### The feature

[strings_1.xml.zip](https://github.com/user-attachments/files/18135216/strings_1.xml.zip)
I am sending the Italian language translation file and propose inclusion in a future update. Thank you. I hope for more Italian-language contributors. P.S. Can you give me a description of Regex? I don't understand what you mean by this word.

**Comment by aj3423** [comment]
Thank you for the translation. 
Actually there are 14 xml files,  strings_1.xml ~ strings_14.xml. 
I copied your translation to 1.xml, the rest are translated using AI, here you go:
https://github.com/aj3423/SpamBlocker/actions/runs/12328829396

**Comment by Prisoner709** [comment]
Okay, later I will check the translations for correctness and if there are errors I will correct them. Thanks again.

**Comment by aj3423** [comment]
>  Can you give me a description of Regex? 

Answered by AI:

A "regex expression," short for "regular expression," is a sequence of characters that defines a search pattern in text, allowing you to find and manipulate specific strings within larger pieces of data using advanced matching criteria, often used for tasks like data validation or text processing within programming languages. 

You can find more examples on the readme page.

**Comment by Prisoner709** [comment]
> > Can you give me a description of Regex?
> 
> Answered by AI:
> 
> A "regex expression," short for "regular expression," is a sequence of characters that defines a search pattern in text, allowing you to find and manipulate specific strings within larger pieces of data using advanced matching criteria, often used for tasks like data validation or text processing within programming languages.
> 
> In this app, it's used to check if the number or SMS content matches a particular pattern. You can find more examples on the readme page.

Okay, i understood. I think Regex is more succinct, but maybe a normal user (like me) can understand immediately what he is referring to. If you want to insert the correct literal translation for Regex is: "Espressione regolare"

**Comment by aj3423** [comment]
I'd prefer using the shorter "Regex" , because long text will break the UI.

**Comment by Prisoner709** [comment]
Right. I have updated the apk. With patience, I will check the translation, but from a first superficial review, there are no major errors. Some minor corrections in syntax and grammatical structure are needed. I assure you that there are many native speakers who speak and write much worse than this translation. The app is really functional and protects against jammers. Thanks.
