### ISSUE TITLE
French blocking list

### ISSUE THREAD

**Issue by Bibuzar** [aj3423/SpamBlocker#223]
### The feature

I use a list of prefixes to block voice spam in France, and it works great. Professionals have to use these prefixes.

Here is the list : 

- 0162, 0163, 0270, 0271, 0377, 0378, 0424, 0425, 0568, 0569, 0948, 0949 (France métropolitaine : +33)
- 09475 (Guadeloupe, Saint-Martin, Saint-Barthélemy : +590)
- 09476 (Guyane : +594)
- 09477 (Martinique : +596)
- 09478, 09479 (La Réunion, Mayotte : +262)

For exemple, with a rule written like this (?:33)?162.* for the 0162 prefix, it works perfectly.

Source : 
ARCEP : https://www.arcep.fr/actualites/actualites-et-communiques/detail/n/plan-de-numerotation-050922.html

**Comment by aj3423** [comment]
Hi, I'm not quite sure what this is about. 

Are you looking for a regex? But it's already working perfectly.
Do you want to share your regex? But where is it?
Or just promoting the website and let people do it on their own?

**Comment by Bibuzar** [comment]
Hi, at the moment I have a working list. And I was thinking of a solution to make it easier for French users to use this regex, either by importing a list or by selecting an option in the app. 

I'm not sure how I can share this list and in which format.

**Comment by aj3423** [comment]
I see, if you are using a single regex like `(?:33)?(162.*|163.*|270.*|......)`, simply share it as a text string.
For multiple rules, consider using a .csv file, for example:

```csv
pattern, description
(?:33)?(162.*|163.*|270.*|......), description A
(9478.*|9479.*), La Réunion Mayotte 
...
```
It can be "imported as multiple rules" by other people.

**Comment by hayvan96** [comment]
As for me here's my regex in France
`(?:33)?(1(?:62|63)|2(?:70|71)|3(?:77|78)|4(?:24|25)|5(?:68|69)|9(?:48|49))\d{6}
`

**Comment by aj3423** [comment]
I'll create a wiki page to gather all regex templates, there will be a new entry "Share Regex" when reporting issues, you can share your regex here and I'll merge them to the wiki page.

**Comment by aj3423** [comment]
It's done, please shared it in the issue list, they will be collected to the wiki page.
![image](https://github.com/user-attachments/assets/fb2b3602-82a7-4f8b-bff6-9a6e89f3bbc7)

**Comment by aj3423** [comment]
Done, now the wiki will be updated automatically whenever there is an issue with label "share regex" is ceated, edited , or deleted.


For example, this issue:
![image](https://github.com/user-attachments/assets/66fac982-e63c-4461-8b0b-2e906847ee86)


will be sychronized to wiki like:
![image](https://github.com/user-attachments/assets/4531f82a-2f35-4f5e-b11d-0ad88c6778fb)

**Comment by aj3423** [comment]
> either by importing it or by selecting an option in the app.

I think users should have the ability to preview the contents before importing, because the usefulness of them is very subjective. I anticipate there to be lots of regex templates in the future, a larger web page would be a better option.

And more importantly, I don't need to mantain the list, the wiki page will get updated automatically :)

**Comment by Bibuzar** [comment]
Ok, so I close this issue. We can share our Regex now :) .

Thank you

**Comment by M0lyk** [comment]
Bonjour,
J'ai installé cette app il y a quelques temps et je n'ai jamais réussi à la faire fonctionner, or aujourd'hui ces appels sont un vrai problème, c'est plusieurs fois par jour.

Je ne comprends pas le fonctionnement de l'app, j'ai testé plusieurs syntaxes : les appels ne sont pas bloqués.

Merci de votre aide

![Screenshot_20250218-145620_SpamBlocker.png](https://github.com/user-attachments/assets/8448c090-40df-4ab0-8327-c182d22f053d)

**Comment by aj3423** [comment]
@M0lyk Veuillez me montrer un numéro d'exemple, de plus, il serait préférable d'ouvrir un nouveau problème séparé pour cela.

**Comment by M0lyk** [comment]
@aj3423 J'ai mis une nouvelle syntaxe aujourd'hui, copiée-collée sur cette page. J'ai fait un essai et ça disait Passé par défaut.
Si ça se renouvelle je créerai un nouvel issue.

Merci
