### ISSUE TITLE
[France] Blocage Démarchage

### ISSUE THREAD

**Issue by hayvan96** [aj3423/SpamBlocker#226]
### The regex

(?:33)?(1(?:62|63)|2(?:70|71)|3(?:77|78)|4(?:24|25)|5(?:68|69)|9(?:48|49))\d{6}

**Comment by aj3423** [comment]
Thanks. 
There seems to be a bug, it should've been synchronized to the wiki, but it's not triggered, I'll look into it.

**Comment by aj3423** [comment]
fixed.

**Comment by marek22k** [comment]
What is "Blocage Démarchage"?

**Comment by marek22k** [comment]
Should I enable "raw number" in the RegEx flags?

**Comment by Fred-Vatin** [comment]
Some other patterns have been added by ARCEP. Check this comment and the updated regex:
https://github.com/aj3423/SpamBlocker/issues/238#issuecomment-3859524663

**Comment by hayvan96** [comment]
Nice catch, I hadn't seen these new additions by ARCEP. Should I edit and update my first post?

**Comment by aj3423** [comment]
> Should I edit and update my first post?

No need, it's been updated, please check this one https://github.com/aj3423/SpamBlocker/issues/524
