### ISSUE TITLE
Make .apk signed with sha256

### ISSUE THREAD

**Issue by ghost** [aj3423/SpamBlocker#227]
### The feature

It would be nice if we could verify the integrity of the .apk file.

**Comment by aj3423** [comment]
Here's what Signal and Proton do:
https://signal.org/android/apk/
https://proton.me/support/verify-apks

```
apksigner verify --print-certs SpamBlocker.apk
Signer #1 certificate DN: C=f, ST=e, L=d, O=c, OU=b, CN=a
Signer #1 certificate SHA-256 digest: 7b1ce727856f3427eab1fadfad6c9730cd4e6ba201661547f009206377dffb58
Signer #1 certificate SHA-1 digest: 8401610cf977f4a8e6f3b25f5d3ea94367e9396a
Signer #1 certificate MD5 digest: 3d466485d721c3e6805f58743ad93aae
```

Do you mean this?

**Comment by aj3423** [comment]
Currently all apks are signed by this signing key, including the action builds.

The sha256 hash is:

7b1ce727856f3427eab1fadfad6c9730cd4e6ba201661547f009206377dffb58

I'll add this to the readme.
