### ISSUE TITLE
How To Set Regex Options?

### ISSUE THREAD

**Issue by Astronox** [aj3423/SpamBlocker#23]
Sorry for opening another issue relating to not understanding regex. I've been using https://regex101.com/ to try to help, but it's unclear to me what specific flavor of regex I'm supposed to be using. 

I've been checking how to use regex options in Kotlin (since that's what this app is written in), but unless I'm misunderstanding things, there's no way to pass options like "IGNORE_CASE" in the app. Here's where I'm getting that information: https://www.baeldung.com/kotlin/regular-expressions . I'm also not familiar with Kotlin, so I might be missing something there too.

For my own use case, I get a lot of political spam texts. I'm able to block them by checking for URLs. So most of my filters are of the form `.*spamurl\.com.*`. This successfully blocks texts with that URL, but I've noticed it doesn't work when the texts have a newline. I think setting a "DOT_MATCHES_ALL" flag for my regex would fix this, I just don't know how to do that with this app.

I'm on version 1.4 right now, on a Pixel 8, running GrapheneOS.

**Comment by aj3423** [comment]
I'll change it to be case insensitive by default, and new line characters will be removed before checking.

**Comment by Astronox** [comment]
Hey, thanks for the response, but is there a way to add options in the app that I just don't understand?

For example in Java I would type my regex string as `".*spamurl\.com.*"gmis`, where the string I'm checking for is in quotes, and then my options are outside the quotes. I've tried that in your app and backslash, forwardslash, quotes, and grave (\`) all don't work.

**Comment by aj3423** [comment]
Ah I see, thanks for the explanation. Seems languages have different syntax for the inline options, such as: 

- rust,golang: `(?i)pattern`
- ruby,js,php: `/pattern/i`

Kotlin doesn't support such inline syntax, it supports options like:

`pattern.toRegex(IGNORE_CASE | MULTILINE).match(str)`

Available options in Kotlin:
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/-regex-option/

The useful ones are:
	IGNORE_CASE
	MULTILINE
	DOT_MATCHES_ALL
	LITERAL
	CANON_EQ

I'll parse the pattern string into these options, it'll support syntax like: `(imdlc)pattern`, how do you think?

**Comment by Astronox** [comment]
You could make it part of the string, but if you implement it like that, you're probably going to get questions from users in the future on how to toggle those options. I think your main goal should be to minimize the number of questions you get about this.

![IMG_20240501_225143](https://github.com/aj3423/SpamBlocker/assets/38494293/d2e6313f-2666-456c-a0f6-21c1103767e5)

Regex is already kind of hard for people to understand already. I think the easiest to understand option may be to add checkboxes to this dialogue box I screenshotted for each of the useful options you listed. You can then pass those to Kotlin's regex interpreter. Adding 5 checkboxes might be a little cluttered though, so you could also do a drop-down menu, a sub-menu, or additional pop-up. I'm not a UI designer though.

Another option would be to have another textbox below where we put in our regex patterns for us to input those options, with a question mark icon explaining how to use the box and that only `imdlc` are valid inputs, explaining what each one does. Then it's trivial to just tell Kotlin an `i` in that box means add `IGNORE_CASE` to the interpreter.

Finally, you could steal from https://regex101.com UI, and have the delimiters set in the Regex pattern box automatically, then you could just copy how one of the languages handles regex, and expect users to know to put their options outside the delimiters.

I think your idea of `(imdlc)pattern` could cause issues with both users who are familiar and unfamiliar with regex. The unfamiliar ones won't know what to look up since you're using a non-standard version of regex. The familiar ones won't know what to do since they're used to other existing conventions. If this is the easiest one for you to implement, I think it's closest to the second option I mentioned where you just have a second text box that you would label "Regex Options" or something. 

Thanks for making this app by the way. Hope my input helps.

**Comment by aj3423** [comment]
You are right, the solution from regex101.com looks much better. I'll try to implement something similar, an icon on the right side showing current flags, when it's being clicked, it popups a dialog with 5 checkboxes(imdlc) and a detailed tooltip.

Something like:
https://github.com/aj3423/SpamBlocker/assets/4710875/d1b86a7d-fecb-4d69-ab00-54610f084d7e

**Comment by aj3423** [comment]
Completed in this action build, thanks for the advice.
https://github.com/aj3423/SpamBlocker/actions/runs/8952209426

I dropped some flags, I think they are useless in this app and will make user even confused,  three are supported:
- Ignore Case
- Dot Match All
- Literal

The rest flags can be added easily, I'll add them if necessary.

**Comment by aj3423** [comment]
On a second thought, I made some more changes:
- dropped `Literal`, I can't come up with any use case of it.
- IgnoreCase and DotMatchAll are set by default, and the indicators "i", "d" are hidden by default.

The tag latest has been updated.
