### ISSUE TITLE
Descriptive name of notification channels

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#24]
Hi,

Can you please name notification channels by their pattern instead of 1,2,3,4? For example, `SB_Shade` SB_Shade+Sound`.

I would like to edit something in how the notification is shown and the current naming is confusing.

Thanks

**Comment by aj3423** [comment]
Yeah, will do that, maybe without the prefix SB_, just `Shade`, `Shade+Sound`.

**Comment by aj3423** [comment]
Done, try the latest action build: https://github.com/aj3423/SpamBlocker/actions/runs/8934899159
