### ISSUE TITLE
Rules with Name "number" aren't respected

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#25]
Steps to reproduce:

- create SMS blacklist rule 1 for content `.*`. Priority 5
- create SMS whitelist rule 2 for number `Microsoft` and content `.*`. Priority 10
- test message from `Microsoft`

Expected: rule 2 applies

Actual: rule 1 applies

Note: this issue only happens with name numbers. If you replace `Microsoft` with a number, the correct rule applies

**Comment by bb1a2** [comment]
Try `Micro-soft`

**Comment by aj3423** [comment]
still works
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/45edee2c-4829-4674-8901-9f9e7a10d9ae)

**Comment by bb1a2** [comment]
Change the rule itself too, please

**Comment by aj3423** [comment]
Fixed in the tag latest: https://github.com/aj3423/SpamBlocker/releases/tag/latest
And it also fixes a RepeatedCall bug that it doesn't work.

**Comment by bb1a2** [comment]
Works! Excellent! Thanks for being very responsive.
