### ISSUE TITLE
Improvements to SMS notifications

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#27]
1. An icon different from the main (blocking) icon **for the pass notification**. An SMS-related icon since this app is supposed to take over notifications.
2. As you have a different icon, there is no need for the "New SMS Message" text which takes valuable space. You can have the message sender as title just like regular SMS apps.
3. Also "SMS Message blocked" can be shorter like "Blocked: \<Sender\>" as title.

**Comment by aj3423** [comment]
Yeah, it looks better.
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/7fadc953-7049-425e-a9ab-89d3f9c2f25a)

**Comment by bb1a2** [comment]
Yeah. I'll recommend using different icons (other than the color) because status bar and lock screen notifications are monochrome. Maybe keep the filter icon for blocked?

**Comment by aj3423** [comment]
What about this

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/23940a8a-3811-4467-8eaf-7dbcf7e91857)

**Comment by bb1a2** [comment]
I like it! But could you make the x a bit larger in the SMS or remove the three dots from the green one? To better tell them apart without squinting!

**Comment by aj3423** [comment]
Not sure how to draw svg icon... just downloaded from https://www.svgrepo.com/vectors/sms/

By "make the green blank" , do you mean this one?  https://www.svgrepo.com/svg/446337/sms

**Comment by bb1a2** [comment]
> By "make the green blank" , do you mean this one? https://www.svgrepo.com/svg/446337/sms

Yeah but white

**Comment by aj3423** [comment]
From https://source.android.com/docs/core/connect/call-notification

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/9fff8f38-5d49-4b5b-a0d7-b4d58f360840)

What Android version is it?

**Comment by bb1a2** [comment]
Wrong topic :)

**Comment by aj3423** [comment]
When the color is determined by system, it's gray on light theme.

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/3d8c1e20-3dd9-4e56-82af-c336f3bbe3bd)

Even lighter on dark theme

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/e6df72e5-5264-4611-bdd9-882d821753fe)

**Comment by bb1a2** [comment]
Close enough :)

**Comment by aj3423** [comment]
done in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/8952209426
