### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#28]
1. In call/SMS log, the item height should expand vertically if the rule name is long.
2. Regex entry fields should have word-wrap and should expand vertically as you enter text. Scrolling left and right is difficult.

**Comment by aj3423** [comment]
Like this:

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/eaa31cf1-8b6e-445f-baab-70b4fc39ef6a)

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/2aa0cb38-d3fe-4c41-9c84-bdb4f1b0d225)

**Comment by bb1a2** [comment]
Yeah, exactly.

**Comment by aj3423** [comment]
done in this action https://github.com/aj3423/SpamBlocker/actions/runs/8951796439

**Comment by bb1a2** [comment]
Thanks
