### ISSUE TITLE
Question: is there a way to not notify system of blocked call?

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#29]
The native "call blocked" notification in the system is obnoxious (with sound) and two notifications are created. The system does not allow modifying or disabling these notifications. Is there a way for SB to handle the call blocking notifications, leaving the system out of it?

Thanks

**Comment by aj3423** [comment]
Not sure if it's caused by the `setSkipCallLog(false)`, I just released an action build with that set to `true`. I guess now the stock call app wouldn't know there is a call rejected.

try this:
https://github.com/aj3423/SpamBlocker/actions/runs/8951796439

**Comment by bb1a2** [comment]
No, system still notifies

**Comment by aj3423** [comment]
The call is blocked by SB , and SB doesn't show a notification?  I just tried on emulator and a phone , both works.
Does your system allow changing the default call app?

**Comment by bb1a2** [comment]
>Does your system allow changing the default call app?

Yes. I use Fossify

**Comment by bb1a2** [comment]
One notification is named "Call blocking". The other is a missed call notification. Both from an app called "Phone calls" `com.android.server.telecom`

**Comment by bb1a2** [comment]
> From https://source.android.com/docs/core/connect/call-notification
> 
> ![image](https://private-user-images.githubusercontent.com/4710875/327963859-9fff8f38-5d49-4b5b-a0d7-b4d58f360840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NDMzNzcsIm5iZiI6MTcxNDg0MzA3NywicGF0aCI6Ii80NzEwODc1LzMyNzk2Mzg1OS05ZmZmOGYzOC01ZDQ5LTRiNWItYTBkNy1iNGQ1OGYzNjA4NDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDRUMTcxNzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTAxNDE1MjhlM2E1MmJjZDU4ODJlYjMzYzFlZjhhNmU3NWNiMDBjMTc4ZTkwZDYzODI5MzA0YzlmNGUzODM3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5J-zOjncNTYo7r4lpZNGoJqqvxN4YXvreyXo6mP31b8)
> 
> What Android version is it?

13

**Comment by bb1a2** [comment]
Even regular missed calls are handled by the system app.

**Comment by aj3423** [comment]
>  If I block the same number in Fossify Phone (without changing the default spam app), no second notification (no missed call), and the block event is not added to SB log.

It looks like Fossify is acting as the default Call ID app. Maybe try clicking on the bottom `Call` icon in SB, SB will check if it's the default ID app every time it's clicked. Or maybe verify that in system setting.

And I just checked the source code of Fossify, it does have call id feature, but without any popup confirmation? 

I found a difference, when a call is blocked, Fossify does `setSkipNotification(true)`, while SB doesn't . I just added it in this action build, maybe have a try to see if any difference.

https://github.com/aj3423/SpamBlocker/actions/runs/8952209426

**Comment by bb1a2** [comment]
I tried both
- another dialer (koler)
- another phone (Android 14) from a different manufacturer

In both cases, the same system app "Phone calls" handles call notifications.

**Comment by bb1a2** [comment]
> It looks like Fossify is acting as the default Call ID app.
It offers to be so but I had SB as the ID and spam app for the past few days.

>Maybe try clicking on the bottom `Call` icon in SB, SB will check if it's the default ID app every time it's clicked. Or maybe verify that in system setting.
When I click, it opens Fossify Phone

**Comment by aj3423** [comment]
> When I click, it opens Fossify Phone

This means currently SB is the Call ID app, not replaced by Fossify,  it's strange that it doesn't show notification.

**Comment by bb1a2** [comment]
I tried the latest build:
- no more missed call notification
- the main "call blocked" notification from the system app remains
- no notifications from SB

**Comment by aj3423** [comment]
>  no more missed call notification
So this is solved by `setSkipNotification(true)`

I just tried the action build on emulator and a phone, both have notification for blocked calls.  Maybe change the notification type to head-up for that blacklist rule, and verify the notification channel settings. 

Or do you have `adb` installed? If so , can you please try `adb logcat` in terminal, to see when a call is rejected, if there is any exception or error text.

**Comment by bb1a2** [comment]
That was it. I was experimenting with a rule set to none. Sorry 😳 and good catch.

That's issue number 2 solved. What remains is how to disable that system notification.

**Comment by bb1a2** [comment]
I figured how to silence that notification so it doesn't make a sound.  You helped me a lot. Thank you.

Feel free to close the issue.

**Comment by aj3423** [comment]
> I figured how to silence that notification so it doesn't make a sound.

How did you do that?

**Comment by bb1a2** [comment]
It doesn't allow you to set the notification to silent, but it allows you to change the notification sound. So I set the sound to "None" from the menu.

**Comment by aj3423** [comment]
Aha.
