### ISSUE TITLE
Global rule settings and rule template

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#30]
Hi,

A message that should be blocked passed. After investigating I found that the reason was due to multiline. As I wanted to update my rules, I realized two things:

1. It would be nice if there are global variables/settings. For example, regex flags by default without having to set multiline for each rule.
2. User-defined settings (like a template) when creating a new rule. For example, when I tap add a call rule, I'd want:
    1. SMS unchecked
    2. regex already prefilled with `^((\+|00)?44)?`
    3. Notification set to none
    4. Any useful future setting

I want to hear your thoughts.

**Comment by aj3423** [comment]
1.  Maybe try this "Dot For All", I just added this feature yesterday, this flag is for matching multiline, maybe I should set it on by default.

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/14b9c74c-6088-453b-82a0-7e44ddf24cbf)

2. I think "rule clone" would be better than using template

**Comment by bb1a2** [comment]
1. Yeah, thanks. That's what I did. I should have been more clear. I just have to remember it every time in the future.
2. That could work too.

**Comment by aj3423** [comment]
1. These two flags will be set on by default: IgnoreCase and DotMatchAll
2. I'll add this "rule clone" featue:
long press a rule -> popup context menu -> click "Clone"
