### ISSUE TITLE
Problem with a valid Regex pattern

### ISSUE THREAD

**Issue by djelloul78** [aj3423/SpamBlocker#34]
Bonjour, 

First of all I'd like to thank you for the app you're developing as it's a really efficient one and a great alternative to "Yet Another Call Blocker" that is considered dangerous for no reason by Google Play Protect rules...

I'm currently facing a strange problem with Regex pattern that I'm not able to solve whatever release SW I use (Normal or Pre-Release variant).

I'm living in France and we sometimes (often!) receive spam calls from commercial companies that are more disturbing than useful.
Here we have the chance that our telecom national manager (ARCEP) have created rules to those spammers to use only specific phone numbers for their services since beginning of January 2023.

That doesn't mean all spammers are following the national rules, but not doing so is now illegal in our country.

Using your app, I've been able to efficiently filter those calls but some of them are still bypassing the blocking feature.

After checking, I had understood why it's not always working but I don't understand why. 

For the context, when we receive a call it could be shown as:
- +33X XX XX XX XX (International Format)
- 0X XX XX XX XX (National Format)

Let's say I'd like to filter all calls that begin with 02 70 XX XX XX or +332 70 XX XX XX.
The following Regex pattern should apply to both format:
`^(0|\+33)270.*`

I've tested it on Regex101 website and it's working fine but when I test it on SpamBlocker, this pattern only blocks 02 70 XX XX XX XX phone numbesr but not +332 70 XX XX XX.
I also tried changing the Regex pattern to: `^(\+33|0)270.*` but no change and same behaviour is observed. 

This problem seems similar to issue [#30 ](https://github.com/aj3423/SpamBlocker/issues/30) so I installed your last recently pre-released version that allows changing the Regex rules that applies but none of the combination with or without Regex flags activated seems to have an effect. 

I know that creating 2 different Regex rules will solve my issue (`^0270.*` and `^\+33270.*`) but it isn't compliant with the smart Regex method you allow us to create. 

From your point of view, is there something I'm doing wrong or do you identify something not running fine in the Regex filtering?

Thank you for your attention.

**Comment by aj3423** [comment]
Hi, thanks for the feedback.

The reason why the "+33" doesn't match is because it clears all special characters before checking, the "+33 1122" becomes "331122", so the "+" isn't necessary here. I tried your regex without the "+" and it worked.
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/1d80aa61-523a-446f-acaa-127019d72ad9)

I'll change the help tooltip for this.

About the prefix "0", it wasn't taken into account because I had no experience with it. I just did some homework, it seems to be commonly used in many countries, even two zeroes. I think I should remove all the leading zeroes as well, it should make writing regex easier.  In your case you can simply use regex like `(33270|270).+`, how do you think?

**Comment by aj3423** [comment]
Done, the leading zeroes are now removed, try the latest tag: https://github.com/aj3423/SpamBlocker/releases
And more description in the tooltip:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/a5171fe3-9f36-4f95-9300-ff28528cdb43)

**Comment by djelloul78** [comment]
Thank you for reacting so fast and your clear explanation regarding the "+" symbol influence in the app.

I tried your Regex pattern proposal and it's perfectly working, so I'll take it as a definitive solution. 

I also tried your latest tag and I think your new logic design is a smart idea but it doesn't take an important aspect in account: The international country code.
In your tool tip exemple, you suppose that the leading characters could be a chain of 0s or a "+" symbol.
In France case, when "+" is present, the "33" international country code is inserted in between the "+" symbol and real start of phone number so your evolution doesn't apply in this case. 

In my opinion, just explaining that special characters "-" and "+" aren't taken in account in the Regex pattern is enough to let us create a correct rule. 
If you identify other special character that have same consequences, just list them in a tool tip for proper guidance and that should be fine.

What do you think?

**Comment by aj3423** [comment]
>  you suppose that the leading characters could be a chain of 0s or a "+" symbol.

Actually I understand there won't be leading zeroes after the country code "+CC", they may exist only when there isn't "+CC". There is an order removing them, leading 0s are removed first, then the special characters, like:
```kotlin
            return number
                .trimStart('0') // remove leading "0"s first
                .replace("-", "")  // then special characters
                .replace("+", "")
                .replace(" ", "")
                .replace("(", "") 
                .replace(")", "")
```
https://github.com/aj3423/SpamBlocker/blob/d826a1994a43c6691ee7b2148cbf608a0ddb1ba7/app/src/main/java/spam/blocker/util/Util.kt#L70
I think this covers all cases including "+33" followed by real number. And I think there won't be '-' in the incoming number, they only exist in the contact number, I did some changes to the tooltip, so user won't get confused anymore.
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/56d34270-789b-4447-baa4-4c660b2cac20)
