### ISSUE TITLE
Add possibility to Export/Import app configuration or set of filtering rules

### ISSUE THREAD

**Issue by djelloul78** [aj3423/SpamBlocker#35]
Bonjour, 

In order to use the app in multiple phones, it would be a good idea to have the possibility to Export configuration or set of filtering rules to a file that could be transferred in another device and Import it in order to avoid repeating the editing already made in original phone.
It can also be useful if we reinstall the app after a phone factory reset.

Improvement could also be made by adding the possibility to transfer the Exported file to cloud services (G-Drive, OneDrive, etc...) directly from the app in order to have a complete in app experience but this could be done in a second time. 

What's your opinion about this proposal?

**Comment by aj3423** [comment]
Hi, 
This is already in the plan: https://github.com/aj3423/SpamBlocker/issues/19. 
However this app is supposed to work completely offline, I don't want it to require the internet permission just for this feature.
I think it would be like: a multiline text field filled with current configuration, copy that text to other phones and import to the same text field, then click "ok".

**Comment by djelloul78** [comment]
Understood and thank you for your quick feedback.
I should have taken a better look on the other issues before opening this one.

I totally agree your statement regarding the online capacity and it seems the saving feature is coming in a near future.

I have nothing to add so feel free to close this issue whenever you want.

**Comment by aj3423** [comment]
Done in the tag latest. https://github.com/aj3423/SpamBlocker/releases/tag/latest
