### ISSUE TITLE
Convert numbers to regex

### ISSUE THREAD

**Issue by BJack0** [aj3423/SpamBlocker#37]
Entering numbers using regex isn't very user friendly, there are other call blockers that are no longer functioning that have this feature. I would be a massive QOL improvement.

**Comment by aj3423** [comment]
Could you elaborate more on this?  How does this feature work, I have no idea about it.

**Comment by BJack0** [comment]
In previous apps I have used you can simply enter, `1234 *` to block any number starting with 1234. You could also add a drop-down to select a filter rather than making regex mandatory, even having an advanced option for users that prefer to use regex.

**Comment by aj3423** [comment]
I see, "wildcard mode". In that mode,  is `*` the only magic character?

**Comment by BJack0** [comment]
It's the only one that I remember. Most users just want to block repeat scam numbers that only change the last few digits. You could add more if you see fit.

**Comment by aj3423** [comment]
I'd prefer using regex directly than creating a bunch of new syntax, so I guess that app only supports `*`.

And regex can be simple too, the `.*`(regex) is identical to `*`(wildcard mode)

`1234 *` (wildcard)  ==  `1234.*`  (regex)

So I don't think it's necessary to add another mode, but thanks, I'll add this to the tips.
