### ISSUE TITLE
feature req: support Android 9

### ISSUE THREAD

**Issue by nutpantz** [aj3423/SpamBlocker#38]
I would love it if this app could support Android 9.
Which is the newest phone i have that the ex girlfriends and banks have the number.

Thank you

**Comment by aj3423** [comment]
Unfortunately, the CallScreeningService only seems to work on Android 10+:

https://developer.android.com/about/versions/10/features#call-screening
> Android 10 provides your app with a means to identify calls not in the user's address book as potential spam calls, and to have spam calls silently rejected on behalf of the user

and https://developer.android.com/develop/connectivity/telecom/dialer-app/screen-calls:
> Devices that run Android 10 (API level 29) or higher allow your app to identify calls from numbers that aren't in the user's address book as potential spam calls.

For Android 9, it has to be the default call app to filter calls, so I think it's not possible to adapt Android 9 :(

**Comment by jvschiavo** [comment]
> For Android 9, it has to be the default call app to filter calls, so I think it's not possible to adapt Android 9 :(

Couldn't the user set this app as the default call app?

If not on stock Android, maybe for a custom ROM at least?

**Comment by aj3423** [comment]
> Couldn't the user set this app as the default call app?

Writing a call app is way more work than writing a call screening app, not worth the effort.
