### ISSUE TITLE
Don't store passed calls/SMS

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#4]
Passed messages are already accepted and appear in the regular SMS app. I think the default behavior should be to show only blocked calls/messages in SpamBlocker.

If you still want the user to see all, you can for example add a filter button in the toolbar (All, passed, blocked).

**Comment by aj3423** [comment]
I think showing passed messages is as important as showing the blocked ones.  One of the main point of that history list is showing why it passed or blocked, which helps user to adjust the filter rules.

I usually take a quick glance and press the bottom SMS button, which launches the regular SMS app and navigating to the message list.

**Comment by bb1a2** [comment]
I understand. How about a filter button? Like this. You would set it to all, I would set it to "blocked". Everybody wins!

![](https://i.stack.imgur.com/KEjpW.jpg)

**Comment by aj3423** [comment]
I'll try. What is this app? What does it look like when clicked?

**Comment by bb1a2** [comment]
It is just a random image I got off the internet. If you want you can check [this app](https://github.com/FossifyOrg/Phone) that also has a filter button.

**Comment by aj3423** [comment]
Done, try this action: https://github.com/aj3423/SpamBlocker/actions/runs/8804103322

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/28636bac-3fe8-4afb-9ff3-54500b2af64c)
