### ISSUE TITLE
Unable to input alphabets in ```Phone Number``` box entry for ```Test```

### ISSUE THREAD

**Issue by refugeindhamma** [aj3423/SpamBlocker#41]
I am unable to input alphabets to test the rules in ```Test``` for both ```Number Rules``` and ```Message Rules```.

I am using LG V50s and whenever I click on the ```Phone Number``` box, a number pad will pop up and I can't change it to key in letters to test "Name numbers" for SMS.

**Comment by aj3423** [comment]
Are you using the old version 1.4 from fdroid? This is fixed in 1.5, you can download it from the release page, or the latest tag which is 1.6, no need to uninstall, just upgrade. The newer version will be synced to fdroid in a couple of days.

**Comment by refugeindhamma** [comment]
Yes I'm using version 1.4. Will update when the version is available on fdroid. Thanks.

**Comment by refugeindhamma** [comment]
Updated to version 1.5. Able to input alphabets in ```Test``` ```Phone Number``` box. Thanks for the update.
