### ISSUE TITLE
Better vertical alignment of the SMS icon in the notification

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#44]
They need to come down a bit.

**Comment by aj3423** [comment]
Like two empty rows between the message body and the Copy text? That would be too much gap I think.

**Comment by bb1a2** [comment]
No, I mean within the blue circle.

**Comment by aj3423** [comment]
like this ?
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/02f56f29-e092-4761-97c3-6f78fcda64e8)

**Comment by bb1a2** [comment]
Yeah

**Comment by aj3423** [comment]
like this 

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/bc33d1e0-e05d-463e-b0ca-baf18fd49c1b)

**Comment by aj3423** [comment]
and ![image](https://github.com/aj3423/SpamBlocker/assets/4710875/b788fbdc-9ef5-44ef-af55-524a78ae3dd4)

**Comment by aj3423** [comment]
done: https://github.com/aj3423/SpamBlocker/actions/runs/9063165440
