### ISSUE TITLE
Show message content in blocked notification

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#45]
Instead of the applied rule, which can be easily viewed in the log if needed. I think it is more useful to know what message I am dismissing.

Also, the app is very nice to use now. Thanks.

**Comment by aj3423** [comment]
Agree.

**Comment by aj3423** [comment]
done: https://github.com/aj3423/SpamBlocker/actions/runs/9063165440

**Comment by bb1a2** [comment]
Thanks
