### ISSUE TITLE
Cannot set internatifonal prefix

### ISSUE THREAD

**Issue by dmarteau** [aj3423/SpamBlocker#48]
Trying to block number with international prefix with regex like `\+33948.*` does not work : test always show 'passed'.

App version: 1.4
Phone: pixel 6a
Android version: 14

Thanks for the app.

**Comment by aj3423** [comment]
This has been fixed in v1.5, the matching logic has been simplified, described in the help balloon. Yesterday fdroid built the v1.5, it will be available soon. You can also try the v1.6 from the release page.

**Comment by aj3423** [comment]
I see this is re-opened, is it not working with v1.5?

**Comment by aj3423** [comment]
To block all calls from `+33948`, you can use filter `33948.*`. As described in the popup tip: 
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/aa7ae544-d8a5-4012-b265-822ecfd07c96)

**Comment by dmarteau** [comment]
Sorry,  I was trying again with the `\+33948.*` pattern and I miss the help balloon (checked the ballon in the *Regex flags*)

All seems to works ok now with the rules above.
Thanks !
