### ISSUE TITLE
Matching contacts doesn't take region/state prefix into account

### ISSUE THREAD

**Issue by OliveiraHermogenes** [aj3423/SpamBlocker#49]
Hi.

Thanks for this very useful piece of software.

I live in a big country where numbers have regional/local prefixes. When calling a local number, however, people don't need to dial the prefix. So, most people don't bother inserting the prefix when saving a local phone number to contacts. In this case, SpamBlocker is not correctly matching numbers to contacts because of the prefix.

![Screenshot_20240515-201043_SpamBlocker-redacted](https://github.com/aj3423/SpamBlocker/assets/25179795/777c0f20-4081-497f-b82a-4b44e73c79f2)

`083` is the prefix in this case. The redacted part in red is the number exactly as saved in contacts.

Both the default phone app and [YACB](https://gitlab.com/xynngh/YetAnotherCallBlocker) are able to correctly match the contact when receiving a call.

I am on version 1.5 installed from F-Droid.

**Comment by aj3423** [comment]
Thanks, just learnt from YACB, it'll be fixed soon.
