### ISSUE TITLE
UI issue: long rules are hidden by UI elements

### ISSUE THREAD

**Issue by bb1a2** [aj3423/SpamBlocker#5]
To reproduce, create a long regex rule for number or description e.g. `123456789|987654321|123459876|987612345`.

It is not a major issue.

**Comment by aj3423** [comment]
Fixed, at most two lines are displayed for pattern string, and one line for description. Will update in next release.

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/69a5ab3a-5ae8-4607-aa93-77ab09b9eabf)

**Comment by bb1a2** [comment]
Can you please show more than two lines? I know the point is to have pattern-based rules, but I got a couple of long rules.

**Comment by bb1a2** [comment]
10 is plenty. Thanks.

**Comment by aj3423** [comment]
Done in the latest action build.
