### ISSUE TITLE
Database or Blacklist 

### ISSUE THREAD

**Issue by Slawa79** [aj3423/SpamBlocker#50]
Hi. Are you planning to add something like a spam call database in the application, the so-called blacklist So that users can add spam numbers to the general database.

**Comment by aj3423** [comment]
Nope:) There won't be such feature like the blacklist database in TrueCaller or YetAnotherCallBlocker. 

Because:
- That doesn't help blocking new numbers, which are generated everyday. This app is supposed to block All spams. 
- Their servers may even be blocked in some countries.

**Comment by Slawa79** [comment]
O. K.

**Comment by aj3423** [comment]
Why not block all unknown numbers and only let known calls pass? As mentioned in the readme, this app is made for people who are more willing to reject unknown calls.

> spoofing repeated calls (5 in 2 minutes)

This would be a problem even for this app, currently RepeatedCall has higher priority than STIR, so it will pass anyway. I'll find a way to solve it, maybe by making the priority of quick settings configurable.

Assume this is supported, will this work for you? 

- calls fail STIR atestation are always blocked
- unknown calls are blocked
- repeated calls will pass

About this STIR checking, actually it's just one line of code, it would be easier for YetAnotherCallBlocker to add it than adding a database in this app :)
Just to mention that, some databases are downloadable, if you find such database you can download it as CSV and import to the app.

> Unfortunately YetAnotherCallBlocker and SpamBlocker cannot block calls at the same time.

Maybe fire a feature request to Android dev, I always think they should support chain of call screening, so these apps can work together.

**Comment by aj3423** [comment]
There is a plan now https://github.com/aj3423/SpamBlocker/issues/140
