### ISSUE TITLE
Number rules dosen't work

### ISSUE THREAD

**Issue by red0queen** [aj3423/SpamBlocker#52]
Hi,
I'm trying to block a range of number, but any kind of regex seems not working, including writing the entire phone number.
For example, i want to block the range 0162xxxxxx
Testing the regex pattern 0162.* with a call number 0162000001 return 'passed by default'. Same result if i write 0162000001 in the regex pattern. I'm doing wrong or it's a bug ?
Thanks

ps : GrapheneOS over a google pixel

**Comment by aj3423** [comment]
The matching logic has been simplified since v1.5, leading zeroes are trimmed before checking, as described in the balloon tip:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/7ea99cda-1da9-49d1-8f57-9c461ae62dab)

In short, you need regex like `162.*`, without the leading `0`.

**Comment by red0queen** [comment]
Ok, it's working this way. Sorry, i didn't understand this the first time I read it. Many thanks !
