### ISSUE TITLE
SpamBlocker 1.6 After restoring data from backup, the application crashes with an error and does not start

### ISSUE THREAD

**Issue by Slawa79** [aj3423/SpamBlocker#53]
In the new version 1.6, after restoring the application settings from backup, an error crash occurs immediately after launching the application. The application does not start until you reset the application data.  ( realme C25 ; android 13 )

**Comment by aj3423** [comment]
After clearing the app data, if you import the backup data again, does it crash anymore?

**Comment by Slawa79** [comment]
> After clearing the app data, if you import the backup data again, does it crash anymore?

The application does not start. For example, I restored the data, a green ✅ was drawn that the data was restored, and an error immediately occurs and crashes from the application. I clear the data and restore the data, and everything repeats, the error again.  It's a pity, I have a lot of spam numbers added there, I don't want to add them manually every time.

**Comment by aj3423** [comment]
Is the setting data sensitive? Can you send me that setting?

**Comment by Slawa79** [comment]
> Is the setting data sensitive? Can you send me that setting?

Yes, I can send you my settings, tell me how do I do it?

**Comment by aj3423** [comment]
Can you upload the text here, in a text file? Maybe remove some sensitive rules, just keep a minimal reproducible configuration.

**Comment by Slawa79** [comment]
> > Can you upload the text here, in a text file? Maybe remove some sensitive rules, just keep a minimal reproducible configuration.
> 
> Now, just a minute. Only I saved the settings to my telegram and the list of settings was divided into two parts, now I will send both to you.

{"global":{"enabled":true},"theme":{"isDark":true},"contacts":{"enabled":true},"repeatedCall":{"times":1,"inXMin":5},"dialed":{"enabled":true,"inXDay":3},"recentApps":{"list":["com.vk.mail","com.uma.musicvk","com.whatsapp","com.zvooq.openplay","com.icemobile.lenta.prod","ru.mts.mymts","ru.mts.bank","ru.mts.music.android","ru.tander.magnit","ru.nskes.paysphera","ru.pyaterochka.app.browser","ru.yandex.weatherplugin","ru.yandex.music","com.yandex.bank","ru.crptech.mark","ru.rostel","spam.blocker","re.sova.five","tw.nekomimi.nekogram","ru.nspk.mirpay","ru.fourpda.client","com.github.android","com.vk.vkvideo","com.google.android.apps.photos","com.google.android.apps.docs"],"inXMin":5},"silence":{"enabled":true},"offTime":{},"numberRules":{"rules":[{"id":34,"pattern":"45 71 89 16 01","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":7,"pattern":"73472753665","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":29,"pattern":"7909.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":14,"pattern":"79155130478","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":30,"pattern":"7919.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":6,"pattern":"79196518925","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":26,"pattern":"7925.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":8,"pattern":"79259750866","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":31,"pattern":"7928.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":9,"pattern":"79281778113","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":13,"pattern":"79290297103","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":3,"pattern":"7934.*","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":4,"pattern":"79343334724","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":27,"pattern":"7958.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":11,"pattern":"79586109058","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":25,"pattern":"7981.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":28,"pattern":"7985.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":12,"pattern":"79856999243","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":22,"pattern":"911.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":35,"pattern":"43.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"развод","flagCallSms":{"value":3}},{"id":39,"pattern":"73832021521","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"разводилы","flagCallSms":{"value":3}},{"id":16,"pattern":"74999292929","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"реклама","flagCallSms":{"value":3}},{"id":17,"pattern":"79112723650","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"реклама","flagCallSms":{"value":3}},{"id":18,"pattern":"79119527426","patternFlags":{"value":0},"patternExt

aFlags":{"value":0},"description":"реклама банка","flagCallSms":{"value":3}},{"id":36,"pattern":"45.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":37,"pattern":"61.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":23,"pattern":"7347.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":5,"pattern":"7499.*","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":10,"pattern":"79090872551","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":24,"pattern":"7915.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":21,"pattern":"7918.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":2,"pattern":"7929.*","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":33,"pattern":"7930.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":40,"pattern":"79810269679","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":20,"pattern":"79302203980","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"фин. услуги","flagCallSms":{"value":3}},{"id":15,"pattern":"79812198088","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"финансовые услуги","flagCallSms":{"value":3}},{"id":19,"pattern":"79812409238","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"финансовые услуги","flagCallSms":{"value":3}},{"id":38,"pattern":"994.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"чурки","flagCallSms":{"value":3}}]},"contentRules":{"rules":[{"id":4,"pattern":".*maggamsru.*","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"разводилы","flagCallSms":{"value":3}},{"id":3,"pattern":".*maggamsru","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":2,"pattern":"^maggamsru.*","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":1,"pattern":"maggamsru","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":5,"pattern":"вам","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":6,"pattern":"вас","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":12,"pattern":"вы","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":7,"pattern":"для вас","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":10,"pattern":"сегодня","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":8,"pattern":"специально","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":9,"pattern":"только","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}}]},"quickCopyRules":{}}

**Comment by aj3423** [comment]
I'll try it now.

**Comment by Slawa79** [comment]
> > > Can you upload the text here, in a text file? Maybe remove some sensitive rules, just keep a minimal reproducible configuration.
> > 
> > 
> > Now, just a minute. Only I saved the settings to my telegram and the list of settings was divided into two parts, now I will send both to you.
> 
> {"global":{"enabled":true},"theme":{"isDark":true},"contacts":{"enabled":true},"repeatedCall":{"times":1,"inXMin":5},"dialed":{"enabled":true,"inXDay":3},"recentApps":{"list":["com.vk.mail","com.uma.musicvk","com.whatsapp","com.zvooq.openplay","com.icemobile.lenta.prod","ru.mts.mymts","ru.mts.bank","ru.mts.music.android","ru.tander.magnit","ru.nskes.paysphera","ru.pyaterochka.app.browser","ru.yandex.weatherplugin","ru.yandex.music","com.yandex.bank","ru.crptech.mark","ru.rostel","spam.blocker","re.sova.five","tw.nekomimi.nekogram","ru.nspk.mirpay","ru.fourpda.client","com.github.android","com.vk.vkvideo","com.google.android.apps.photos","com.google.android.apps.docs"],"inXMin":5},"silence":{"enabled":true},"offTime":{},"numberRules":{"rules":[{"id":34,"pattern":"45 71 89 16 01","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":7,"pattern":"73472753665","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":29,"pattern":"7909._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":14,"pattern":"79155130478","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":30,"pattern":"7919._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":6,"pattern":"79196518925","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":26,"pattern":"7925._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":8,"pattern":"79259750866","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":31,"pattern":"7928._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":9,"pattern":"79281778113","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":13,"pattern":"79290297103","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":3,"pattern":"7934._","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":4,"pattern":"79343334724","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":27,"pattern":"7958._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":11,"pattern":"79586109058","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":25,"pattern":"7981._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":28,"pattern":"7985._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":12,"pattern":"79856999243","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"мошенники","flagCallSms":{"value":3}},{"id":22,"pattern":"911._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"мошенники","flagCallSms":{"value":3}},{"id":35,"pattern":"43._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"развод","flagCallSms":{"value":3}},{"id":39,"pattern":"73832021521","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"разводилы","flagCallSms":{"value":3}},{"id":16,"pattern":"74999292929","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"реклама","flagCallSms":{"value":3}},{"id":17,"pattern":"79112723650","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"реклама","flagCallSms":{"value":3}},{"id":18,"pattern":"79119527426","patternFlags":{"value":0},"patternExt
> 
> aFlags":{"value":0},"description":"реклама банка","flagCallSms":{"value":3}},{"id":36,"pattern":"45._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":37,"pattern":"61._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":23,"pattern":"7347._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":5,"pattern":"7499._","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":10,"pattern":"79090872551","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":24,"pattern":"7915._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":21,"pattern":"7918._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":2,"pattern":"7929._","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":33,"pattern":"7930._","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":40,"pattern":"79810269679","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":20,"pattern":"79302203980","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"фин. услуги","flagCallSms":{"value":3}},{"id":15,"pattern":"79812198088","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"финансовые услуги","flagCallSms":{"value":3}},{"id":19,"pattern":"79812409238","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"финансовые услуги","flagCallSms":{"value":3}},{"id":38,"pattern":"994.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"чурки","flagCallSms":{"value":3}}]},"contentRules":{"rules":[{"id":4,"pattern":"._maggamsru._","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"разводилы","flagCallSms":{"value":3}},{"id":3,"pattern":"._maggamsru","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":2,"pattern":"^maggamsru._","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":1,"pattern":"maggamsru","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":5,"pattern":"вам","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":6,"pattern":"вас","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":12,"pattern":"вы","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"спам","flagCallSms":{"value":3}},{"id":7,"pattern":"для вас","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":10,"pattern":"сегодня","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":8,"pattern":"специально","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}},{"id":9,"pattern":"только","patternFlags":{"value":0},"patternExtraFlags":{"value":0},"description":"спам","flagCallSms":{"value":3}}]},"quickCopyRules":{}}

**Comment by Slawa79** [comment]
> I'll try it now.

o.k.

**Comment by aj3423** [comment]
ok, reproduced, fixing now.

**Comment by aj3423** [comment]
Yes, the bug is , when an app is add to the RecentApps and has been uninstalled,  it crashes when trying to show the icon on UI. 
 This image thing may take a while to fix, as a quick workaround, you can remove the app from the setting text, in this text block:
 
   "recentApps": {
    "list": [
.....

I tried your setting without the apps, it works.

**Comment by Slawa79** [comment]
> Yes, the bug is , when an app is add to the RecentApps and has been uninstalled, it crashes when trying to show the icon on UI. This image thing may take a while to fix, as a quick workaround, you can remove the app from the setting text, in this text block:
> 
> "recentApps": { "list": [ .....
> 
> I tried your setting without the apps, it works.

I had an idea to remove all applications from the list, but I do not know where to start and where to finish.

**Comment by aj3423** [comment]
Remove all these package names in the red rectangle, 

![image](https://github.com/aj3423/SpamBlocker/assets/4710875/bd1716cd-7249-45f2-b09b-c3e2a165b387)

After that your setting should look like:

... "recentApps": { "list": [ ], "inXMin": 5 }, ...

**Comment by Slawa79** [comment]
> Remove all these package names in the red rectangle,
> 
> ![изображение](https://private-user-images.githubusercontent.com/4710875/331643497-bd1716cd-7249-45f2-b09b-c3e2a165b387.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTg3MDMsIm5iZiI6MTcxNTk1ODQwMywicGF0aCI6Ii80NzEwODc1LzMzMTY0MzQ5Ny1iZDE3MTZjZC03MjQ5LTQ1ZjItYjA5Yi1jM2UyYTE2NWIzODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMTUwNjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjViOGUyYTE4ZDg5ODJjM2JkMzViMTFlNGUxMTllMjk3NjBjZjA1ZDYwMjBkZjc0ZTI1ZWM1OWFhNzFjYzlkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DQmhS_lwZwJH0RFQugIaaa5wVp5agJFoKtUwPV9PBbY)
> 
> After that your setting should look like:
> 
> ... "recentApps": { "list": [ ], "inXMin": 5 }, ...

Спасибо за помощь, теперь понятно.

**Comment by aj3423** [comment]
This will be fixed in the 1.7, thanks for reporting this.

**Comment by aj3423** [comment]
fixed in the tag latest  .
