### ISSUE TITLE
Regex problem when starting with 0 or +.

### ISSUE THREAD

**Issue by Babag63** [aj3423/SpamBlocker#54]
Hi everyone and thanks for your awesome app !

I'm trying to block all numbers starting with 09 48 which are authorized commercial numbers in France so I tried this in regex : `0948.*` as suggested in the readme.md but when I click on test and try a number such as 09 48 56 45 23, it isn't blocked.

Then I did further investigation and it seems that every regex starting with 0 doesn't work while other numbers do (something like `01.*` or even `0.*` doesn't work).

Finally I thought that I may not need to block numbers beginning with 0948 but +33948 instead as +33 is the local phone indicator for metropolitan France so I put `\+339.*` in regex field and tried the "number" +33934567890 and it still isn't blocked.

I think the app is the problem as I granted all the permission for it and it works for numbers like 1234567890 when I put `12.*` in the regex field and tools like a ![regex visualizor](https://lehollandaisvolant.net/tout/tools/regex) don't show things differently when it starts with `0`, `1` or even a `+`.

I'm a beginner in regex so I really hope I'm not the problem but I'll be glad to help you solve this if I can !

**Comment by aj3423** [comment]
Since v1.5, the matching logic ignores the leading zeroes, and the `+` sign, the regex should be `948.*`, without the leading `0` or `+`.
As described in the balloon tooltip:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/7ea99cda-1da9-49d1-8f57-9c461ae62dab)

Seems I really need to note this in readme, thanks for the feedback.

**Comment by bb1a2** [comment]
@aj3423 Or maybe apply the same stripping rule to the test string

**Comment by aj3423** [comment]
@bb1a2 The stripping of these characters does apply to the test string, I just verified it again and it works.

**Comment by bb1a2** [comment]
Then why is the test call allowed? I am confused.

**Comment by aj3423** [comment]
@bb1a2 Can you show me a test case?  I tested with rule `400.*`, and Tested with number `+400111`/`0400111`, both blocked by this rule.

**Comment by bb1a2** [comment]
I didn't try it myself. I went by the multiple issues raised. Isn't that what issue author is facing?

**Comment by aj3423** [comment]
Oh, now I understand, you mean remove the `0`s in the rules as well.

**Comment by bb1a2** [comment]
Keep them for visuals (not to confuse the first-time user). But for all three (rule, test, actual call), apply the same treatment.

**Comment by aj3423** [comment]
That's a good idea, thanks. I think it's better to solve it in the first place when editing rules, if there is leading `0` or `+`, show some yellow warning below.

**Comment by bb1a2** [comment]
That can work.

**Comment by Babag63** [comment]
Thanks for all your answers and the solutions proposed.
Really sorry for not having seen the balloon tooltip.
So to match a number starting with 0948 or +33948 finally I think I'll to do something like `(33|)948.*` as the 0 and + will be skipped anyways (if I understood your messages correctly).
Thanks again for your responsiveness.

**Comment by aj3423** [comment]
`(33|)948.*` should work.
New error prompt has been added in tag latest.
