### ISSUE TITLE
feature request - enable/disable SpamBlocker from quicktile

### ISSUE THREAD

**Issue by redcat42** [aj3423/SpamBlocker#56]
would be great if one could enable/disable SpamBlocker using quicktile

thanks

**Comment by aj3423** [comment]
good idea, will implement.

**Comment by aj3423** [comment]
Supported in the latest tag.

**Comment by redcat42** [comment]
amazing work 👍

**Comment by redcat42** [comment]
> Supported in the latest tag.

it does not seem to be working for me on android 14 :(

it does not switch SpamBlocker off or on

**Comment by aj3423** [comment]
Really? I've tested it on emulator and real phone, both running android 14, both work fine.

**Comment by redcat42** [comment]
> Really? I've tested it on emulator and real phone, both running android 14, both work fine.

yup, if I keep the app open and toggle the tile, nothing happens in the app, will restart the phone and try

**Comment by aj3423** [comment]
Maybe the UI is not get refreshed when it's enable/disabled from the tile, can you try to switch to phone tab and switch back to setting tab, to see if it changes? I'll fix this.

**Comment by redcat42** [comment]
> Maybe the UI is not get refreshed when it's enable/disabled from the tile, can you try to restart the app to see if it works? I'll fix this.

you are absolutely right, it was just not getting refreshed and the button for enabled is not getting toggled as well, but it is working 


https://github.com/aj3423/SpamBlocker/assets/113236440/11c0c302-8f95-436f-a2b3-54f116af50bf

**Comment by aj3423** [comment]
Fixed in the tag latest, now the UI is always synchronized with the tile clicking.

**Comment by redcat42** [comment]
> Fixed in the tag latest, now the UI is always synchronized with the tile clicking.

nice, just installed and tested, perfect 👍
