### ISSUE TITLE
Possibility to select filtering with SIM card/Phone Number selection on dual/multiple SIM devices

### ISSUE THREAD

**Issue by djelloul78** [aj3423/SpamBlocker#59]
Bonjour

I was thinking if it could be possible to detect the phone being able to use 1 or multiple SIM cards, and then apply a new selector for each filtering rule pattern to add its behaviour on a specific SIM card in particular.

This way your app will be able to let users filters unwanted call on a specific SIM but not on the others.

What is your opinion? 

Thank you for your attention.

**Comment by aj3423** [comment]
Can you show me a use case? Why is a call considered spam on SIM 1 but not on SIM 2?

**Comment by djelloul78** [comment]
I was sure my request will require some context in order to be more accurate! 

First, thank you for replying so fast as usual.

Let's say you have a professional and a personal SIM card embedded in a same device having dual SIM ability. 
You could consider receiving professional call in your personal SIM a sort of spam.
Having a pattern filtered call/SMS on personal SIM based on companies phone definition but allowing them in professional SIM or vice-versa will help the device user to not be annoyed by not properly oriented call/SMS.

I know it's possible to create a black list on the contact app of some phones and activate a call/SMS filtering based on specific hours/days and also between each SIM card, but this feature is present only on some phone suppliers that have teams of devs engaged in customer satisfaction with a sense of service open to customizing.

I don't know about you, but I had lots ofdual SIM phones from many different brands and all doesn't manage such type of feature the same way or manage it at all.
Having an app that could centralise a proper way to have this feature with the alarm existing granularity will be a great thing. 

However, I recognise that this evolution request seems more of a personal use case than a globally useful one now that I've written it properly...

I'll totally understand that you don't want to give this request a go.

**Comment by AntBasP** [comment]
This would be a wonderful feature to block all calls on the work sim during the off hours of a day. It would help disconnect from work for those of us with creepy bosses that keep trying to contact us after work.

I know there's a work profile on android that does that for apps, but I'm not aware of anything that can do the same for calls.

**Comment by aj3423** [comment]
Sounds reasonable. Is it enough to only support this "per SIM card" for the regex rules? Like this:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/83999ce3-b887-4ae8-bba7-0a9d219fd5cb)

**Comment by djelloul78** [comment]
It seems a good GUI proposal, however, if we take AntBasp's remark, this has to also be done in other parameters.
For example deciding to apply an off time on a SIM but not the other, or silence calls on a SIM but not the other, etc...

Maybe it will be more efficient to have these global options being set per rules definition instead of globally applied in the app. 

This will let the user do whatever he wants the way he want, but this will probably requires a major rework on your SW logic and this maybe isn't a priority for now.

**Comment by aj3423** [comment]
Yeah, another approach would be adding a new combobox at the top for choosing SIM cards, it's hidden when there is only 1 SIM card, when there are multiple cards, the combo would look like:

- Default
- 11111111 (SIM 1)  (maybe add a switchbox here for Enable/Disable this profile)
- 2222222 (SIM 2)

When a SIM profile is selected, the rest of UI remains the same, but it only shows settings for that profile, so it would work for everyone:
- For most users, they only need to set the Default profile.
- You can enable the work SIM profile, maybe clone the Default profile to it via "backup & restore" and then add some more rules.
- For AntBasP's boss, I'll add a "Exclusive" option to the feature "Off Time", currently it's "Inclusive" that always allow calls during a period, "Excusive" would be always reject.

**Comment by djelloul78** [comment]
I understand better now. 
Thank you for the clarification. 

I'll be ready to test and I have 2 dual SIM phones available if you need (Realme X2 Pro & Samsung Galaxy Fold 5).
Even a tablet with dual SIM support...

By the way, do you want me to translate the GUI strings in French?

If I'm not wrong, it's a matter of translating 4 XML files.

If yes, I'll have to put out mice and keyboard from hibernation...
I haven't used them since a while!

**Comment by djelloul78** [comment]
Understood and thank you for your confidence in my English writing level!

I'll take a look on what the AI result will be and take the role of a French language reviewer then.

Enough off-topic from me. 
I'll follow next app releases.

Thank you for your valuable attention.

**Comment by aj3423** [comment]
I just added French language support in the latest tag, maybe take a look, how good/bad is it.

**Comment by djelloul78** [comment]
I've just checked the French translation, and it isn't that bad.
However it's sometimes confusing with some words that could have a double comprehension.
It's not a blocking point but knowing how French people can easily complain on details, I'll share some correction. 
How do you want me to proceed? 
Open a new topic with correction proposal or corrected French XML files?

By the way, French language makes some parameters longer to be written making some touch action hidden on small phone screens.
I think I'll open another topic about this if you're OK with that.

**Comment by aj3423** [comment]
I don't think it's ideal to correct the AI generated translation, because next time I regenerate it with AI, it will be overwritten. I think it's better to use some other English words, that won't lead to misleading translation. Maybe show me those misleading places.

**Comment by aj3423** [comment]
I think when this app becomes stable and there's no more features to add, I wouldn't use AI translation anymore, it's just a temporary workaround.

**Comment by djelloul78** [comment]
OK.
Then we'll wait for stability before making your app more "Française" friendly.

**Comment by aj3423** [comment]
I trusted AI about how to get the SIM number from an incoming call, I tried 4 different AI, they all showed me very clear answer, then I started implementing. Now the coding is finished, UI/configuration/database/logic have been upgraded to supported multi-sim, but...
It turns out that, as a call ID app, it not possible to get the SIM information from incoming calls. :shit::shit::shit: I tried an app called "Dual SIM Call blocker - Hush", it doesn't work at all.

If anyone knows any app that is capable of blocking calls by SIM, please let me know, I'll try more apps later.

**Comment by djelloul78** [comment]
Bonjour,

I remember having used this app that had ability to apply call filtering with SIM selection: 
https://play.google.com/store/apps/details?id=com.mglab.scm

I also remember it wasn't very efficient due to its limited mask/filtering aspect. 
It was also annoying with regular ads, interesting features only available in paid pro version, and what made me dressed my hair straight, mandatory categorize, qualify and share your filtering masks to supply a database to help everybody using the app. 

I understand the good will behind this, but some filters does contain private data that had nothing to do out of user device, and I don't like the "Mandatory by default" approach.
I understood that it was possible to deactivate this specific aspect but the number of parameters wasn't that easy to check about that and my mind was already dropping the idea to keep this app on the phone...

However, you'll see that the app is full of smart ideas that you had already implemented in yours or going to, but I think the dev behind it had lost himself in complexity making it usable only by the braves...

I'll be happy to have your own opinion about it.

**Comment by aj3423** [comment]
Thanks, 
I tried to analyze this com.mglab.scm, the pro version, maybe it's already cracked because I don't see any ads or limitations, anyway, this is how it works:
1. it monitors call state change using a `Receiver`, if there is a call start ringing, it would know
2. when there is an incoming call, it doesn't block the call, it let the call ring
3. the ringing will be immediately captured by the monitor, then hang it immediately

There are pros and cons with this `Receiver`:
Pros:
1. In the `Receiver`, it's possible to get which sim slot is being called on. 

Cons:
1.  When the app is killed, maybe killed by android automatically, the `Receiver` is also killed. So you would have to keep this app running to make it work. I've seen such settings that allows an app to always run, it seems possible but it would consume more battery.
2. There is a delay between the start ringing and being hung up, very short but noticeable, the lock screen will be turned on.

I'd rather not use this solution, maybe I've been going in the wrong direction, there is no need to support dual SIM at all, because of the Cons, and it does make the UI more complex, you would need to maintain two profiles. 

The personal/work issue can be solved by adding two new features, for example:
1. support "Time Schedule" in the regex rule, the rule only works during this time period. It can be scheduled like X:00-Y:00 from Monday to Friday
2. support "Reject Type" in the regex rule, so you can set this rule to `Silence` for boss

It would be a lot more flexible than the dual sim solution, How do you think?

**Comment by AntBasP** [comment]
Sounds good given the limitations.

**Comment by djelloul78** [comment]
It seems using `Receiver` add much more cons than pros...
I join AntBasP opinion and your arguments are clear. 

We maybe made a mistake by focusing on multi profile management just for SIM recognition.
The goal of this app is to filter calls with a set of rules whatever the incoming source. 
Your proposal won't cover one specific point I have in mind, but it covers million of other needs so that is fine. 

Thanks for staying cold in your thinking.
I really appreciate how you're open to ideas and how you consider arguments of others.

**Comment by aj3423** [comment]
It's done in the latest tag:
- Time Schedule per rule
- Block Type per rule

**Comment by aj3423** [comment]
It's now supported: https://github.com/aj3423/SpamBlocker/issues/169#issuecomment-3617874545

**Comment by djelloul78** [comment]
I'm surprised you were still keeping track on this opened issue!
I'll test it coming Monday to make some filtering with Office calls as I'm now literally spammed by foreign dev teams after 8:30PM, that I consider way out of respectable working hours!

Whatever the result, you stay one of the most respectful developer in my eye as you still keep the app up to date, make it evolve continuously, optimized in memory occupation and always open to check issues or suggestion. 

You did and still do a great job!
Thank you very much, sincerely.
