### ISSUE TITLE
this app IS great 

### ISSUE THREAD

**Issue by userx77** [aj3423/SpamBlocker#61]
First, thanks for finally showing that you are developing a modern SMS and call block application. I can think of a development idea that might be possible? Offtime days of the week rules? A more precise adjustment option for phone contacts rules?

**Comment by aj3423** [comment]
I plan to refactor the OffTime, I'll take this "schedule by weekday" into account, just like the alarm app.

> A more precise adjustment option for phone contacts rules?

Not sure what this means, can you elaborate more?

**Comment by userx77** [comment]
I mean the separate setting of a particular contact. E.g. "Silent", Block or "Not blocked" for a certain time of the day. ☺️ Sorry  I can't explain that, but the function is familiar in older call blocker softwares..

25. toukok. 2024 klo 13.45 - lähettäjä ***@***.***:

**Comment by aj3423** [comment]
I see, this can be done by adding a "time period" option to the number rule, the rule would only apply within the time period.  Then you can set a rule for that particular contact number.

**Comment by aj3423** [comment]
It's possible now, two features are added in the latest tag:

- Time Schedule per rule
- Block Type per rule
