### ISSUE TITLE
[Feature request] Add option to delete SMS

### ISSUE THREAD

**Issue by CuriousApe2020** [aj3423/SpamBlocker#62]
I am trying to set the App up for an elderly person, and would really like to just delete all SMS that do not come from the phones contcts. Woud this be possible to implement?

**Comment by aj3423** [comment]
Yeah, enable the Contact (Inclusive) and set a SMS Content Rule `.*` (blacklist), all SMS messages from non-contacts will be blocked.

**Comment by CuriousApe2020** [comment]
Ok, thanks for the quick answer.
