### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by EthicalGhost** [aj3423/SpamBlocker#65]
I could not figure out how to do my setup.

I want to block all calls for a specific timespan (from 8.00 to 11.00, for example).
But when unblocked, I want to block all calls except 2 phone numbers that starts with "+" (+12345 for example).

Please help me to set this up.

**Comment by aj3423** [comment]
This is not possible with v1.8, but the latest tag has just introduced a new feature, time constraint for regex rule,  now you can do that with two rules: 
1. blacklist rule `.*` within `8:00-11:00`
2. whitelist rule `12345` with higher priority

Please note the leading `+` isn't necessary and should be ignored, that is explained in help balloon of "Number Rules":
![Screenshot_20240602-152221_SpamBlocker.png](https://github.com/aj3423/SpamBlocker/assets/4710875/46b0db71-98e7-40bd-bd3d-566145b9a433)

**Comment by EthicalGhost** [comment]
> 1. blacklist rule .* within 8:00-11:00
> 2. whitelist rule 12345 with higher priority

It is working only when I am using the same timeframe for both block and white lists. How to block all calls for the rest of the time?
I tried to fix it with Off Time but did not work.
I also tried to blacklist .* for all the time, and then whitelisted two numbers for a scheduled time frame on all weekdays, but that did not work either. Will you please fix that?

**Comment by aj3423** [comment]
It's based on priority, what priority do you set for these rules?

**Comment by EthicalGhost** [comment]
Did not know that. Now it's working fine. I set priority of whitelist to 20. 
Thank you so much, sir.
