### ISSUE TITLE
Porting app to Android 9 ?

### ISSUE THREAD

**Issue by Xalares** [aj3423/SpamBlocker#67]
Hi everybody, I'm greatly interested in your app, but unfortunately my phone is using Android 9. Is any project to port the app to Android 9 ?

**Comment by aj3423** [comment]
It's not possible because Android 9 doesn't support call screening service, only the default call app is capable of blocking calls. https://github.com/aj3423/SpamBlocker/issues/38

**Comment by Xalares** [comment]
Ok, but I don't understand how this app works then https://play.google.com/store/apps/details?id=callfilter.app, because it's not my default phone app and it works well. But unfortunately it's not open source ;)

**Comment by Xalares** [comment]
Yes indeed, I just checked the app I use, and indeed it's my default call app, I thought it wasn't, thanks for your answer !
