### ISSUE TITLE
Error after updating to version 1.9      android 13

### ISSUE THREAD

**Issue by Slawa79** [aj3423/SpamBlocker#69]
https://github.com/aj3423/SpamBlocker/assets/23304238/0da9a728-e6c8-445a-8e62-752765b48259

After upgrading to version 1.9, the application does not start  crashes with an error .  Reinstalling the application does not help, the application does not start either

**Comment by aj3423** [comment]
You mean it even crashes on fresh install? I can't reproduce that, tried on Android 13 emulator

https://github.com/aj3423/SpamBlocker/assets/4710875/56395932-3e4e-4593-b6eb-76e79d729125

Can you connect the phone to a PC and capture a log? I'll show you the steps.

**Comment by Slawa79** [comment]
> Вы имеете в виду, что он вылетает даже при новой установке? Я не могу воспроизвести это, пробовал на эмуляторе Android 13
> 
>  nocrash.mp4 
> Можете ли вы подключить телефон к ПК и записать журнал? Я покажу вам шаги.

Yes, even after reinstalling the app, it doesn't run on my phone.   
  Unfortunately I don't have a computer 🤷

**Comment by aj3423** [comment]
Now there is crash report in the latest tag, looks like
![crash_report.png](https://github.com/aj3423/SpamBlocker/assets/4710875/05d57b85-5779-4c72-a61e-2ff20e3a1e52)

Please copy the content here.

**Comment by aj3423** [comment]
Maybe try the latest v1.1.1

**Comment by Slawa79** [comment]
> Maybe try the latest v1.1. Hi. Yes, this version works fine, there are no errors. Thank you for quickly correcting the error
