### ISSUE TITLE
Improve Notification Channels

### ISSUE THREAD

**Issue by newhinton** [aj3423/SpamBlocker#70]
Currently, the notification channels are nondescriptive.

Preferably they would be per feature, eg. blocked sms notifications, blocked calls, silenced calls, etc.

The reasoning behind this is that i dont want to be notified twice about sms. Currently i get both a notification by spamblock and my sms app, even though it was allowed. With a better notification system, this would be easily achieved. (Maybe add this as a native option to the app aswell, to disable sms checks?)

Otherwise this app is great, especially for calls. Thanks!

**Comment by aj3423** [comment]
The ancient version used `NOTIFICATION_CHANNEL_1 - 5`, if you still see them, plz uninstall and reinstall the app to get rid of them, upgrading won't make them disappear.

In latest version they are `None`, `StatusBar+Shade`, etc, they are applied for both Call/SMS, so they can't be renamed to "blocked sms notifications, blocked calls, silenced calls, etc"

>  Currently i get both a notification by spamblock and my sms app
This app is supposed to fully take over the notification of the default SMS app, you can disable the notification of your default SMS app, no need to manipulate the notification channels.

I've thought about auto-disabling the notification of default SMS app, but it would require 1 more permission, so I gave up, I'll try to add some tip about this.

**Comment by newhinton** [comment]
> The ancient version used NOTIFICATION_CHANNEL_1 - 5, if you still see them, plz uninstall and reinstall the app to get rid of them, upgrading won't make them disappear.

No, it's the other ones.


> In latest version they are None, StatusBar+Shade, etc

This is kinda the problem, what does that even mean? Ususally the channel names are descriptive of their function. It seems the names are correlated to their "visibility". That is usually inadvisable, as there are better ways to manage that.

> This app is supposed to fully take over the notification of the default SMS app, you can disable the notification of your default SMS app, no need to manipulate the notification channels.

I would rather not do that, my default sms app is just fine.

**Comment by aj3423** [comment]
I see, actually you want to disable the rules for SMS, you can uncheck this checkbox:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/446bc6bc-7024-4c1c-a4fa-32021d59b024)
Then the rule will only work for calls.

**Comment by newhinton** [comment]
I dont have any rules :D 

I use this app to block unknown numbers, because either the caller is in my contacts, or it's a spam call. 

Gladly, i don't get any sms-based spam, so my default app works fine, that's why i would like to disable sms-notifications from your app.

Having seperate channels for calls&sms would fit there perfectly!

If you like, i could take a look at your notification-implementation and give some ideas on how to improve the notification-ux.

**Comment by newhinton** [comment]
For now i will check if it is enough to remove the sms-permission.

**Comment by aj3423** [comment]
Yeah, remove the sms permission would do, an alternative way would be: add a rule that applies for all SMS messages, with higher priority, set notification type to "None" to not show any notifications, like:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/160404c4-4605-4642-9edc-72880af0345a)

**Comment by aj3423** [comment]
Now in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/9422556934, it supports enabling call/sms individually:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/18952e48-4be4-479d-b3ca-9ec6ef658524)
