### ISSUE TITLE
Dual SIM support 

### ISSUE THREAD

**Issue by 123unix** [aj3423/SpamBlocker#72]
Hello! Would you please consider adding dual SIM support to filter rules?

Possible scenario:

1. SIM 1 accepts all calls
2. SIM 2 accepts calls from the Contacts only

**Comment by aj3423** [comment]
Technically, it's not possible to access the SIM information within CallScreeningService, which is used by this app. While some apps use CallStateReceiver to block calls, it provides access to the SIM slot number. However, the call must pass the Service to trigger the Receiver, which means the lockscreen will be turned on, preventing silent call rejection or silencing(ringing at background).

The approach would significantly increase complexity (code, UI, user experience), and offers more Cons than Pros. Therefore, I prefer not support it yet.

There must be a reason for google to restrict SIM info in CallScreeningService, I'll try to submit a feature request to them anyway. Once supported, this use case can be easily solved with one regex rule.

**Comment by aj3423** [comment]
It's now supported: https://github.com/aj3423/SpamBlocker/issues/169#issuecomment-3617874545
