### ISSUE TITLE
Meaning of "Include Unverified" for STIR Attestation?

### ISSUE THREAD

**Issue by mohammedthejihadist** [aj3423/SpamBlocker#73]
It is not clear to me what exactly "Include Unverified" includes unverified calls for. Does it include the calls in being filtered or does it include the calls in being allowed?

To ask a different way, if I turn on STIR and set it to exclusive and don't want unverified calls getting in, what should I set "Include Unverified" to?

**Comment by aj3423** [comment]
>  if I turn on STIR and set it to exclusive and don't want unverified calls getting in, what should I set "Include Unverified" 

You should check this "Include Unverified".

related code:
https://github.com/aj3423/SpamBlocker/blob/d8cb21b4968d0455df216cb2088164a88cdb398f/app/src/main/java/spam/blocker/service/Checker.kt#L101

I'll improve the help tip a bit.
