### ISSUE TITLE
Please, add Ukrainian translate (ua)

### ISSUE THREAD

**Issue by vanek49** [aj3423/SpamBlocker#78]
Hi, please, add Ukrainian translate.
Thanks.

**Comment by aj3423** [comment]
Done in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/9539514163

**Comment by aj3423** [comment]
Actually the language code is `uk`, not `ua`. 
I was trying to upload to google play, but it reports unknown language `ua`, in the report there's a link for all supported languages :

> Type: language
> Subtag: uk
> Description: Ukrainian

https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
