### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by Umotas** [aj3423/SpamBlocker#8]
Do you have plans to add import/export black-white lists? (f.ex. I have 2000 blocked numbers +10 in regexp records.)

Allow Contacts - Is allowed only Contacts? Will any other numbers blocked?
Allow hidden numbers? 
Allow any numbers?
If I'd like to add some simple number: +43987654321 (without regex).
`I added "\+43987654321" - Is it working in this way?`

**Comment by aj3423** [comment]
> Do you have plans to add import/export black-white lists? (f.ex. I have 2000 blocked numbers +10 in regexp records.)

Currently no plan for importing from other apps, the point of this app is to use very few rules to block all spam. You can keep those 2000 numbers blacklisted in the stock call app, it should work along with this, this app checks first, then the stock app.

> Allow Contacts - Is allowed only Contacts? Will any other numbers blocked?

A number that isn't contact will be checked by other rules, all rules will be checked until a match is found. Contact checking is prior to the regex rules.

> Allow hidden numbers?

What are hidden numbers?

> Allow any numbers?

Try this regex: `.*`, which means any content.

> If I'd like to add some simple number: +43987654321 (without regex).

The regex also supports exact string, for example regex "111" matches the exact number "111", other strings like "1111" or "21113" won't match. Special characters like `+`, `-` and spaces are removed before comparing, just add it as "43987654321".  I'll add these notes to Readme.

**Comment by aj3423** [comment]
Done with tag v1.3
