### ISSUE TITLE
Feature Request (Repeated Call & Off Time toogle in Regex Block)

### ISSUE THREAD

**Issue by roadrunn-er** [aj3423/SpamBlocker#80]
Hi there, 

Firstly I want to thank you for this useful app. It's been great, however there is something that I'm encountering. So. I've done an "Inclusive Block" for blocking a specific range of numbers and then I've done a block with ".*" to block all calls. 

One might ask why, well I want to block all unknown calls but still allow repeated calls and off time which works great, but there are some range of numbers that I want to block and don't want the repeated calls or off time rule to apply to those particular number block rules.
I might've made it sound confusing but what I mean is, there are some numbers or range of numbers that no matter how many time they call or even if it's off time, I still want them to be blocked and not allow in any case.

Now currently what I can think of is having a toggle to allow or disallow "global repeated calls and off time rule" for a specific block rule, something like "allow repeated calls" & "allow off time" in a particular number rule.

again thanks for this great app.

**Comment by aj3423** [comment]
The whitelist filters like RepeatedCall and OffTime have priority as 10(as described in the balloon tip), you can set rules with higher priority to override them.

For example, a blacklist rule `123.*`(priority 100) would always block numbers start with 123 regardless of how many times they repeat or whether it's OffTime.

Btw, the global OffTime can also be overridden by per rule TimeSchedule, the global setting is just for convenience.

**Comment by roadrunn-er** [comment]
That's great and I see it's even mentioned in the FAQ, didn't saw it before my bad. Thanks for the quick response :)

**Comment by roadrunn-er** [comment]
That's great and I see it's even mentioned in the FAQ, didn't saw it before my bad. Thanks for the quick response :)

**Comment by aj3423** [comment]
I just added this to FAQ :)

**Comment by polin79** [comment]
Hi,
In my case I want to have in whitelist all my contacts and numbers starting with 0039017, and to block all the other numbers. I tried with rules as per the attachment, but I don't understand why the rule with .* for all numbers with priority 10 runs before the rule 0039017.* with priority 0. Could you explain me how to proceed? 

Thanks
Paolo
![Screenshot_20241025-130110_SpamBlocker](https://github.com/user-attachments/assets/09b971fa-d8fe-474b-ac0d-506ca19b0d2a)

**Comment by aj3423** [comment]
@polin79 Rule with higher priority will be checked first.

>  I want to have in whitelist all my contacts and numbers starting with 0039017

1. Enable the "Contacts" and set it to Inclusive, as you've already done. (its priority is 10)
2. Add a whitelist rule `0039017.*` with priority 1
3. Add a blacklist rule `.*` with priority 0

So based on the priority, the checking order would be 1 -> 2 -> 3, which means:
allow if it's contact -> allow if it's 0039... -> block all other numbers

And plz create a new issue if there's any further question.

**Comment by polin79** [comment]
``Hi,
Thank you very very much for the support: so If I understand priority 10 is higher than priority with lower number. I thought on the contrary: that was the reason of the problem. Now I have added other whitelist rules in addition to contacts and 0039017.*
How many rules does the app support? If inclusive contacts is 10 I think only 10 for rules with lower priority.

Thanks
Paolo
![Screenshot_20241025-134908_SpamBlocker](https://github.com/user-attachments/assets/cb951176-420a-4ddb-a3e2-45a608e1285c)

**Comment by aj3423** [comment]
You don't have to use different priorities for those whitelist rules, I used priority 1 in the previous post just for demonstration. You can use 1 for all whitelist rules, or even 999, as long as they override the blacklist priority. The point is to allow the call, it doesn't really matter which rule allowed it.

**Comment by polin79** [comment]
Ok clear, thanks for all

**Comment by polin79** [comment]
> You don't have to use different priorities for those whitelist rules, I used priority 1 in the previous post just for demonstration. You can use 1 for all whitelist rules, or even 999, as long as they override the blacklist priority. The point is to allow the call, it doesn't really matter which rule allowed it.

Could you kindly insert these instructions in the FAQ?

**Comment by aj3423** [comment]
> Could you kindly insert these instructions in the FAQ?

Good suggestion, FAQ updated.

**Comment by polin79** [comment]
Thank you

**Comment by polin79** [comment]
Very helpful. Now it's more clear. Many thanks
