### ISSUE TITLE
Not working on GrapheneOS

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [aj3423/SpamBlocker#87]
[GrapheneOS](https://grapheneos.org/) It triggered a block in the SpamBlocker app block test.

But the fact that it called me didn't trigger the intercept?

How to block numbers starting with 021 ? 
![Screenshot_20240625-155026](https://github.com/aj3423/SpamBlocker/assets/169121286/ba74ce24-9961-4bd3-b2bc-f2eae280fb8f)

Maybe the app needs Accessibility  permissions.

**Comment by aj3423** [comment]
Did you see this popup dialog on first launch? (it means the OS supports call screening service)
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/2a225c0a-ca0a-40a6-96c4-be29cddd1f4f)

Is the call icon green? (it means the app is enabled as the default caller ID app)
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/c3659f98-e66c-41bc-8cc3-e72e0f1e5251)

**Comment by Zig-Rust-Odin** [comment]
Yes, I did, but it still doesn't work.  
![Screenshot_20240625-224022](https://github.com/aj3423/SpamBlocker/assets/169121286/fcff3271-13d4-44f1-91c9-bccc06c743e4)

**Comment by Zig-Rust-Odin** [comment]
![Uploading Screenshot_20240625-225116.png…]()

**Comment by Zig-Rust-Odin** [comment]
Yes, I did, but it still doesn't work.

![Screenshot_20240625-224022](https://github.com/aj3423/SpamBlocker/assets/169121286/830f1be8-9404-4529-be8c-2e80e7b41e44)

![Screenshot_20240625-225116](https://github.com/aj3423/SpamBlocker/assets/169121286/a727459a-1d80-4f68-bef9-45655c4a7505)

**Comment by aj3423** [comment]
So it's just how to set the rule, I thought you've set it correctly since it works when testing.

> How to block numbers starting with 021 ?

You need `21.*`, the leading 0 is ignored,

**Comment by Zig-Rust-Odin** [comment]
You still haven't solved the problem of not working on GrapheneOS
I should say that SpamBlocker, the whole program, doesn't work. It doesn't block any numbers.

**Comment by aj3423** [comment]
I'll try to install GrapheneOS.

**Comment by AustralEpitech** [comment]
I works perfectly fine for me on a Pixel 7a with GrapheneOS build 2024062000
Are you sure you set it up correctly?

Here is ny config (just change the rules):
```json
{"global":{"enabled":true,"callEnabled":true},"theme":{"isDark":true},"language":{"lang":"en"},"contacts":{"enabled":true},"stir":{},"repeatedCall":{"times":1,"inXMin":5},"dialed":{"inXDay":3},"recentApps":{"inXMin":5},"blockType":{},"offTime":{},"numberRules":{"rules":[{"id":2,"pattern":"33525.*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"flagCallSms":{"value":3},"schedule":",00:00-00:00,false"},{"id":3,"pattern":"3356[8-9].*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"flagCallSms":{"value":3},"schedule":",00:00-00:00,false"},{"id":1,"pattern":"33[^5-7].*","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"flagCallSms":{"value":3},"schedule":",00:00-00:00,false"}]},"contentRules":{},"quickCopyRules":{}}
```

![Screenshot_20240627-085934](https://github.com/aj3423/SpamBlocker/assets/71961651/27a14874-972b-4d4c-a6f5-6e5d57cc3d8f)
![Screenshot_20240627-085944](https://github.com/aj3423/SpamBlocker/assets/71961651/9706213e-2059-46e8-a580-2d33fd9a09f8)
![Screenshot_20240627-090057](https://github.com/aj3423/SpamBlocker/assets/71961651/894b1460-7d73-4a6b-baf9-9de25b48fc65)
![Screenshot_20240627-090113](https://github.com/aj3423/SpamBlocker/assets/71961651/d0d09d48-bf93-4a2d-b497-37e535579e6f)

**Comment by aj3423** [comment]
@AustralEpitech Thanks for confirming this.

@Zig-Rust-Odin  Turns out that I don't have the environment to test the GrapheneOS, it only works with Pixel series and the emulator build doesn't work on Wayland. Just to confirm, do you see any log in the call history page?
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/9bd55165-0e93-4270-b552-7ce58e0e71a4)

**Comment by Zig-Rust-Odin** [comment]
We've found the cause. It's a backstage kill death.
SpamBlocker should keep waking up in the background, and start up on boot.

**Comment by Zig-Rust-Odin** [comment]
## Slide up and you're clean.
![Screenshot_20240627-194629](https://github.com/aj3423/SpamBlocker/assets/169121286/dad7132c-058c-47ca-886e-afaf541d87c2)

### ## I've enabled it and I'm still getting this background cleanup issue ##
![Screenshot_20240627-194811](https://github.com/aj3423/SpamBlocker/assets/169121286/0d956bf0-ab80-4fed-861f-7aaf636bc498)

**Comment by aj3423** [comment]
> We've found the cause. It's a backstage kill death. SpamBlocker should keep waking up in the background, and start up on boot.

This battery setting only affects SMS messages, as described in the [FAQ](https://github.com/aj3423/SpamBlocker/#faq--troubleshooting).
But for calls, it uses CallScreeningService which is not affected by this battery option, it's a background service that will always be invoked on incoming calls. 
Is the call blocking actually working after allowing the background usage?

**Comment by Zig-Rust-Odin** [comment]
@aj3423 add @cretaceous:matrix.org I'll send you a video, the app doesn't work at all.

**Comment by aj3423** [comment]
@Zig-Rust-Odin I understand somehow it's not working, if possible, please connect the phone to a PC and capture some adb log:
- open a terminal and type `adb logcat | ag 111111`
- make a phone call to it
- see if there is any output, it should be something like:
> ... new call from: .....

**Comment by Zig-Rust-Odin** [comment]
> adb logcat | ag 111111
This command does not exist

**Comment by aj3423** [comment]
Please download the adb from https://developer.android.com/tools/releases/platform-tools
And enable "usb debugging" in developer options.

**Comment by Zig-Rust-Odin** [comment]
There's too many logs. The terminal can't get all the text.
[adb.zip](https://github.com/user-attachments/files/16015826/adb.zip)

**Comment by Sjano** [comment]
This works perfectly on grapheneOS. Needs to be installed on owner user, I think. As calls are routed trough there. Only enable the permissions.

**Comment by aj3423** [comment]
From the log, that call didn't trigger the service, something strange in the log:

> Telecom : CallScreeningServiceHelper: com.android.dialer has no call screening service defined.: ...
> Telecom : CallScreeningServiceFilter: Call screening service binding failed.: ...
> Telecom : IncomingCallFilterGraph: Filter com.android.server.telecom.callfiltering.CallFilter@357b2b8 done, result: [Allow, logged, notified].: ...
> Telecom : CallsManager: setCallState NEW -> RINGING...

Seems that the system didn't find any registered caller ID app, but actually you have registered it, very strange. 

@Zig-Rust-Odin, as mentioned by @Sjano, are you using any sandbox? Or something like personal/work profile?

**Comment by Zig-Rust-Odin** [comment]
> From the log, that call didn't trigger the service, something strange in the log:
> 
> > Telecom : CallScreeningServiceHelper: com.android.dialer has no call screening service defined.: ...
> > Telecom : CallScreeningServiceFilter: Call screening service binding failed.: ...
> > Telecom : IncomingCallFilterGraph: Filter com.android.server.telecom.callfiltering.CallFilter@357b2b8 done, result: [Allow, logged, notified].: ...
> > Telecom : CallsManager: setCallState NEW -> RINGING...
> 
> Seems that the system didn't find any registered caller ID app, but actually you have registered it, very strange.
> 
> @Zig-Rust-Odin, as mentioned by @Sjano, are you using any sandbox? Or something like personal/work profile?


Yes, I have all my apps installed in another GrapheneOS > Multiple Users working profile.

I hardly ever switch to the GrapheneOS admin except to update the system.

**Comment by aj3423** [comment]
I just tried it in work profile, it can be registered as the caller ID app but it doesn't work at all.
I guess you have to install this app in main profile, unless you find a way to handle incoming calls with the dialer in work profile(not sure if it would work)

**Comment by Sjano** [comment]
Yeah. That might be an issue then.I have it on my admin profile and it works. Even if you enabled SMS and calling on the other profiles it might not work

**Comment by SirTeddyBear** [comment]
Last graphene update (Android 15), using admin profile, the application stopped working. I will try to reinstall it

**Comment by aj3423** [comment]
It's weird that I haven't reopened this issue, it's now open and there is no "reopened by" tag. 

@SirTeddyBear It works on Android 15 emulator, plz fire a new issue if it's still not working, closing this.
