### ISSUE TITLE
Regex numéro non français

### ISSUE THREAD

**Issue by Paul75** [aj3423/SpamBlocker#90]
Bonjour

J'essaye de rajouter une règle qui interdit les numéros qui ne sont pas français mais cela ne semble pas marcher.

Voila le regex :

^(?!(\+33|0033|0)(?:[1-9])\d{8}$).*$

Merci

**Comment by Sjano** [comment]
Just do:
33.*
Or
33.{8,}

33.=+33|0033|033

**Comment by Paul75** [comment]
I do like you and if test with number +447362040858 it pass....

**Comment by Paul75** [comment]
![](https://i.imgur.com/9O1VUmm.jpeg)

**Comment by aj3423** [comment]
@Paul75 Can you export your setting through "Backup and Restore" and paste here?

**Comment by Paul75** [comment]
{"global":{"enabled":true,"callEnabled":true,"smsEnabled":true},"theme":{},"language":{"lang":"fr"},"contacts":{"enabled":true},"stir":{"enabled":true},"repeatedCall":{"times":1,"inXMin":5},"dialed":{"inXDay":3},"recentApps":{"inXMin":5},"blockType":{},"offTime":{},"numberRules":{"rules":[{"id":1,"pattern":"33.{8,}","patternFlags":{"value":5},"patternExtraFlags":{"value":5},"description":"Hors francais","flagCallSms":{"value":3},"schedule":",00:00-00:00,false"}]},"contentRules":{},"quickCopyRules":{}}

**Comment by Sjano** [comment]
33.{8,}
Would block +3312345678
But not. +331234567

44.*
Would block: +447362040858

**Comment by aj3423** [comment]
To block non-French numbers, you can set two regex,
- blacklist rule `.*` priority 1, this blocks all numbers 
- whitelist rule `33.*` priority 2, this allows numbers start with 33

Adjust the second rule to make it more precise.

**Comment by Paul75** [comment]
But does this mean that you have to manually block the numbers? So the program is not the type to block from a list of fraudulent or something else?

**Comment by aj3423** [comment]
> But does this mean that you have to manually block the numbers? So the program is not the type to block from a list of fraudulent or something else?

Do you mean a database contains spam numbers, like what YetAnotherCallBlocker does?  There isn't such database in this app, you need to block or allow numbers manually.

**Comment by Paul75** [comment]
Thanks

**Comment by Gwened** [comment]
> Hi, If you want to block all call bots ("Démarchage") like your energy provider etc., you can block all officially assigned numbers with this rule
> 
> (?:33|0)?(1(?:62|63)|2(?:70|71)|3(?:77|78)|4(?:24|25)|5(?:68|69)|9(?:48|49)).*
> 
> I'm using it successfully.

Thanks, the UI was driving me nuts!
Especially the hint on "Number Rules" tells it ignores leading + and zeroes. Based on your regex I guess the part about zeroes is not true?

**Comment by aj3423** [comment]
@Gwened There could be one or two leading 0s, they would've made the regex a lot more complex, so I removed them before the regex matching, so just keep in mind that there are no leading zeroes.
This part `(?:33|0)?` matches either leading 33 or 0, but actually it will only match leading 33. The `|0` here is redundant but it would still work.

**Comment by alxrdn** [comment]
For French _plan de numérotation démarchage_, I would enhance it to
`(?:33)?(1(?:62|63)|2(?:70|71)|3(?:77|78)|4(?:24|25)|5(?:68|69)|9(?:48|49))\d{6}`
