### ISSUE TITLE
Copy number to Clipboard from Notification

### ISSUE THREAD

**Issue by newhinton** [aj3423/SpamBlocker#91]
As in the title.

It can be useful to copy the number to the clipboard from the notification, especially to cross-check the number for known spam calls. Thanks!

**Comment by aj3423** [comment]
> to cross-check the number for known spam calls

I don't quite understand why and how to do that, can you elaborate more on this? 

To me, a "Copy Number" button in the notification would be redundant in most cases. When I want to copy a number for testing, I press the notification to launch the call app, then I can long press the number to copy it, just one more step than copying it directly in the notification.

**Comment by newhinton** [comment]
> I don't quite understand why and how to do that, can you elaborate more on this?

There is a german website where users can report numbers for spam calls. Usually if i recieve a call from an unknown number, i can then check the reports there, and if there is no report, i might call back later to check who called me. 

Usually there are tons of reports of those numbers, so i know not to bother.


> then I can long press the number to copy it

This does not seem to work for me (v1.15, fdroid)

**Comment by aj3423** [comment]
I'll improve QuickCopy to support this.

**Comment by aj3423** [comment]
Done in the latest tag, set a QuickCopy rule like this to copy the number from the notification:
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/9427f0ce-d471-43c1-b8a6-a81b24962a4f)
