### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SchikoPiko** [aj3423/SpamBlocker#95]
After I made a setting to block unknown callers, the app unfortunately crashed. I should post the error code here. 

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
	at spam.blocker.service.CallScreeningService.onScreenCall(Unknown Source:16)
	at android.telecom.CallScreeningService$1.handleMessage(CallScreeningService.java:140)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by aj3423** [comment]
What does that number look like in the history of the dialer app? Is it something like "unknown number" or does it actually have some digits?

**Comment by SchikoPiko** [comment]
I have entered an unknown number. No digits.

**Comment by aj3423** [comment]
How did you enter that number?

**Comment by SchikoPiko** [comment]
I wanted to block the unknown calls directly. For the priorities list for the calls, do you always have to Enter a number of 1 to 10?

**Comment by aj3423** [comment]
Not sure what you mean by the "enter", can you show me how to reproduce the crash?

**Comment by SchikoPiko** [comment]
Do you mein this?

![Screenshot_20240708_125949_SpamBlocker.jpg](https://github.com/aj3423/SpamBlocker/assets/155118448/dfc25799-c5fc-444f-9029-89075b3be42e)

**Comment by aj3423** [comment]
I see, you are using "unknown number" as the rule. The crash happened on a call with unknown number, it was trying to get the number and it failed for some unknown reason. 

This has been fixed in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/9838899998. 

Now, when there is a call like this, the app will try different ways to get the number, if none of them works, the number will be empty string "". You can set a rule like `.{0}` or `^$` for this, but not `unknown number`, this label is just displayed by the dialer app.

**Comment by SchikoPiko** [comment]
I understand, thank you for pointing it out.

**Comment by SchikoPiko** [comment]
I would like to know if there is a detailed guide by allowing me to set everything completely.

**Comment by aj3423** [comment]
Currently the balloon tips are the best instructions, for the number rules, there are some typical regex patterns on the readme page: https://github.com/aj3423/SpamBlocker/?tab=readme-ov-file#filters.

**Comment by SchikoPiko** [comment]
I saved it. I hope I get something out of it. thank you. the balloon tips I didn't notice. thank you very much
