### ISSUE TITLE
[Enhancement] Option to not remove leading 0\+ in Number Rules

### ISSUE THREAD

**Issue by sirtao** [aj3423/SpamBlocker#97]
As the title says.

The stripping of leading 0s and +s is causing me quite the headache with filtering domestic prefixes.  
For all purposes and intents it's impossible to differentiate between an international prefix and an Italian phone number, making the main reason I installed the app(automatically refuse international numbers) moot.

I understand wanting to simplify things for less tech-savvy people(though I'd argue anybody using a regex wouldn't fall under the description in first place) but I'd like an option to have full control.

**Comment by aj3423** [comment]
Yeah, I'll add a regex flag "raw number" for not optimizing the number.

**Comment by aj3423** [comment]
Done in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/9890663032
