### ISSUE TITLE
Duplicate Notifications for Spam Messages

### ISSUE THREAD

**Issue by 4DEATH** [aj3423/SpamBlocker#98]
**Description**

When a spam message is caught by a rule in SpamBlocker, it should prevent Google Messages from triggering an SMS notification.

**Current Behavior**

Upon receiving a message, both Google Messages and SpamBlocker send notifications. The SpamBlocker notification is silent as per the settings, but Google Messages still sends a standard notification.

**Expected Behavior**

When SpamBlocker catches a spam message, Google Messages should not send a notification.

**Setup Details**

    Device: MIUI Global 14.0.3
    OS: Android 13
    App Version: SpamBlocker 1.17, Google Messages messages.android_20240621_00_RC03.phone_dynamic

**Additional Information**

    SpamBlocker is not set up as the caller ID & spam app (Google Phone app is used for that purpose, not enabled for calls).
    All other necessary permissions for SpamBlocker are granted, including battery optimization and autostart.

Thank you for developing this much-needed app! Also open for replacing Google Messages if issue is not fixable without doing so.

**Comment by aj3423** [comment]
You don't need to replace Google Messages, just disable all notifications of it in system settings, let this app take over the notification, as described in the balloon tip of "Message Rules", not very intuitive, I'll try to find some better way to inform user about this.

**Comment by 4DEATH** [comment]
Yeah i just read that again ,oops. I probably took first part of info bubble wrong. "It blocks notifications" it says. Probably shold say mutes or replaces, and "disable default app notifictions" part should be first sentence for clarity.

**Comment by aj3423** [comment]
Indeed, it's misleading, I'll improve it, thanks.

**Comment by aj3423** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/0dacce89-6c5f-4085-9b2d-f059e41e9f4f)

For Android 13+ there will also be a popup warning.
![image](https://github.com/user-attachments/assets/3f70bad3-0969-4cea-ba3f-806a43b48cc2)
